### ISSUE TITLE
Problem with size of the player + qualty; have to reload

### ISSUE THREAD

**Issue by JBey4you** [YePpHa/YouTubeCenter#1017]
I have set the player size at 16/9. I wanted to try 3/2, so I chose this option. I didn't like it, so I went back to 16/9. Unfortunately, this appears sometimes. I have to reload the page in order to fix it. Plus, the quality of the video doesn't change there (I have set 1080p). When I reload the page, the video is good (size + quality).

Maybe it's related to SPF, I'm not sure. I know you had a fix recently, so it's uncertain right now.

![capture d ecran 2014-10-15 a 16 24 00](https://cloud.githubusercontent.com/assets/7979756/4646915/5199dae2-5477-11e4-9fc4-99f7ca0358f1.jpg)

**Comment by ireun** [comment]
Main thread for this is now: #1844.
