### ISSUE TITLE
Option to reverse playlist order

### ISSUE THREAD

**Issue by ocbaker** [YePpHa/YouTubeCenter#104]
Playing let's plays is a great way for me to wind down but unless they provide a correctly ordered playlist for me to watch the uploaded videos playlist goes in reverse!

It would be great if there was a simple checkbox in the playlist combo selector to reverse the order in which videos will be queued!

**Comment by ronCYA** [comment]
What is the progress/prospect of this happening at the moment? And which of these is the 'official' request?:

#104
#396
#955

**Comment by FichteFoll** [comment]
\*subtly pointing at labels\*
