### ISSUE TITLE
Youtube implemented permanently the fexp that breaks the auto html5 sizing

### ISSUE THREAD

**Issue by Yonezpt** [YePpHa/YouTubeCenter#1083]
As before expected in https://github.com/YePpHa/YouTubeCenter/issues/1017#issuecomment-59236445 youtube went ahead and implemented the hardcoded player sizes for the html5 player, now the progress bar and video frame won't adjust to the size of the player resulting in the return of the previously linked issue.

**Comment by svnpenn** [comment]
https://github.com/svnpenn/bm/issues/14

**Comment by svnpenn** [comment]
https://github.com/svnpenn/bm/issues/15

**Comment by svnpenn** [comment]
https://github.com/snarly/yt6/issues/1
