### ISSUE TITLE
Video only takes up part of screen when viewing in 720p Large-Centered player size

### ISSUE THREAD

**Issue by roger778876** [YePpHa/YouTubeCenter#1117]
Here is what it looks like:
![youcenter](https://cloud.githubusercontent.com/assets/9500216/4872436/3abbc642-61e6-11e4-8e63-e6e546172ac9.JPG)

My General Player settings:
![youcenter2](https://cloud.githubusercontent.com/assets/9500216/4872438/44b2f346-61e6-11e4-9cd7-50f268305dae.JPG)

My YTCS file:
https://www.dropbox.com/s/y3ix2hciaahcmdg/ytcenter-settings222.ytcs?dl=0

**Comment by AJDxB** [comment]
![ntgjnfgmgfmfgmfgmfnbfg](https://cloud.githubusercontent.com/assets/12012474/7217434/c14b08e2-e63b-11e4-8822-9e0db366d0b3.PNG)
This solved my problem, dont know about the rest though...

**Comment by sleeksorrow** [comment]
bad news, this issue seems to be back now with chrome 43 stable, at least for me running on Ubuntu 14.04. Using latest YTC Developer Version build 525

**Comment by roger778876** [comment]
yep, now it covers the description! i have to resize it in order to see the channel or the description, etc.
