### ISSUE TITLE
A permanent fix for the html5 player resizing problem, hopefully

### ISSUE THREAD

**Issue by Yonezpt** [YePpHa/YouTubeCenter#1125]
I have been working around this ever since the problematic html5 player experiment was implemented permanenlty (https://github.com/YePpHa/YouTubeCenter/issues/1083) and a couple of days ago I managed to intercept the functions that are requesting the fixed sizes from the script.

The 'hack' worked flawlessly, but it was just for a short duration since de html5 script changed 4 times and eventually the minifier changed the pointers that I was using which ruined the hack, however I also managed to avoid this issue.
The following is the polished and minfier-proof (I hope) script that I managed to create:

``` javascript
function detour(b, c) {
  return function() {
    // we will call the original sizes, store them in the "changed" variable and
    // check wether it has the width and height properties. If it does then we
    // will change them, if not then we relay whatever other arguments the
    // unknown function calls require
    var changed = b.apply(this, arguments);
    if (changed.width && changed.height) {
      // the variable "c" is just a way to distinguish between sizes for the video canvas
      // and sizes for the progressbar, and its components
      changed.width = (c) ? document.querySelector('#movie_player').getBoundingClientRect().width : document.querySelector('.html5-video-container').getBoundingClientRect().width;
      changed.height = (c) ? document.querySelector('#movie_player').getBoundingClientRect().height : document.querySelector('.html5-video-container').getBoundingClientRect().height;
    }
    return changed;
  };
}
var i,
  j;
try {
  // first of all we will find our main pointer that targets the two functions we want
  // to intercept and for that we will iterate through all the keys in the player instance
  // object (which is acquired by attaching a variable to the Application.create function
  // which you -YePpHa- already know), find our target functions and "patch" them
  // accordingly
  for (i in playerInstance) {
    // first filtering step is to only work with keys that are objects, aren't null objects
    // and contain the .element key - there is only one object that contains it which
    // is the one that we want
    if (typeof playerInstance[i] === 'object' && playerInstance[i] && playerInstance[i].element) {
      console.log('Pointer: ' + i);
      // now that we have our main pointer we will iterate through all its keys
      // to find our target functions
      for (j in playerInstance[i]) {
        // here we check for the main properties of the functions that we want to
        // find and for that we will check for certain details inside the functions
        // that we are currently iterating. never use properties that can be changed
        // when the script is minified -such as named functions- instead use
        // native javascript nomenclature which is less likely to change.
        // in this case both our functions contain the return"detailpage" text
        // so we will be looking for that line in each function.
        // we also only want to look for functions, the rest will only be a waste of time
        if (typeof playerInstance[i][j] === 'function' && /return"detailpage"/.test(playerInstance[i][j].toString())) {
          // now that we find one of the two functions we will check which one
          // we detect so we can manipulate it accordingly.
          // there are two functions: one relays the dimensions to the progressbar
          // elements and the other is for the video element size. 
          // they are almost identical, but there are small differences which
          // we wil use to detect which one is for the progressbar and video,
          // the later ends with !0) while the former doesn't, so we will use
          // that information to regulate the functions' manipulation
          if (/!0\)/.test(playerInstance[i][j].toString())) {
            console.log('Progressbar: ' + j);
            // here we simply wrap the original function to force it pass
            // through our detour function before returning the size values.
            // in this case I add a '' so that the detour function can tell which
            // function is being called and change the sizes accordingly
            playerInstance[i][j] = detour(playerInstance[i][j], '');
          } else if (!/!0\)/.test(playerInstance[i][j].toString())) {
            console.log('Canvas: ' + j);
            playerInstance[i][j] = detour(playerInstance[i][j]);
          }
        }
      }
    }
  }
} catch (e) {
  console.error(e);
}
```

As of the current time of this post, the most recent html5 script is:
https://s.ytimg.com/yts/jsbin/html5player-en_US-vflKCJBPS/html5player.js

The respective functions that we are targeting are:
playerInstance.j.Fb » For the progressbar
playerInstance.j.ib » For the video

And here are the original functions from the html5 script after passing through the jsbeautifier.org:

``` javascript
f.Fb = function () {
  var a = this.app.R();
  return 'detailpage' != a.ba || a.Za ? N7.H.Fb.call(this) : ZM(a, !0)
};
f.ib = function () {
  var a = this.app.R();
  return 'detailpage' != a.ba || a.Za ? N7.H.ib.call(this) : ZM(a)
};
```

The f.Fb function is almost the same as the f.Eb function mentioned here: https://github.com/YePpHa/YouTubeCenter/issues/1083#issuecomment-60857608
It also was named f.Eb before it went through a minifier version change, except this one is called when args.el = detailpage (which I assume to be set by default when watching in youtube even if it doesn't list in the dom). Either way, I am assuming that the same logic I used for the fix can also be adapted for the other similar function calls which are supposedly made when the args.el != detailpage (embedded video, for example), in which case it's a simple matter of tweaking the last filters in order to also modify those similar functions, but I don't think it will be necessary since this problem is restricted to the player in the youtube pages, at least for now.

This works perfectly well with me, but I am using a CSS style that changes the player size to a 16:9 AR which increases and decreases according to the window size (basically the same as the Fit to Content option in YTC) and because of this it might not return the sizes correctly with the YTC script, so tweak the detour function according to your needs if such is the case. The way I set it up is suppose to result in exactly the way the player behaved before the experiment became permanent, so I don't expect that much tweaking is needed. It looks for whatever sizes the player has and changes to those accordingly.

If something is not working right or there is anything else that might have escaped my attention please let me know so that I can see what I forgot. It can happen, I doubt 2 months of learning javascript in my free time make me a professional at this.

**Comment by maximang** [comment]
Am I the only to still have this problem sometimes?

**Comment by Yonezpt** [comment]
@maximang If you are not using the latest developer version then you will most likely face this problem.

**Comment by maximang** [comment]
@Yonezpt What you mean by "developer version". I use the userscript in version 2.1.7 on Chrome (Tampermonkey).

**Comment by ErdeFB** [comment]
@maximang https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by maximang** [comment]
@ErdeFB Thanks! :)
