### ISSUE TITLE
"Warning: Unresponsive Script" Error when running YC Extension

### ISSUE THREAD

**Issue by LemGambino** [YePpHa/YouTubeCenter#1130]
Hi everyone, I just redownloaded Youtube Center after not using it for a while. However, after downloading the .xpi file and loading the home page, I got an unresponsive script error:

Script: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/browser/extensions/%7B82AF8DCA-6DE9-405D-BD5E-43525BDAD38A%7D.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://skype_ff_extension-at-jetpack/skype_ff_extension/data/jquery-2.1.0.min.js:26

I have no coding/debugging experience, can someone help me sort this out?

**Comment by Sartan4455** [comment]
I think it's not youtube center anymore(if it ever was?). I think it's more firefox and/or flash related .  
The problem reduced when YC was close, causing a red herring,  but over time it became a problem with no extensions enabled at all.  After a full profile wipe(refresh firefox) and reinstall of YC - youtube no longer lags.  Conclusion: this is not a YC issue.
Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0
