### ISSUE TITLE
Settings feature request: Ability to "Don't change the Like/Dislike Button" Same for the "Rating Bar" Also a "Reset to YouTube default style" button

### ISSUE THREAD

**Issue by 3ICE** [YePpHa/YouTubeCenter#1186]
Hi,

Currently there is no way to tell YouTubeCenter to leave the UI elements below the player unchanged. And once I change something I am stuck with it; There is no reset to default button. Unless we count the reset everything button in General that I'd rather not click. (Don't want to lose all my settings.)

I'd prefer an on/off button over a reset button on those tabs, but having both would be the most welcome addition.

Reasoning:
I am okay with the way YouTube looks by default. Most other people probably are as well. The bar used to be red/green, now it's blue/gray. Blue is fine, but YouTubeCenter remembers the red/green style because it was the default and I have been using it for so long. Restores it every time too, perfectly.

I don't know what the default values are now.

Restyling the controls at each page load probably takes some valuable time and makes initialization a little more laggy than it should be.

Please add an on/off switch to these pages:
UI → Like/Dislike Button
UI → Rating Bar

Thank you for your consideration.

Sincerely,
Daniel "3ICE" Berezvai

**Comment by kancaras** [comment]
Hello. Youtube center is very bugy lately. Not long ago it had embeded videos broken, so i swaped to developer version which fixed it. 
But then developer version got updated and now Like/Dislike buttons dont function as they use to. If i keep YoutubeCenter functionality enabled for them, buttons dont change color at all, if i disable that functionality it is still bugy - blue color stays blue all the time, even if i dislike the video (after i liked it before, to see if it changes color). If i disable the addon , everything come back to normal, even the interective stuff like "added to liked videos" and share bar. 
I wonder why disabling some functionality isnt the same as disabling whole addon. Like disabling Liked/Dislike Button, or External Player Embeded. It could solve bug problems imideately, by disabling unwanted features. Btw is it posible to download old developer versions?
