### ISSUE TITLE
Playlist "list" on watch page overflows

### ISSUE THREAD

**Issue by SuperSajuuk** [YePpHa/YouTubeCenter#1318]
If you go to a video as part of a playlist (the &list= will be in the url), the following happens in the picture below:
![yt visual bug](https://cloud.githubusercontent.com/assets/8324490/5508986/ec79660c-87aa-11e4-8857-1347f951daf8.jpg)

EDIT: When I use "Inspect Element" to remove the overlapping sections, it seems to be a possible youtube change, which now shows the whole contents of the playlist instead of only being 5-6 videos in length and using a scroller to find the rest.

EDIT2: Checked a playlist with many videos, the same thing shows up. Either it's a change on YT's end, or a bug with the extension. I'll check if disabling the extension fixes it.

EDIT3: Doesn't happen with the extension disabled, hopefully this can be looked into for a fix by either @Yonezpt or @YePpHa :)

**Comment by SuperSajuuk** [comment]
It's been close to a month.... is this going to get fixed at any point? We've already established this is a bug, so I'm surprised about the lack of a fix for it. Tagging @YePpHa in case he missed this.

**Comment by Yonezpt** [comment]
@SuperSajuuk This has been fixed already, see https://github.com/YePpHa/YouTubeCenter/commit/58990095744e98ac9c11c79cd7fa5aba6b107073

The latest dev build is 470

**Comment by SuperSajuuk** [comment]
Oh ok. It would be better if there were more "stable" releases, so I don't have to use a developer version just to get a fix though....
