### ISSUE TITLE
video keeps playing in the background

### ISSUE THREAD

**Issue by fighterisr** [YePpHa/YouTubeCenter#1340]
i am using firefox 24.0.5 and youtube center build 461.
when i am moving out of the video page, for example clicking on the youtube logo or going to the channel's page, the video keeps playing in the background and does not stop automatically (you keep hearing the audio.
it happens with the flash player of youtube.
by the way, browsing into a different video page will stop the last and play the video.

**Comment by ErdeFB** [comment]
If you have SPF enabled in YTC options, try disabling it.

**Comment by fighterisr** [comment]
hmm it works.
strange, i am sure that i already tried that in the past. spf didn't cause any problems long ago, but then some build broke it, i don't remember which.

**Comment by ErdeFB** [comment]
Glad to hear it seems to be solved!. Please close this issue after you verify it works.

**Comment by fighterisr** [comment]
ah, i didn't see the button, i will close the issue now, thanks.
