### ISSUE TITLE
Feature Request: Default homepage to "My Subscriptions"

### ISSUE THREAD

**Issue by r3Fuze** [YePpHa/YouTubeCenter#1347]
When I go to youtube.com or click the YouTube logo I go to the "What to watch" page. This page is pretty useless to me and I'd much rather have it go to the "My Subscriptions" page. A simple checkbox to enable this would be pretty convenient.

**Comment by Yonezpt** [comment]
This feature already exists, it allows you to link to whatever section you prefer the most.

Go to Youtube Center Settings > UI > General

Where it reads "YouTube logo link" is where you can type the target location you want by default for the youtube logo. In your case all you have to type is `/feed/subscriptions`

Remember to refresh youtube and then try clicking on the youtube logo.

**Comment by r3Fuze** [comment]
Oh, sorry. I wasn't aware of this. Thanks!
