### ISSUE TITLE
1080p60fps not available with DASH enabled

### ISSUE THREAD

**Issue by raywu2478** [YePpHa/YouTubeCenter#1348]
I'm using the developer build 461 as a GM script on firefox 34.0.5. media.mediasource.enabled is set to true, media.mediasource.ignore_codecs is set to false. DASH is enabled, other settings can be seen here: https://imgur.com/a/hUdiu

I'm not getting 1080p60 in videos that offer that format, only 720p at 30fps. Normal 1080p 30fps videos are still available in 1080p. I'm aware that DASH is needed for 1080p video, but I can't get the 60 fps working. If I set media.mediasource.ignore_codecs to true, the video will play in 1080p60, but weird thing starts to happen, like the video progress will read 0:00/0:00, then they will both count up at the same time to 0:01/0:01, 0:02/0:02, etc. The video will end after about 20 seconds regardless of how long the actual video is.

I was able to play 1080p60 with this setting before, but then I restarted my computer and then it stopped working.

Any help is appreciated.

**Comment by ZeDestructor** [comment]
Works nicely on Nightly 64bit on Windows 8.1 64-bit. Can you check with Nightly? Based on the bug tracking for FF MSE support, mainline/stable support is still incomplete, and that's why it's preffed as disabled in stable versions.

**Comment by Yonezpt** [comment]
Current Firefox stable versions don't work properly with 1080p30fps and 60fps in html5 player. This is not a YTC problem, it is a Firefox limitation.

**Comment by ErdeFB** [comment]
Quite. Firefox 34 does not support MSE + H.264. In the future, to see what your browser supports, visit 
https://www.youtube.com/html5

As this issue is not related to YTC, could OP please close this issue report. 

Thanks.

**Comment by raywu2478** [comment]
Using Nightly solves the problem, but since it's not a stable release, so there are some issues with normal web browsing.

I'm really wondering how it worked with the exact same settings before, but now I can't replicate the results.

**Comment by ZeDestructor** [comment]
Ppossibly a change at Google.. Welcome to webapps: no changelogs anywhere public, no announcements, nothing, just.. something changed.

**Comment by Yonezpt** [comment]
@raywu2478 That's because whenever the html5 jams in stable firefox, it stays jammed/bugged until you revert the `about:config` changes you mentioned, restart firefox and re-enable them again.
