### ISSUE TITLE
YTC just not working? (Firefox)

### ISSUE THREAD

**Issue by Vwyx** [YePpHa/YouTubeCenter#1350]
I'd been using YTC for about a month, now, but about 2 days ago it just stopped working. I tried uninstalling then reinstalling, both the version on the mozilla addon site and on this github site, and neither has worked. I've tried disabling my other addons, and that didn't help either. There's no gear to change settings where it should be beside my Youtube username, and when I try to go from my addon manager to the settings, it just loads a regular Youtube page. Is there anyone who knows how to fix this, or even what might be wrong?

**Comment by Zarggg** [comment]
To start, completely remove all versions (addon and/or userscript) currently installed in Firefox, clear the cache, then close and reopen the browser. Additionally, you can create a new profile in Firefox. The goal in this step is to make sure that no part of YTC is present in your profile before re-installing. Having multiple copies of the script installed can cause problems.

Then, install the current developer build, either the userscript or the addon. Make sure you install only one. If the configuration menu still does not appear, then there is an issue specific to your build of Firefox.

**Comment by Vwyx** [comment]
It's still not there, so I guess it's Firefox.

**Comment by Yonezpt** [comment]
I am currently using Firefox v34.0.5 with both userscript and addon latest YTC developer version 461, and it is working correctly.

What Firefox version are you using?

**Comment by Vwyx** [comment]
34.0.5

**Comment by ErdeFB** [comment]
Did you try installing the developer version?
https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by Vwyx** [comment]
The developer version seems to be working for me. Still no idea what happened to the other version. I'm going to put it down to some kind of script on my end that still messed things up despite my disabling it. I suppose I'll stick with the developer version and pray.

**Comment by Yonezpt** [comment]
It's probably because you were using the outdated v2.1.0, I just checked that version and the settings' button wouldn't show up for me either.

Glad to see that ErdeFB managed to help you out. If there isn't anything else then could you close the issue? It's the "Close issue" button to the left of the green button below the reply box. The less issues are open, the less work the addon author will have.

**Comment by Vwyx** [comment]
I was using the 2.1.7 version. I tried with the version on the Mozilla Addon site, which I believe was the 2.1.0 version, but I was originally using the one on the YTC Github. The issue wasn't really solved, I guess, but I'll close it anyway.
