### ISSUE TITLE
Specific youtube video won't play with YTC enabled.

### ISSUE THREAD

**Issue by mzso** [YePpHa/YouTubeCenter#1352]
With this video playback won't start: https://www.youtube.com/watch?v=KO0hy2olg9k
The symptoms are the same as in #1256, but while none of the embedded videos start so far this is the only video on the youtube website that won't start playback.
With YTC disabled the playback works.
It's on FF nightly with MSE enabled.

**Comment by mzso** [comment]
Curiously while the embedded videos work with the firefox addon variant this doesn't.

**Comment by myobfool** [comment]
I'm having the same issue.  If I force to the html5 player most video's work.  If I leave flash on (and I've had multiple versions including the current 16 (or so) UTC being up will have some of the video's refuse to play with the errors already cited.

**Comment by LittleVulpix** [comment]
This video works for me, using the greasemonkey version of YTC.

**Comment by mzso** [comment]
I ran into another video that doesn't start: https://www.youtube.com/watch?v=e2Q4j0iPSgc

**Comment by GoaLitiuM** [comment]
I can confirm, none of these linked videos wont play for me. There is following error present in Web Console after attempting to open the link:

TypeError: stream.dimension is undefined           watch:569:10

**Comment by ErdeFB** [comment]
All of the linked videos played for me.
Firefox 36, latest YTC add-on developer version at time of writing.
HTML5 player.

**Comment by mzso** [comment]
Not very informative if you guys don't even tell the browser/version and the variant of YTC you were using.

**Comment by mzso** [comment]
Seems to be working now I guess they fixed something in firefox.

**Comment by mzso** [comment]
I take that back. It only works with the addon version not with Greasemonkey.

**Comment by mzso** [comment]
Now it seems to be working. Don't know what changed.
