### ISSUE TITLE
Entire page reloads when loading quality info on thumbnails [solved]

### ISSUE THREAD

**Issue by Butt88** [YePpHa/YouTubeCenter#1356]
Whenever YT/C loads the Quality (ie "1080p@60") to display in the thumbnail, the entire page reloads. When set to "only on mouse-over" any mouse-over causes a reload (making it hard to actually open videos) and when set to the other two options, the page gets caught in a never-ending reload-loop.

I say "the page" as it doesn't matter if it's the subsription list or a playlist, new videos or old ones. No other thumbnail setting causes it.

Windows 7 HP
Firefox 34.0.5
YTC devbuild 461

**Comment by ErdeFB** [comment]
Try disabling all other add-ons besides YTC and see if the problem still persists as I'm not experiencing this on Firefox Developer Edition (36) and the latest YTC Dev build.

**Comment by Butt88** [comment]
well I'll be damned. conflict with Youtube Unblocker. Nevermind then. Thanks!

**Comment by ErdeFB** [comment]
No problem. Feel free to click the "close issue" -button at your earliest convenience.
