### ISSUE TITLE
"Dark player background" setting breaks video alignment

### ISSUE THREAD

**Issue by NightKev** [YePpHa/YouTubeCenter#1357]
Lately, if I enable this setting, the video moves to the left side of the page instead of being centered. Disabling it fixes the alignment issue. Using the developer version makes no difference, it still acts the same.
Edit: Forgot to mention, I tested this in both Firefox and Chrome.
Example:
![dark bg](https://cloud.githubusercontent.com/assets/849285/5675437/eec9da40-9772-11e4-9922-ca412943813a.png)
![regular bg](https://cloud.githubusercontent.com/assets/849285/5675438/eece465c-9772-11e4-9ed4-09350cc6577b.png)

**Comment by RedDeadElite** [comment]
This fixed it for me: Go to Settings>>Player>>Player Size>>Only On Stage Mode. Make sure it's ticked and reload the page if necessary.

**Comment by NightKev** [comment]
Ah, that does seem to have fixed it. Thanks for the info.
