### ISSUE TITLE
"watch later" is somehow bugged?

### ISSUE THREAD

**Issue by Leifman27** [YePpHa/YouTubeCenter#1360]
well to put it simple, i had the "watch later" in the UI always selected as "when u hover over the thumbnail" it will showup on the buttom right (where it shows is really irrelevant but just saying)
the entire "when mousing over the thumbail" seems to be broken for me... it just never showsup now (possibly broken in the past day or two)
the option itself still works if u put it "show always" just the when hovered over thumbail seems to not work anymore

**Comment by endymion0000** [comment]
Yes. I'm seeing the same thing.

**Comment by BradJJ** [comment]
same. also, the 3 vertical dots to "hide these videos" is over the thumbnail in the top right corner when in grid view, right where i have the "watch later" button.

**Comment by 3ICE** [comment]
Me too. As a temporary workaround I set it to Bottom left - Always. (While I add the 100-200 new videos on my feed that accumulated over the week.)

**Comment by AlbinoDrought** [comment]
Yep, works when I set it to a different location and "Always" under the UI tab. Was scared that Youtube had removed it

**Comment by BradJJ** [comment]
3ICE - how do you see videos over a day old? my feed only goes back 1 day now. for a couple months i could go back several days but youtube changed the feed again recently... i might have too many subscriptions though at 300+

**Comment by 3ICE** [comment]
Yeah, me too... :(

The trick now is to check multiple times a day, and use the Watch Later button excessively. (My backlog is 500 videos at the moment.)

Also, I put my subscriptions in lists, that helped a lot.
There is: Active (Channel has multiple uploads per day)
and: Inactive (New cool video released maybe once a week)

The inactive list goes back an entire month. That way I can be sure I didn't miss out on any of the important, rare videos.

The active list also goes back a week too, at the moment.
![image](https://cloud.githubusercontent.com/assets/5385790/5773777/a0482a08-9d66-11e4-8e55-e5e3b0954809.png)

If it doesn't, I split it into two: Active1 and Active2.

**Comment by YePpHa** [comment]
Issue has been fixed in the latest developer version.
