### ISSUE TITLE
chrome html5 video looks odd

### ISSUE THREAD

**Issue by dem0z** [YePpHa/YouTubeCenter#1364]
so am a new user to chrome and whenever i try to use html5 instead of flash the video goes like this http://i.imgur.com/jc0uq5H.png can i fix this somehow?

**Comment by ErdeFB** [comment]
Try the developer version from here:
https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by dem0z** [comment]
thanks that version fixed it.

**Comment by ErdeFB** [comment]
No problem. Please close this issue report at your earliest convenience.
