### ISSUE TITLE
Rating count / bar in thumbnail hides "watch later" button

### ISSUE THREAD

**Issue by krisu5** [YePpHa/YouTubeCenter#1366]
When rating count or rating bar is enabled and watch later button is set to visible only when mouse is over thumbnail, button doesn't show up.

**Comment by TheTruthSentMe** [comment]
+1
I have this issue as well.

**Comment by ReporterX** [comment]
Well I believe it is due to this issue #1369

**Comment by YePpHa** [comment]
Fixed.
