### ISSUE TITLE
"Related Videos" list messed up

### ISSUE THREAD

**Issue by ReporterX** [YePpHa/YouTubeCenter#1367]
You need a youtube account and open one of **your uploaded videos** (it is important!).
Then you will see the first related video being cut off a little bit, like the following:

![YouTube Screenshot](http://snag.gy/8T06d.jpg)

Firefox 34.0.5
YTC Dev Build 461

**Comment by ErdeFB** [comment]
Not happening to me at least and I'm on Firefox 36 and latest dev version of YTC. You should try it if you already haven't. You can get it from: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

PS: Next time when you open a issue, please list your browser and it's version and also YTC version.

**Comment by ReporterX** [comment]
@ErdeFB 
Firefox 34.0.5
YTC Dev Build 461

**Comment by Yonezpt** [comment]
@ReporterX Is it possible tha this issue is being caused by the fixed that you mentioned here: https://github.com/YePpHa/YouTubeCenter/issues/1345#issuecomment-68638681

**Comment by ReporterX** [comment]
@Yonezpt Thanks for the reply. No, the CSS fix is not the culprit. This bug won't occur if I disable the script.

Note that you have to visit '''your own uploaded video'''. It won't occur if you watch other's videos.

**Comment by ReporterX** [comment]
@Yonezpt 

Without YTC Dev Build:
```CSS
<div id="watch7-sidebar" class="watch-sidebar">
```

With YTC, when I watch other's videos:
```CSS
<div id="watch7-sidebar" class="watch-sidebar" style="top: -360px;">
```

With YTC, when I watch my own uploaded videos:
```CSS
<div id="watch7-sidebar" class="watch-sidebar" style="top: -408px;">
```

Which option/feature causes this change? Any clues?

**Comment by Yonezpt** [comment]
Sorry for the delay, didn't have any uploaded video to test the layout so I had to upload one and now I am able to replicate the issue.

It seems Youtube changed something, yet again, causing the code to malfunction, specifically these lines in YTC source code:
line 22543
````javascript
        // Sidebar
        if (sidebar) {
          if (!large && !document.getElementById("watch7-playlist-data")) {
            var mt = calcHeight + pbh + (document.getElementById("watch7-creator-bar") ? 48 : 0);
            if (ytcenter.utils.hasClass(document.getElementById("watch7-container"), "watch-branded-banner") && !ytcenter.settings.removeBrandingBanner)
              mt += 70;
            sidebar.style.top = "-" + mt + "px";
          } else {
            sidebar.style.top = "";
          }
        }
````

What is happening is that in the line `var mt` it is trying to calculate the new top position of the sidebar wether the user is watching his own video or someone else's. When YePpHa wrote that section, the sidebar was supposedly 48px higher than it is now when compared to the page layout when watching someone else's video. Now it seems that the sidebar isn't higher than the default one, which supposedly leads me to believe that simply removing the end of the mentioned line fixes the issue, so the above code should be replaced with this fixed one:

````javascript
        // Sidebar
        if (sidebar) {
          if (!large && !document.getElementById("watch7-playlist-data")) {
            var mt = calcHeight + pbh;
            if (ytcenter.utils.hasClass(document.getElementById("watch7-container"), "watch-branded-banner") && !ytcenter.settings.removeBrandingBanner)
              mt += 70;
            sidebar.style.top = "-" + mt + "px";
          } else {
            sidebar.style.top = "";
          }
        }
````
I just tested and it looks right for me now.

**Comment by ReporterX** [comment]
For those who are interested:

**Temporary fix**

Install Stylish addon.
Go to youtube.com
Write new style -> For youtube.com...
Copy this code:
```css
#watch7-sidebar {
    top: -360px !important;
}
```
Name the style. Save.

@Yonezpt Thanks a lot for your detailed reply.

**Comment by ReporterX** [comment]
This bug is fixed. Closed.
