### ISSUE TITLE
Watch Later & Time Code - "Only when mouse is (not) over thumbnail" is broken

### ISSUE THREAD

**Issue by ReporterX** [YePpHa/YouTubeCenter#1369]
Go to "Options > UI > Video Thumbnail"

For these info:
* Watch Later
* Time Code

Neither option works:
"**Only when mouse is over thumbnail**" - In fact, it will never show up
"**Only when mouse is not over thumbnail**" - In fact, it is always visible

Firefox 34.0.5
YTC Dev Build 461

**Comment by jaryth000** [comment]
Having the same issue here myself. Stats below:

Browser name: Firefox
Browser version: 28.0
Browser engine: Gecko, SpiderMonkey
YouTube Center version: Developer Version - Build #461
Addon type: Chrome extension; Webstore edition
Debug log: https://gist.github.com/f63ecb9aaadc976674bc
Issue description: Watch Later no longer appears when set to mouse hover.

How to reproduce the issue: Enable mouse hover, and attempt to hover. Feature was working in this same version (browser and plugin) previously, as such it is now broken most likely to something Google has done.

**Comment by Leifman27** [comment]
https://github.com/YePpHa/YouTubeCenter/issues/1360
already reported and known

**Comment by YePpHa** [comment]
Fixed in latest dev version.
