### ISSUE TITLE
What is Guide Mode?

### ISSUE THREAD

**Issue by ReporterX** [YePpHa/YouTubeCenter#1370]
> Guide Mode
> 
> The guide mode feature gives you the option to have the guide to be opened or closed every time you go to a video (or any other page where the guide is available). 

I still don't get it. What is it? What feature/function does it provide?
Thank you.

**Comment by ErdeFB** [comment]
Guide is the interface that appears on the leftmost side of the screen when you click on the three horizontal lines next to the YouTube logo at top left corner.

**Comment by ReporterX** [comment]
@ErdeFB Thanks for the reply. Well is it this icon that you are talking about?

![YouTube thumbnail](http://snag.gy/SA7qA.jpg)

But I don't get what those options are for. For example, it does not seem to have any effect when I set it to "always open/closed". It might be bugged. :-/

**Comment by ErdeFB** [comment]
Yes, that is exactly what I meant. And indeed, "always open" is bugged. Has been since the last major overhaul of YouTube UI. I think I even reported it. No fix yet. But even if it wasn't bugged, it would cover part of the player (at least with my settings. would think that even for others).
