### ISSUE TITLE
[Build 461] Completely broken since several days?

### ISSUE THREAD

**Issue by madock314** [YePpHa/YouTubeCenter#1375]
Hi,
YouTubeCenter seems to be broken since several days.
YouTube gets caught in a reload loop if the YouTubeCenter script is enabled. Also the layout seems to be broken.

Firefox 35, Greasemonkey 2.3, YouTubeCenter.js Build 461

**Comment by Cnuut** [comment]
Works fine for me.
FF 35, GM 2.3, YTC Dev 461, win 8.1

**Comment by andyb2** [comment]
Works mostly for me in chrome.Just a few times the annotation block doesnt work and some recommended video banner from the channel owner always sliding into the video from the left side.

**Comment by madock314** [comment]
I was an incompatibility with one of my addons: YouTube Unblocker
YouTubeCenter and YouTube Unblocker work fine on it's one, but together it causes reload loops.

I will close that issue for now. If the author thinks it's worth investigating, he can reopen.
