### ISSUE TITLE
Prevent auto-play with HTML5 not working

### ISSUE THREAD

**Issue by Justtaway** [YePpHa/YouTubeCenter#1376]
But working fine with Flash.
Chrome 39.0.2171.99.

**Comment by Eisys** [comment]
Always say what version of YTC you are using when reporting something!

**Comment by Justtaway** [comment]
v2.1.4, sorry.

**Comment by ErdeFB** [comment]
The latest stable version is 2.1.7. Don't get the one in the Mozilla add-ons page as that is a old version.
If 2.1.7 fails, try the latest developer version.

**Comment by Justtaway** [comment]
2.1.7 works for me, but now I have another broken thing: aligning to center not working, if dark player background enabled or if lights off enabled.

**Comment by Eisys** [comment]
Yeah that is a new bug even with the latest DEV version. YT probably changed something! Just gotta live with it for now!

**Comment by Justtaway** [comment]
Yeah, just disabled both of those and it's fine x)
