### ISSUE TITLE
HTML5 playback colors worse than Flash

### ISSUE THREAD

**Issue by CathalCraft** [YePpHa/YouTubeCenter#1379]
I know this isn't necessarily an issue with YoutubeCenter, but I have no idea where else to post this. In the image below, Firefox on the left is using Flash and Chrome on the right is using HTML5. As you can see, the colors are washed out on Chrome using HTML5. I then set Firefox to use HTML5 to rule out browser differences, and the colors looked the same on both browsers, leading me to believe that HTML5 has washed out colors compared to Flash.

![ss 2015-01-16 at 09 02 09](https://cloud.githubusercontent.com/assets/3347837/5787236/36e2f714-9dc5-11e4-9f4f-387523d4aed3.jpg)

Is there a way to fix this or pass this information to someone to get it fixed?  Or will HTML forever have worse colors compared to Flash? I want to use HTML5 for 60FPS playback, but I hate washed out colors.

**Comment by Seiryuu-sama** [comment]
I think I heard that this could be fixed by making sure the video is displayed with the full RGB color range. How you do that depends on what graphic card provider you have,

**Comment by CathalCraft** [comment]
I'm using a NVIDIA 970.

**Comment by Seiryuu-sama** [comment]
[Try this] (http://www.reddit.com/r/youtube/comments/2jb8to/why_are_video_colors_different_when_displaying/claenyt)

**Comment by CathalCraft** [comment]
Thanks! That worked.

**Comment by ErdeFB** [comment]
Glad to see your issue is resolved. Please click the "close issue" -button at your earliest convenience.
