### ISSUE TITLE
open video without playlist.

### ISSUE THREAD

**Issue by kuratowakiru** [YePpHa/YouTubeCenter#1383]
Since the freeze auto playlist broken again and again due to YT keep changing things. Can we have an option for opening a video from a playlist without the playlist embedded next to it?

**Comment by Yonezpt** [comment]
Until YePpHa manages to find some free time, you can use my <b>userscript</b> patch which can be found here: http://openuserjs.org/scripts/ParticleCore/Playlist_Autoplay_Control_for_YouTube

**Comment by Eisys** [comment]
Hey @Yonezpt You seem to know your way around scripting and stuff.. Do you reckon you could jimmy up a script that hides the header when watching videos?
Like this extension does it:
http://improvedtube.com/
I would use the addon itself but it's quite buggy alongside YTC.
If you can't or don't want to then it's completely fine. I made a request about this here as well but it hasn't been added yet and I could really use it!

**Comment by Yonezpt** [comment]
@Eisys Can you link me your thread request or make a new one and link me there if you haven't already? I will try to code something and post the script there once I get home. This way it will be easier for YePpHa to use the code from a dedicated thread if he wants to.

**Comment by Eisys** [comment]
Here ya go! ;)
https://github.com/YePpHa/YouTubeCenter/issues/786
