### ISSUE TITLE
Feature Request: Reduce Link Size on Search Results without Disabling Flex Width on Page

### ISSUE THREAD

**Issue by HaikenEdge** [YePpHa/YouTubeCenter#1385]
Currently, each search result extends all the way to the right edge of the page, even when it looks ostensibly white and clear; this is problematic in a two-monitor setup when the user clicks into the Youtube search page, and is immediately sent to a search result even if the intent was simply to shift focus to the browser.

**Comment by Eisys** [comment]
For me, there is alot of free space to the left and right of the search results, with Flex Width to Page enabled. I can see this being a problem if the browser size is smaller though!

**Comment by Shinshikaizer** [comment]
My problem isn't that there's space; I like the space. My problem is that the links extends all the way to the end, which includes a lot of blank white space. 

I'ved attached an screen capture to illustrate what i mean: 

![yt](https://cloud.githubusercontent.com/assets/9447962/5795191/9d1b2388-9f3e-11e4-9fc6-73697b8a807f.jpg)

The area highlighted with red is blank white space, but the links into the videos extend into that area; when I'm switching between monitors, I often end up clicking in that white space, thinking it's empty, and instead end up redirected to a link I didn't intend on clicking.

**Comment by Eisys** [comment]
Oh... That doesn't happen for me.. The links have their little box area for me...
http://prntscr.com/5udsv2
The links don't extend into the darker area for me! Just empty space!

**Comment by HaikenEdge** [comment]
I get the same result as your picture if I turn off Flex width on page and close the sidebar, but I like having flex width on, and the sidebar open.
