### ISSUE TITLE
Dev Build 463 Broken

### ISSUE THREAD

**Issue by Aphoristic** [YePpHa/YouTubeCenter#1386]
Works fine on my subs page, but it breaks when I click on a video. No cog at the top, resizing broken, all buttons missing.  Thumbnail stuff still loaded on related videos for some reason.

Browser: Opera 15+

**Comment by YePpHa** [comment]
@Aphoristic could you please try to open your developer console and see if some kind of error were reported. You can open it by pressing `CTRL` + `SHIFT` + `J`.

**Comment by Cnuut** [comment]
yeah not looking good in FF either

**Comment by YePpHa** [comment]
I think I might have an idea what could be wrong.

**Comment by Cnuut** [comment]
"TypeError: elm is null"

**Comment by gitmonger** [comment]
Broken in Firefox 17.0.11

**Comment by YePpHa** [comment]
__THIS WILL BE BROKEN ON EVERY VIDEO EXCEPT PLAYLISTS__

**Comment by KDsMax** [comment]
Still broken?

![image](https://cloud.githubusercontent.com/assets/10601224/5804348/e44dd47e-a00d-11e4-8063-646cd1f2559c.png)

**Comment by Cnuut** [comment]
465 is out as I type this
https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by KDsMax** [comment]
Running Dev version 466, still have this same issue.

**Comment by YePpHa** [comment]
Those who have an issue where YouTube Center doesn't work, please dump your developer console (CTRL + SHIFT + J/K).

**Comment by KDsMax** [comment]
I cleared console log, didn't help. Or what console you mean?

**Comment by Zerathos** [comment]
Not dump as in get rid of, dump as in paste here.

**Comment by gitmonger** [comment]
464 looks fine so far.
I'll leave well enough alone and stop auto-updates, unless a major issue arises.

**Comment by KDsMax** [comment]
My developer console was empty, nothing to dump.

**Comment by YePpHa** [comment]
It seems like there still was an issue where the button to access the YouTube Center settings wouldn't appear if you're weren't on a video and that's due to the api function getPlayerState weren't available. I will release a new dev version in just a moment and should fix this.

**Comment by YePpHa** [comment]
If the dev version 467 is broken then create a new issue with a reference to this issue.
