### ISSUE TITLE
Build 477 broken

### ISSUE THREAD

**Issue by KDsMax** [YePpHa/YouTubeCenter#1389]
Reference: #1386 

![image](https://cloud.githubusercontent.com/assets/10601224/5804900/ae6c1f14-a012-11e4-8375-59ea31b02e96.png)

**Comment by YePpHa** [comment]
@KDsMax could you please post the content of your developer console. You can access it by pressing F12 or CTRL + SHIFT + J.

**Comment by KDsMax** [comment]
Not sure if this is the right one: http://pastebin.com/yh2Svnd3

**Comment by YePpHa** [comment]
I wonder if it has something to do with you running Chrome Canary? I will try to test it.

**Comment by YePpHa** [comment]
I can't see anything wrong in your developer console.

**Comment by KDsMax** [comment]
My Canary build is 42.0.2280.2 (64-bit)

**Comment by YePpHa** [comment]
I have the same build. However, there is no issue on my end. I'm wondering if it could have something to do with your YouTube Center settings.

**Comment by KDsMax** [comment]
Found the issue, when I disabled "Enable row width limit" all is working correctly.

**Comment by YePpHa** [comment]
Okay, thanks. I will try to debug it.

**Comment by YePpHa** [comment]
It seems like you set the row width to be about 100px. It's recommended to set it to about 700px.

**Comment by KDsMax** [comment]
Yeah, that was the issue.

**Comment by KDsMax** [comment]
What this feature actually does? First I thought that it would reduce the height of the video search page. So there would not be so many videos at the same page.

**Comment by YePpHa** [comment]
Ahh, no. It's related to this issue #1385.

**Comment by YePpHa** [comment]
I will set the minimum width to 700px to make sure this doesn't happen again by accident.

**Comment by KDsMax** [comment]
Aahh, good to know lol.
