### ISSUE TITLE
Developer Version - Build #467 Blank space around the player

### ISSUE THREAD

**Issue by kilara1988** [YePpHa/YouTubeCenter#1391]
With the mentioned build there is blank space on the right and between the player and the video description.
![untitled](https://cloud.githubusercontent.com/assets/1025376/5805192/666d5ca2-a015-11e4-8e7b-a9556b069c54.png)

**Comment by YePpHa** [comment]
Could you provide a screenshot of this?

**Comment by kilara1988** [comment]
Sorry forgot to include it.Included in first post now.

**Comment by YePpHa** [comment]
Okay, thx.

**Comment by YePpHa** [comment]
It's weird that the empty element is not hidden. Are you using Firefox?

**Comment by kilara1988** [comment]
Yes.Stable Version.

**Comment by fable2** [comment]
Same here Build #467, on firefox

**Comment by YePpHa** [comment]
I found the issue. I will be uploading an update in just a moment.

**Comment by CitrusAlex** [comment]
Same thing

**Comment by Yonezpt** [comment]
@YePpHa The dock-offset somehow boxed outside the player? Looks like setting `#player-api` position to absolute fixes the problem.

**Comment by YePpHa** [comment]
I accidentally set the dock-offset id as a classname instead. This caused the css styles to not apply and that's what caused the issue.
