### ISSUE TITLE
Large blank space under videos on Build #467

### ISSUE THREAD

**Issue by jamerst** [YePpHa/YouTubeCenter#1392]
With build 467, there is a large blank space underneath the video, not sure if it is something in my settings that has been broken.
![untitled-1](https://cloud.githubusercontent.com/assets/10601770/5805123/29e6b55a-a004-11e4-9db7-b9405da167cb.png)
Video is just above the top of this screenshot - my resolution isn't large enough to display both the video and the gap.

**Comment by jamerst** [comment]
Duplicate issue.

**Comment by YePpHa** [comment]
Related #1391.
