### ISSUE TITLE
So about the header!

### ISSUE THREAD

**Issue by Eisys** [YePpHa/YouTubeCenter#1393]
So I'm gonna make a new issue about this!
Continuing this: https://github.com/YePpHa/YouTubeCenter/issues/786

I'm glad it got implemented, Thanks @YePpHa and @Yonezpt !!

But it has some problems for me:
With it enabled, the header does go away but the video doesnt scroll up:
http://prntscr.com/5uhldh
Having the transition enabled or disabled makes no difference.
Sometimes the page tries to scroll down to the video but then pops back up.

On the other hand, @Yonezpt , your script works perfectly now alongside the latest dev build!

Edit: Also, a feature request, perhaps add a simple way to change the time it takes for the header to come and go.

**Comment by KDsMax** [comment]
I confirm this behaviour.

**Comment by YePpHa** [comment]
@Eisys Please, could you post what browser and what version of said browser you're using.

**Comment by Yonezpt** [comment]
@YePpHa According to his recent comment in the other thread, he is using Chrome Version 40.0.2214.85 beta-m (64-bit) https://github.com/YePpHa/YouTubeCenter/issues/786#issuecomment-70503157

**Comment by YePpHa** [comment]
@Yonezpt thx.

**Comment by KDsMax** [comment]
I have a suggestion regarding the header hiding, add a feature to show header via scrolling the mouse wheel up. So we don't have to pause the video to get the header visible.

**Comment by YePpHa** [comment]
@KDsMax that will make the feature a lot more complicated, but it will be durable.

**Comment by Eisys** [comment]
I am all for it if it's an option.. I scroll through the page alot when watching videos so this would be kind of annoying for me! But it would be a great feature!

**Comment by Yonezpt** [comment]
Perhaps the best option would be to show it based on the mouse location, a certain top distance treshold which would show the header, stay visible when the element is active, hide again when the mouse moves downwards and away from the header. I'll try to mock up a concept example, I'm curious to see wether this will impact browser performance or not.

**Comment by Eisys** [comment]
@Yonezpt That is definitely possible, the addon I was talking about in the other thread worked just like that! And I didn't see any performance issues but then again I have a decent PC!

**Comment by KDsMax** [comment]
I agree @Yonezpt

**Comment by Yonezpt** [comment]
@Eisys You already know how it is, here is the userscript: https://gist.github.com/Yonezpt/cf655fe7f9751877fb3d

Move mouse to the top and the header should appear, move downwards and it will hide. Also this time the notifications window should show up, unlike with the other script.
Same preferences apply, if you want a faster transition simply decrease the seconds. If you put it at 0s then it should appear and disappear instantly.

**Comment by Yonezpt** [comment]
Made a quick update because I forgot to account for when a user is using the header and navigating away from a video page.

**Comment by Eisys** [comment]
Oh wow. That is amazing @Yonezpt !

This works really well and I think this fits my needs better than it appearing when the video is paused, since it got a bit annoying that the video moves up and down all the time when pausing!
I think @YePpHa should implement this as a 3rd option so people could have the variety!

Again, thank you so much for making this as I can now fully enjoy Youtube!

**Comment by Yonezpt** [comment]
Make sure you are using the version 6, there were some details I overlooked. Also clicked on assignees by mistake...

**Comment by Eisys** [comment]
Yep, I am indeed on ver 6, but reinstalled just in case! Works perfectly so far. The 0s works best for me as anything slower just seems unnecessary!

**Comment by KDsMax** [comment]
How you guys installed this script?

**Comment by Eisys** [comment]
I have the Tampermonkey addon for Chrome, that is used to install userscripts! Im guessing @Yonezpt  has it too!

Also. @Yonezpt I think there might be one last bug in your script, sometimes when going to a video the page scrolls down the height of the header and stays down like that, sometimes it flickers down and up really fast, sometimes a bit slower! I tried setting the speed higher and then it seems not to do it as much but there is still that flicker, but at 0s or 0.1s or so it stays down more often it seems!

**Comment by Yonezpt** [comment]
@Eisys In that case it is best to simply change the following lines:

````javascript
    var sheet =
        '#masthead-positioner,#masthead-positioner-height-offset{margin-top:0;transition:margin-top 1s}\n' +
        '#body #body-container .hide{margin-top:-50px}',
````

to  this:

````javascript
    var sheet = '#body #body-container .hide{display:none}',
````

Seeing that you prefer it without transition.

**Comment by Eisys** [comment]
Ok yep, that works perfectly, thanks!
Now to wait and hope that @YePpHa fixes the original issue and implements your new mouse-proximity version as well! I don't mind it being a seperate script but just having it all in one place would be better.

**Comment by KDsMax** [comment]
Or you could add a feature that header would reappear when video ends.
