### ISSUE TITLE
Prevent Auto play next video button shows undefined hint

### ISSUE THREAD

**Issue by F43nd1r** [YePpHa/YouTubeCenter#1395]
![unbenannt](https://cloud.githubusercontent.com/assets/10252708/5806078/bf607a24-a015-11e4-9e31-321cfd5f725e.PNG)

@YePpHa the bug still consist in dev build 470 

The Button does what it should, it just doesn't show the correct hint. 
(Additionally I would suggest to use a different icon)

**Comment by YePpHa** [comment]
I will give the button an alternative label to prevent it from saying undefined.

Also I'm not sure what I should change the icon to, but suggestions are welcome.

**Comment by Eisys** [comment]
Hmm, it says 'Autoplay' for me, im on latest dev build!
I think it should be a small play button icon, like the one in YT logo, and if it's disabled, it has a line across it!

**Comment by YePpHa** [comment]
@Eisys it does say `autoplay` for me too, but it might be that other people's YouTube is a little bit different.

As for the logo, that might not be that bad of an idea. Do you think it would be a bad idea to try adding the arrows as a circle around the play icon?

**Comment by Eisys** [comment]
@YePpHa Oo yes, that sounds even better! It would fit well!

**Comment by F43nd1r** [comment]
@YePpHa yeah sounds cool as icon. 
Additonal info: I'm using Firefox 35.0, other plugins are: adblock plus, hide caption titlebar plus, instantfox and master password+

Can anybody confirm this issue or is it just me?

**Comment by YePpHa** [comment]
I think the reason is that your YouTube is in a language other than English, but can be a completely different issue. However, it should not be hard to fix.

**Comment by F43nd1r** [comment]
@YePpHa correct, my youtube is in german.

**Comment by Yonezpt** [comment]
@YePpHa Just throwing my suggestion for the button as well; I used the HTML5 play icon for the playlist autoplay in my userscript, the screenshot shows how it looks:

![ss](https://cloud.githubusercontent.com/assets/8498057/5808158/f8ce287a-a019-11e4-8384-f4a645128e3c.png)

Also, if you are still seeing the autoplay tooltip by default then you either need to delete your cookies in order to load the new ones containing the responsible fexp value or they haven't yet expanded the experiment to your country.

**Comment by ReporterX** [comment]
I see "undefined" label too.
Inspecting the code:

```HTML
<button class="yt-uix-button yt-uix-button-size-default yt-uix-button-player-controls yt-uix-button-empty yt-uix-button-has-icon toggle-autoplay yt-uix-button-opacity yt-uix-tooltip yt-uix-tooltip yt-uix-button-toggled" type="button" onclick=";return false;" title="undefined" data-button-toggle="false" data-tooltip-text="undefined" aria-pressed="true">
```

Language: English
Country: UK

I would suggest this as Autoplay icon.
![Autoplay icon](http://snag.gy/aaXaS.jpg)

**Comment by Yonezpt** [comment]
@ReporterX I don't think there is one

@YePpHa Disable `Prevent playlist auto-play` and check the tooltip of that button, does it read `undefined`as well?

**Comment by kliop00023** [comment]
i think it is caused by SPF

**Comment by F43nd1r** [comment]
Fixed for me in build 477.
