### ISSUE TITLE
will not refresh automatically

### ISSUE THREAD

**Issue by kliop00023** [YePpHa/YouTubeCenter#1401]
browser:maxthon 4.4.3.3000
YouTube Center Developer Build v473 using Violentmonkey

does not refresh automatically:
when i press save and reload or reload bottoms in this 2 sub-windows:
1.import/export settings
2.reset settings,(it does not work either)
the page will not refresh automatically and the settings cannot save

playlist functions:
(see #1395)

do you have the same problem?

**Comment by kliop00023** [comment]
ref. also #1400

**Comment by kliop00023** [comment]
playlist's problem should be related to some of my changes in setting but i do not know which one...

**Comment by kliop00023** [comment]
updated @YePpHa

**Comment by YePpHa** [comment]
Seems to be a Maxthon bug; possibly a bug related to Violentmonkey. I would recommend you to try [the native extension](https://github.com/YePpHa/YouTubeCenter/raw/master/dist/YouTubeCenter.mxaddon) for Maxthon and installing YouTube Center through Violentmonkey as I do not officially support Violentmonkey.

**Comment by kliop00023** [comment]
fixed in v474
