### ISSUE TITLE
Center Player horizontal

### ISSUE THREAD

**Issue by noxxim** [YePpHa/YouTubeCenter#1407]
Hi.

I set to 720p with autoresolution and the player size is "fit to content". So after loading the page and the video starts, the player scale up to 720, but after that the player isn't in the center of the screen (like on the screenshot below). 

Can you set the css to center the player after resizing?

http://www.xup.in/dl,16063814/Bildschirmfoto_vom_2015-01-25_14:52:09.png

**Comment by Yonezpt** [comment]
Could you take a screenshot of the "Fit to content" settings you have? Capture it like this:

![screen shot 2015-01-25 at 13 39 42](https://cloud.githubusercontent.com/assets/8498057/5891825/c8c69554-a497-11e4-8bc0-87259a4861ce.png)

Also the current YTC version you are using and browser as well are always helpful information.

**Comment by grantlee77** [comment]
I'm having the same issue : 
<a href="http://imgur.com/9xfZL6Q"><img src="http://i.imgur.com/9xfZL6Qs.png" title="source: imgur.com" /></a>
Here are my settings : 
<a href="http://imgur.com/584NxEB"><img src="http://i.imgur.com/584NxEBs.png" title="source: imgur.com" /></a>

I'm using Firefox 35.0 and YTC 2.1.7 (which I got from here, since Firefox add-on page is stuck to 2.1.0).

**Comment by Tiuqu** [comment]
UI -> Dark player background, uncheck, problem fixed...

I hope there will be new stable release soon, that will fix all the bugs (also official firefox addon page still has 2.1.0 instead of 2.1.7)

**Comment by grantlee77** [comment]
Thanks for the fix !

**Comment by Yonezpt** [comment]
@grantlee77 The settings you showed are not the settings of the "Fit to content" option, you showed the settings for the "80%" which is not what you described in your original post.

Regardless, I have tested the same settings your screenshot shows and the player displays correctly with the <b>dev build</b> 470 with no need to remove the dark player background.

You can download the latest developer build here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

@Tiuqu read https://github.com/YePpHa/YouTubeCenter/issues/1325#issuecomment-68047353

**Comment by grantlee77** [comment]
I am not the original poster. I thought my problem was similar to him. 
Apparently it is not, my apologies for putting a bit of misunderstanding here.
Thank you for taking time to answer me.

**Comment by Yonezpt** [comment]
Apologies, I thought you were the original poster. But still, the suggestion remains valid for anyone with this problem, try the developer version because I suspect this problem has been fixed already.

**Comment by F43nd1r** [comment]
I have a similar Issue: When I enable Player size: enable Resize everything works fine, but when I disable it, the Player is too far on the right.
