### ISSUE TITLE
Reset settings not working

### ISSUE THREAD

**Issue by Yonezpt** [YePpHa/YouTubeCenter#1408]
Browsers tested:

Chrome 40.0.2214.91
Firefox 35.0

YTC dev 470

When clicking on the Reset button in the "Reset settings" dialog it gets stuck on trying to reset the settings.

In Chrome's console it displays the following:

````
[Storage] Checking if settings have expired.
[Tab Events] Sending new settings to other open tabs.
````

Firefox console:
````
"[Storage] Checking if settings have expired."
````

No matter how long I wait, nothing else happens. I have to refresh the page and the settings remain unchanged.

**Comment by alpe12** [comment]
Same here when trying to import settings.

**Comment by mleyen** [comment]
Confirmed on Cyberfox 35.0.1 with YTC build 471.

After a bit of testing, I realized that the settings will not save if the value of the "lastUpdated" property is less than the current value. I guess this is done to prevent YTC from accidentally overwriting the settings with invalid ones – the "settings randomly reset" has indeed not happened to me for a while now – but this also prevents importing older settings (resp. resetting all settings manually), as it would overwrite the "lastUpdated" value with a lower one (resp. clear it).

If you need to import settings, you'll have to edit "lastUpdated" manually (replacing the last few digits with "99999" will do the trick) before you save. That value will be at the very end of the input box.

**Comment by Sophira** [comment]
Thanks, mleyen - I was pointed here from #1400 and was coming to that conclusion myself after fiddling about with the saved files.

My exported settings were from a version old enough to not have a lastUpdated property, but adding one and giving it a high value (`"lastUpdated":1422762999999`) was enough to allow YTC to load them.

**Comment by greatwroth** [comment]
Same here, this is a big problem as I have an issue with audio/video de-syncing in html5 player but I can't troubleshoot it without resetting the settings.

**Comment by YePpHa** [comment]
Seems like I didn't account for this when I applied the `lastUpdated` update. I will try to get a fix out in the coming future.
