### ISSUE TITLE
Extension copy-cat on the Chrome webstore

### ISSUE THREAD

**Issue by Yonezpt** [YePpHa/YouTubeCenter#1412]
YouTube Center copy

https://chrome.google.com/webstore/detail/youtube-center/iiofijpibleaenofalhiehchdcfdnmon

The same user has also published a copy of SPOI

https://chrome.google.com/webstore/detail/youtube-options-spoi-opti/kkenbbbdbbmddgiielijkooilljhopol

Didn't even tested the extensions, I suspect they are filled with data-mining methods.

Thought you should be aware of this.

**Comment by ErdeFB** [comment]
Too bad we can't DMCA that stuff since we don't have a permission to do so. Oh well. I'm guessing this is in fact a copy software. @YePpHa, might want to check this out.

**Comment by Eisys** [comment]
Oh man this sucks..
I was going to review it and tell people not to use it but one has to add it Chrome first.. Yeah, not gonna do that!
I hope something can be done about this.

**Comment by YePpHa** [comment]
It seems like the only thing the extension does is adding this popup box (checked the code):
![ss 2015-01-29 at 04 12 34](https://cloud.githubusercontent.com/assets/2348303/5959845/afc6483c-a7d1-11e4-884a-adb28cceaf6f.png)

The two links that you can see in the popup box is http://addoncrop.com/youtube_center/ and http://addoncrop.com/how-to-install-chrome-extensions-in-developer-mode/.

They will then have you download their extension which does multiple things. The first is to add a bookmark that redirects to `http://addoncrop.com/`. It will then inject an additional script with the URL: http://www.sourcecrab.com/YouTube_Center_Extend/Back_extend.js. However, I haven't been able to read the code and I'm not sure what it does. The first time you install the extension they will also open two tabs: http://www.youtube.com/#ytcenter.settings.open and http://addoncrop.com/youtube-center-installed-successfully. However they also add Google analytic tracking to the page.
After this it will then inject YouTube Center v2.1.7 and it seems to be the original version.

This is mostly what I got from this and also YouTube Center is under the [MIT license](https://github.com/YePpHa/YouTubeCenter/blob/master/LICENSE.md). So they are allowed to do it. The most sensible thing to do is to encourage users to not use it.

**Comment by Yonezpt** [comment]
Can't read the injected the two injected files either. It's possible that they are custom pings that act like google's analytic pixel, but so far none of it looks good despite the fact that he seems to provide the official script version. Maybe he really is genuinely trying to help others getting your software, but he should at least have told you something. Not having done so raised the first red flag.

I am aware of the license, just thought you should be aware because it is basically your software image. Your review should be enough to prevent any ill consequences backfiring at you in case the software contains malicious code.

**Comment by Pontiac76** [comment]
Just reading over the image gives me pause to begin with, simply because of
the typos, bad "gramatics", and the fact that it is in the store, yet,
we're told it isn't in the store anymore.  If Chrome Store were to drop it
due to policy infractions and abuse, you'd figure you'd never SEE it to
begin with.

Either way, I don't use Chrome, and download my updates directly from the
github site when I'm informed of an update.

**Comment by Yonezpt** [comment]
Looks like his account has been suspended.

**Comment by christopheranderton** [comment]
Sorry for bumping/hijacking this closed thread. But when looking around if the ”developer” of the extensions at addoncrop was trustworthy, the only relevant result was this thread. 

Later today, the following comment was posted to a video on the ”developer's” Youtube channel (screen shot):
![screenshot 2015-07-24 at 11 25 37](https://cloud.githubusercontent.com/assets/1305802/8871737/dac23144-31f7-11e5-98ff-d38a98f8a70f.png)

The poster in question says that the extensions on the mentioned site do and tries to do sneaky stuff without user knowledge. Also, the ”developer” don't quite get the concept of Open Source. 

Posting this if any one comes from Google and looking for addoncrop extensions, and in this case looking for the the original YouTubeCenter extension.

Keep up the good work btw! 

@YePpHa ->
*Man borde släppa Ernst-Hugo Järegårds spøgelse på denna ”utvecklare” (minus Ernst Hugos synpunkter om Danmark då ;)*
