### ISSUE TITLE
Video resize doesn't function properly (Chrome script)

### ISSUE THREAD

**Issue by DShippam** [YePpHa/YouTubeCenter#1415]
When I try to resize the video that I'm trying to watch, the player will increase or decrease in size but the actual video will not which results in the video taking up space in a large black box. Is there anything I can do to fix this?

**Comment by ErdeFB** [comment]
What version of YTC are you running and what browser?

**Comment by Yonezpt** [comment]
@ErdeFB He is most likely using an outdated version and experiencing the issue https://github.com/YePpHa/YouTubeCenter/issues/1017

@DShippam You can install the latest stable version 2.1.7 if you haven't already, which can be found here: https://github.com/YePpHa/YouTubeCenter/wiki

If you find problems then try the developer version which can be found here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by ErdeFB** [comment]
@Yonezpt I figured as much myself, but since he wasn't considerate enough to tell us the basic minimum information to help solve their issue, I didn't feel considerate enough to write out a longer reply. ;)

**Comment by DShippam** [comment]
@ErdeFB I apologize. Yes, I am using version 2.1.7 and I'm using Chrome. I've tried re-installing the script twice but that hasn't done anything to fix the issue.

**Comment by Yonezpt** [comment]
@DShippam In that case try the developer version like I suggested and linked in my previous reply.

**Comment by sanitysama** [comment]
i have this problem as well but only with the html5 player. youtube now uses the html5 player by default, which has historically had alignment and resizing problems in this script. you should switch it back to the flash player and see if that fixes it. it works for me. settings > player > player type > change 'default' to 'flash'

**Comment by Yonezpt** [comment]
@sanitysama The html5 player resizing problem #1017 has been fixed already and continues working as of the latest developer version of YTC, 471

**Comment by ireun** [comment]
Main thread for this is now: #1844.
