### ISSUE TITLE
Restoring default settings freezes page

### ISSUE THREAD

**Issue by rafaeldamasceno** [YePpHa/YouTubeCenter#1419]
Title. Plus, settings do not get restored.

YTC471, Chrome 42.0.2288.6 dev-m (64-bit), using Chrome .crx

**Comment by F43nd1r** [comment]
Confirm same issue in friefox.

**Comment by Sigi-cz** [comment]
i was going to report that too. Using extracted crx in chrome.

**Comment by YePpHa** [comment]
I'm not able to recreate this issue at all in 475. If you open the developer console and try to restore the default settings, do anything appear in the developer console while the page is frozen?

**Comment by rafaeldamasceno** [comment]
Hey, this is a duplicate from #1408. I searched for restore settings and it didn't come up with anything, so I reported it. Sorry, I'm closing the bug for you :+1:

**Comment by YePpHa** [comment]
No problem.
