### ISSUE TITLE
Youtube Dropdown broken beyond homepage

### ISSUE THREAD

**Issue by tomtom9749** [YePpHa/YouTubeCenter#1423]
When on youtube hompage and i click the dropdown in the top left i get this: Normaly

![yt home](https://cloud.githubusercontent.com/assets/9009764/5991136/83c0dcd8-a9a8-11e4-8fe6-447160244a5f.PNG)

If i navigate anywhere else and try to use the dropdown all i see is this.

![yt other expand](https://cloud.githubusercontent.com/assets/9009764/5991137/83c2afc2-a9a8-11e4-9ef3-413b635ba096.PNG)

It just expands to empty space happened after latest dev update

Chrome              40.0.2214.93
Tampermonkey  3.9.202
YTCenter Dev    471

**Comment by mleyen** [comment]
Try [clearing your cookies](https://support.google.com/chrome/answer/95647?hl=en-GB) (at least the ones from youtube.com).

I had the same problem, even with YTC disabled. I noticed it didn't happen in incognito mode, so I cleared my YouTube cookies and the menu reappeared.

**Comment by tomtom9749** [comment]
That fixed it thanks!. I wasnt seeing it when i had ytc disabled but for whatever reason that cleared it up thanks.
