### ISSUE TITLE
suggestion about download option.

### ISSUE THREAD

**Issue by starobots** [YePpHa/YouTubeCenter#1424]
I know youtube has changed their rules. They use separate files for video and audio ,so 480p and 1080p are no longer available downloaded from it. Could you add these none-audio files and audio only files into download option or download button? Or give a choice to show the download link in somewhere, that I can merge these files in some easy software by myself.
Thank you for your great work. I can use this to set my youtube use Flash and disable dashplayback only install one extension,It's very useful for me.

**Comment by YePpHa** [comment]
I do plan on doing this at some point, but I would rather do this when I revamp the download system.

**Comment by starobots** [comment]
Thank for your reply.
There is a little issue, when I download the video, it could not catch the file's name in right way.
It shows videoplayback instead of theirs.
Thanks again.
\O/
