### ISSUE TITLE
Youtube doesn't provide 1080p+ resolutions in html5 anymore for unpopular videos

### ISSUE THREAD

**Issue by mzso** [YePpHa/YouTubeCenter#1429]
Hello!

Apparently youtube hidden the 1080p+ resolutions from the HTML5 player. It only seems to affect videos with few views. It happens on FF IE and Chrome. With flash all resolutions are there.
Can this be worked around?

Examples:
https://www.youtube.com/watch?v=kmCublPK42c

https://www.youtube.com/watch?v=hicBgE6XndM
(Both should have 1920*1200 aka "1440p")

**Comment by waltervrossem** [comment]
It is most likely that youtube hasn't finished rendering those video formats for the video yet, 1440p is available now in your 2nd link.

**Comment by mzso** [comment]
@waltervrossem commented on [2015. febr. 5. 20:06 CET](https://github.com/YePpHa/YouTubeCenter/issues/1429#issuecomment-73106138 "2015-02-05T19:06:58Z - Replied by Github Comment Enhancer"):
> It is most likely that youtube hasn't finished rendering those video formats for the video yet, 1440p is available now in your 2nd link.

It's surely not that. They're not new videos and had the streams before. Also the flash player still has them.
It's not available here.

**Comment by Kravyn** [comment]
I also posted about video format it seems youtube might have changed its format setup within the last few days and YTC does not work with the new changes so higher formats are missing or hidden. If you disable YTC you will see all formats are back. I just hope a new version comes out soon because I am unable to watch video's using youtubes crappy default setup.

**Comment by ErdeFB** [comment]
Can confirm that I'm also missing >=1080p on both latest Chromium and Firefox 38.

**Comment by mzso** [comment]
@Kravyn commented on [2015. febr. 5. 20:57 CET](https://github.com/YePpHa/YouTubeCenter/issues/1429#issuecomment-73115277 "2015-02-05T19:57:59Z - Replied by Github Comment Enhancer"):
> I also posted about video format it seems youtube might have changed its format setup within the last few days and YTC does not work with the new changes so higher formats are missing or hidden. If you disable YTC you will see all formats are back. I just hope a new version comes out soon because I am unable to watch video's using youtubes crappy default setup.

That's not it. I'm only missing 1080p+, and on all browsers. With or without YTC.

**Comment by ErdeFB** [comment]
Yes, happens without YTC. But not only in videos with small number of views. I just checked a video with over 150k views and it was missing anything over 720p on HTML5.

**Comment by Yonezpt** [comment]
I confirm the same issues without YTC. Since this is a YouTube problem and not YTC it would be best if this issue was posted on their support forums: https://productforums.google.com/forum/#!categories/youtube

**Comment by ErdeFB** [comment]
While I agree with @Yonezpt, this issue report also serves a purpose in which @YePpHa can see if this is something YTC can help with.

**Comment by mzso** [comment]
@Yonezpt commented on [2015. febr. 5. 22:08 CET](https://github.com/YePpHa/YouTubeCenter/issues/1429#issuecomment-73129037 "2015-02-05T21:08:58Z - Replied by Github Comment Enhancer"):
> I confirm the same issues without YTC. Since this is a YouTube problem and not YTC it would be best if this issue was posted on their support forums: [https://productforums.google.com/forum/#!categories/youtube](https://productforums.google.com/forum/#!categories/youtube)

I doubt it's by accident. Youtube does stuff like this whimsically.

**Comment by mzso** [comment]
Sadly it seems pretty permanent. None of the affected videos got back the missing resolution(s). "Thanks" google...

**Comment by YePpHa** [comment]
The first video: https://www.youtube.com/watch?v=kmCublPK42c, seems to use the 1080p quality when in reality it uses the 1920x1200 quality. If I change the resolution to 720p it selects the 1152x720 quality. So it seems like the HTML5 player has a bug where it skips the 1728x1080 quality.
![video1](https://cloud.githubusercontent.com/assets/2348303/6249376/1ebed97e-b787-11e4-812a-0547ea6b1c9c.png)

Moreover I looked at the available qualities for the video and these are the qualities available:
```
230x144
384x240
576x360
768x480
1152x720
1728x1080
1920x1200
```

**Comment by mzso** [comment]
Interesting. I don't think it did this when I posted the issue. I'm quite sure it played 1080p.
Also because of [another bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1095549) I would have noticed it.

Also the second video behaves differently. It starts to play 1080p and then changes to 1200p a few seconds later while still showing 1080p quality...

**Comment by YePpHa** [comment]
I'm thinking this is most likely a bug in the HTML5 player where both the 1920x1200 quality and the 1728x1080 quality are detected as 1080p. I will have to verify this by looking in the HTMl5 player code, but this is most likely the culprit.

**Comment by Gittyperson** [comment]
Since there's another YouTube script (with way less features that YTC) that successfully provides 1080p HTML5 playback (proving that it can be done), hopefully YTC can do it too and override yet another Google restriction.

**Comment by Yonezpt** [comment]
@Gittyperson The other YouTube scripts provide the ability to use a third party library - commonly used is the ffmpeg application: 

>[The latest FFmpeg version is needed for muxing DASH videos (480p/1080p) and audio](https://addons.mozilla.org/en-Us/firefox/addon/complete-youtube-saver/)

>[This script downloads the audio and video as separate streams, then uses FFMPEG to re-combine them into a single video file](https://gist.github.com/lelandbatey/11100493)

or converted in the server and then sent back to the user, such as http://www.clipconverter.cc/

What google did wasn't a restriction, they simply stopped providing non-DASH streams above 720p. YePpHa already looked into a way of doing it directly in the browser (see https://github.com/YePpHa/YouTubeCenter/issues/716), but the compromise is just too big to be worth the trouble. Users are better off just using an online service or similar alternative that already does the same job if they want higher qualities than the currently available ones.

**Comment by Gittyperson** [comment]
Thanks Yonezpt, I wasn't talking about a downloading script, but ViewTube's MPEG-DASH experimental feature which works directly in the browser.

**Comment by Yonezpt** [comment]
@Gittyperson That's the same one YePpHa discussed in the linked issue I provided.

**Comment by Gittyperson** [comment]
Oh I see, thanks. It seems to be done on the fly though, without using the 20+MB ffmpeg.exe. I could be wrong of course but the script's size is small and ffmpeg is not required. Maybe they use some other trickery to feed the DASH streams to the HTML5 player?

**Comment by Yonezpt** [comment]
@Gittyperson ViewTube doesn't use any muxing whatsoever, they provide the same files that YTC provides plus the individual video streams that contain no audio.

**Comment by Gittyperson** [comment]
Ok, but it does provide 1080p HTML5 online playback with audio that's why I mentioned it.

**Comment by Yonezpt** [comment]
@Gittyperson Ah, yes it is very possible, all you need is to play both files at the same time and maintain them in synch.

And now I see the confusion I am making, I thought you were talking about downloading the videos with qualities above 720p, not watching them in higher qualities. But according to the quick test by YePpHa the issue is limited to the labeling, because the quality is still the same even if the 1080p stream is incorrectly labeled as 720p.

**Comment by mzso** [comment]
None of what you're talking about are about this issue.
@Gittyperson
YTC provides 1080p playback it always did, this issue is about higher resolutions. You just need a recent browser version.
ViewTube could only play dash formats audio/video only the last time I checked.
There's no way for userscripts to handle dash formats simultaneously as far as I know. None have done it.

**Comment by mzso** [comment]
[**@Gittyperson**](https://github.com/Gittyperson) commented on [2015. máj. 10. 15:32 CEST](https://github.com/YePpHa/YouTubeCenter/issues/1429#issuecomment-100642560 "2015-05-10T13:32:27Z - Replied by Github Comment Enhancer"):
> Ok, but it does provide 1080p HTML5 online playback with audio that's why I mentioned it.

So does YTC with a recent browser version.
On the other hand you can't change the volume when using viewtube.

With this video it can't play 1920*1200: https://www.youtube.com/watch?v=hicBgE6XndM

**Comment by Yonezpt** [comment]
@mzso Check again, it is playing in that resolution:

![ss](https://cloud.githubusercontent.com/assets/8498057/7554864/6572bcec-f728-11e4-817e-2ea3c7b48995.png)


The 1080p label doesn't mean that the video is literally playing with a 1920x1080 resolution, it means that it is playing at least with that resolution or higher, but below the next higher option if one is available.

1920x1200 is by no means 1440p resolution, it is below it and since there isn't any other quality label between 1080p and 1440p it defaults to the next lowest, not highest.

When the resolution is 1440p or above then that label will show up, for example: https://www.youtube.com/watch?v=mFQd9_rf69I

![ss](https://cloud.githubusercontent.com/assets/8498057/7554911/f48ae21a-f728-11e4-9ffd-7df82191ad0a.png)


So this means that this issue does not exist and can be closed, there is no problem anywhere, if anything YouTube corrected the quality labels which might have been sorted incorrectly before.

**Comment by Gittyperson** [comment]
A final comment: mzso's remark "you just need a recent browser version" is probably the key to why I cannot see 1080p with YTC. Using Pale Moon which is of course recent, but probably unsupported by YTC and that's where the problem lies. Maybe I'll open a new issue if it's possible to fix this. Thanks for the info.

**Comment by ErdeFB** [comment]
You should check youtube.com/html5 to see what formats your browser supports. Last I checked, Palemoon did not really support MSE.

**Comment by mzso** [comment]
[**@Gittyperson**](https://github.com/Gittyperson) commented on [2015. máj. 10. 18:58 CEST](https://github.com/YePpHa/YouTubeCenter/issues/1429#issuecomment-100668441 "2015-05-10T16:58:48Z - Replied by Github Comment Enhancer"):
>  Using Pale Moon (MSE format not implemented yet due to instability, not sure if this applies here) which is of course recent, but probably unsupported by YTC and that's where the problem lies.

The problem lies in the fact that Pale Moon is practically a somewhat tuned outdated firefox.
I've been using it until they stopped building it to the newest FF codebase.

**Comment by mzso** [comment]
[**@Yonezpt**](https://github.com/Yonezpt) commented on [2015. máj. 10. 17:28 CEST](https://github.com/YePpHa/YouTubeCenter/issues/1429#issuecomment-100655772 "2015-05-10T15:28:52Z - Replied by Github Comment Enhancer"):
> [@mzso](https://github.com/mzso) Check again, it is playing in that resolution:
> 
>  
> The 1080p label doesn't mean that the video is literally playing with a 1920x1080 resolution, it means that it is playing at least with that resolution or higher, but below the next higher option if one is available.
> 
> 1920x1200 is by no means 1440p resolution, it is below it and since there isn't any other quality label between 1080p and 1440p it defaults to the next lowest, not highest.
> 
> When the resolution is 1440p or above then that label will show up, for example: [[HD 1440p] BATMAN V SUPERMAN Official Trailer (2016)](https://www.youtube.com/watch?v=mFQd9_rf69I)
> 
> 
> 
> So this means that this issue does not exist and can be closed, there is no problem anywhere, if anything YouTube corrected the quality labels which might have been sorted incorrectly before.

Ultimately I doubt you're right. It used to be that youtube always showed the quality that the resolution fits in. (And still does with Flash)  Since 1920*1200 is larger then 1080p it showed 1440p. Which makes sense. It means at most X resolution, but bigger than the resolution below this. The way it is now you can't select 1080p even if you want to.

Also let me quote myself:
[**@mzso**](https://github.com/mzso) commented on [2015. febr. 18. 16:13 CET](https://github.com/YePpHa/YouTubeCenter/issues/1429#issuecomment-74880069 "2015-02-18T15:13:48Z - Replied by Github Comment Enhancer"):
> Also the second video behaves differently. It starts to play 1080p and then changes to 1200p a few seconds later while still showing 1080p quality...
> 
> (PS: What's that button for you on the far right? I never saw that.)

It still happens as such. This can't be considered normal at all.

But I guess the only way YTC could work around this is by replacing youtube's HTML5 player with it's own, which I doubt will happen.

**Comment by Gittyperson** [comment]
@ErdeFB yes, I mentioned that MSE is not supported by choice details on this [here] (http://forum.palemoon.org/viewtopic.php?f=3&t=6368) but as per ViewTube, it can be done without MSE.

  @mzso The 'outdated Firefox' label is misleading at best, please read [this] (https://forum.palemoon.org/viewtopic.php?f=4&t=7818). If we really have to compare it to Firefox it's a 'more stable, non-Australis Firefox' but they really are significantly different browsers today.

**Comment by mzso** [comment]
That's just propaganda. They added very little.
The significant differences lie in the fact of the pretty old codebase. (ff24)
The don't have the man power for larger features. For example unless they pull MSE from mozilla you'll never support for it in PM.

**Comment by Gittyperson** [comment]
This is way off-topic (sorry about that) but please stop posting inaccuracies. The fact is that MSE [is not even properly supported by Firefox](http://en.wikipedia.org/wiki/Media_Source_Extensions#cite_note-4), and Pale Moon's decision to not implement it at the moment is fully explained in my previous link. The info is all there for anyone interested, no need to comment it here. Propaganda is the definition of posting inaccuracies.

**Comment by Yonezpt** [comment]
The flash player never had much to change when compared to the HTML5 player, it is very likely that it still uses an outdated quality labeling attribute. Regardless of the case, this is a YouTube problem, not YTC. Creating an HTML5 player from scratch to provide you what you want would be a monumental task and would introduce problems after problems, especially with the systematic changes YouTube has been introducing recently.

Like I said in my first reply in February in this issue, it would be best if your issue is posted in their forums: https://productforums.google.com/forum/#!categories/youtube

**Comment by mzso** [comment]
@Yonezpt 
Oh, well. Then it was a dumb decision on their part...

**Comment by Zarggg** [comment]
@mzso: As has been stated more than once, this is not the venue for that. This issue has already been closed by the developer of YTC that this is an issue with YouTube and cannot be fixed/changed by this script.

If you have further concerns, take them up with YouTube/Google directly.
