### ISSUE TITLE
Update 473, whole script broke... again.

### ISSUE THREAD

**Issue by emm980** [YePpHa/YouTubeCenter#1433]
Just updated to 473. Last time 463 did the same thing, YTC config button shows only in settings page, resizing doesn't work, autoplay doesn't work... and probably others don't work either. Sometimes it loads, other times it doesn't.

Debug log: https://gist.github.com/4d1c22703cddc4362240

For now I've downgraded to 471 (user.js).
Note: just now I found 472, apparently that's the update that broke 471.

**Comment by ErdeFB** [comment]
Just adding that the Chrome add-on at least works.

**Comment by emm980** [comment]
On a 2nd note, 471 does the same... now, but it didn't before.

**Comment by seagull** [comment]
Good call @emm980 , thank you for that. There is indeed a conflict.
Perhaps YePpHa could integrate the plug-in's functionality into his own extension? (because that's a five-minute operation, right?! It's just ones and zeroes! /s)

**Comment by emm980** [comment]
I've moved the code from that ext to Tampermonkey and executing it first then YTC.

Now I have the following issue: the player location is blank.

In console YTC gives this:

YouTubeCenter.js:23131 Uncaught TypeError: Cannot read property 'replace' of null
<pre>if (ytcenter.html5 && !a.canPlayType(streams[i].type.split(";")[0]).replace(/no/, '')) continue; // Browser doesn't support this format</pre>

YouTubeCenter.js:12423 Uncaught TypeError: Cannot read property 'className' of null
<pre>ytcenter.utils.addClass = function(elm, className){
if (typeof elm === "undefined" || typeof elm.className === "undefined") return;</pre>

I can only think that first error is due to the other script stopping HTML5 player which does alter canPlayType:
<pre>document.createElement("video").constructor.prototype.canPlayType = function(type) { return null; }</pre>

**Comment by emm980** [comment]
If the stopping script returns an empty string (as per chromium source code specs), then YTC behaves as it did when I first started the thread. The player gets resized, "autostop" fails, background players keep playing concomitantly and there's no YTC config button.

The only difference is that in console YTC's only error is:
YouTubeCenter.js:12423 Uncaught TypeError: Cannot read property 'className' of null

But then there popped up this error:
youtube's html5player.js:1623 Uncaught TypeError: Cannot read property 'getPlayerType' of null
... which I believe is related but doesn't interfere.

If I change the order of the scripts in Tampermonkey, nothing changes.
The issue showed up after updating from I don't know what version to 473.
HTML5 stopping script did not update.

Something in between updates something changed... I'll keep browsing for older YTC to see if YTC is causing the issue or Chrome itself.

There might be a problem with using different Chrome builds, since YePpHa uses, I believe, a dev version, where as most people just use the latest stable version, including me. If Chrome changed something there, the stable catching up / having some html5player bug fixed, the issue was bound to happen.

**Comment by YePpHa** [comment]
Can anyone confirm if this is fixed in the newer developer version or if it's still present.

**Comment by emm980** [comment]
I've Tested 477, and as far as I can tell, it's fixed (on my side, can't speak for others).

Method: disabled any other extension or script pertaining to YouTube's player, other than YTC, opened from YouTube's channel list several (> 6) clips in background tabs.

Result: All are fully functional.

Side notes:
1. enabled "Disable Youtube™ HTML5 Player 1.1" extension, the one disabling prototype.canPlayType return, and it showed the same behaviour as YTC build 473. As YTC 477 works fully on its own, this extension is not needed anymore.

2. enabled "a" disable Youtube HTML5 Player script which disables prototype.play action, YTC 477 is fully functional and I noticed no interference.
