### ISSUE TITLE
Playlist videos missing default view size

### ISSUE THREAD

**Issue by F43nd1r** [YePpHa/YouTubeCenter#1434]
In Kino mode everything is ok:
![unbenannt](https://cloud.githubusercontent.com/assets/10252708/6076508/af30d770-ade4-11e4-93f5-ba4483a373a0.PNG)
But in default mode the playlist videos are missing:
![unbenannt2](https://cloud.githubusercontent.com/assets/10252708/6076509/af65cef8-ade4-11e4-89a2-b6dabb1539f9.PNG)

**Comment by seagull** [comment]
The second view is what I'm seeing and I think it's a bug resulting from YouTube changing their code; I'm used to the playlist appearing below the video, not to the right of it.

**Comment by YePpHa** [comment]
This should be fixed in the [developer version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version).

**Comment by F43nd1r** [comment]
Well...

![unbenannt](https://cloud.githubusercontent.com/assets/10252708/6256484/e6c46cbe-b7b8-11e4-9cde-873cd2f0e30e.PNG)
![unbenannt2](https://cloud.githubusercontent.com/assets/10252708/6256485/e8a7da98-b7b8-11e4-8258-c164728f9a10.PNG)

**Comment by YePpHa** [comment]
@F43nd1r that looks new. Do you have anything that could conflict with YouTube Center? Also could you please tell me which browser you're using and how you installed YouTube Center (addon or userscript w/ Greasemonkey or Tampermonkey),

**Comment by F43nd1r** [comment]
I don't think any of my other plugins coul dconflict wiuth it. Anyway, here's a list:AdBlockPlus, Hide Caption Titlebar plus, Instantfox, Tab Mix Plus, Masterpassword Plus

Browser: Firefox
Installed via addon (.xpi from git wiki)

**Comment by YePpHa** [comment]
@F43nd1r try to take a look at this issue #1463.

**Comment by F43nd1r** [comment]
Fixed in dev 481

**Comment by F43nd1r** [comment]
Note: Not a real Problem, because reloading the page fixes this. Still: When I toggle (no matter whether on or off)  the 'hide footer' settting while in  a playlist tab, this bug arises again.

**Comment by YePpHa** [comment]
@F43nd1r It's still a problem even if reloading the page fixes it. The ideal solution is to not having this issue appear at all. So if it's an issue then please create a new issue preferable with a reference to this issue.
