### ISSUE TITLE
Video not filling out the whole space

### ISSUE THREAD

**Issue by xur86x** [YePpHa/YouTubeCenter#1437]
I just made a picture, because explaining would take long: http://puu.sh/fDOfj/a6171af6f0.png
This is what happens to me sometimes.
Version 2.1.7 with Opera

**Comment by Yonezpt** [comment]
Install the developer version which can be downloaded here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by dragons4life** [comment]
Is there a reason, why you guys haven't fixed this on the released/normal version?

**Comment by Yonezpt** [comment]
@dragons4life There is only one person -the addon author- working on the addon whenever he has the time for it.

**Comment by dragons4life** [comment]
@Yonezpt Thank you
