### ISSUE TITLE
Subscriptions Not Updating

### ISSUE THREAD

**Issue by HaikenEdge** [YePpHa/YouTubeCenter#1439]
Started Saturday Pacific Time ish; both my Uploads Only and Activities tab under Subscription are no longer updating at the top; in fact, I have to scroll down for it to fetch new updates, which also repeat the old ones, and some uploads aren't even showing up in the Uploads Only tab. Not sure what's happening there, so I'm including screenshots in case I'm not particularly clear:

Before I scroll down
![ytstuckbefore](https://cloud.githubusercontent.com/assets/9447962/6111285/87deff58-b03c-11e4-93d1-ddfad8b8342e.jpg)

After I scroll down (note the new item, "single release celebrationz" that is more recent that the "JUPITER ASCENDING - Double Toasted Video", that doesn't show up in the first screenshot).
![ytstuckafter](https://cloud.githubusercontent.com/assets/9447962/6111304/ac2db94e-b03c-11e4-8d4f-8221f52c4984.jpg)

Something similar is happening in the "All activity" tab as well.

**Comment by Yonezpt** [comment]
This is a YouTube problem which many users have already reported on the Google forums:

https://productforums.google.com/forum/#!category-topic/youtube/VogctZdi4U4

https://productforums.google.com/forum/#!category-topic/youtube/HL8Ph5-LFLQ

https://productforums.google.com/forum/#!category-topic/youtube/4FW2YVse2Ac

https://productforums.google.com/forum/#!category-topic/youtube/yxL6Tws1jhw

https://productforums.google.com/forum/#!category-topic/youtube/C2sKKTJoGL0

https://productforums.google.com/forum/#!category-topic/youtube/q7h8EIjSgkM

https://productforums.google.com/forum/#!category-topic/youtube/rDrbHFdqq-s

https://productforums.google.com/forum/#!category-topic/youtube/4S69CUFAuS8

**Comment by YePpHa** [comment]
This is a YouTube issue and therefore I will not fix it as it should already be fixed or at least be fixed in the near future by YouTube.
