### ISSUE TITLE
Disabling DASH doesn't make videos load

### ISSUE THREAD

**Issue by pH142857** [YePpHa/YouTubeCenter#1451]
I am on a rather slow connection and I would like to watch my videos in something higher than 144p. YouTube just won't let me as it now pauses the buffering as long as the video is paused.
So I installed YouTube Center to disable the DASH Playback, but it does not seem to work.

I was thinking, this DASH technique is about cutting down the video into *segments*, which is not the default behaviour I observed: Youtube won't load the video **at all** (passed a small portion) while it's paused. So is it possible that these dumbf*cks implemented a new discriminative restriction which is not DASH? Is there a workaround?

**Comment by chdft** [comment]
I think YouTubeCenter can only disable DASH, if you are using the HTML5 player (and not the flash one). Can you disable flash and try again?
If you are using the HTML5 player without dash, you should be able to find a video element in the dom, after the video started playing. The src tag contains an url to a (usually mp4) video. Can you try to open this url with your browser and if that doesn't work in a media player with support for network streaming? If the url looks like "mediasource:{some numbers here}", you are using DASH playback.
If you don't know how to view the current dom tree: You can usually open the web developer tools using the F12 key on your keyboard. After that you have to search for something like "Inspector" or "DOM Explorer". After that you use the search box to search for "video", the first video tag (if any exists) on the page you are viewing will get highlighted.
Additionally, it would be helpful to know what browser and which version of YouTubeCenter (userscript / firefox addon / ...) you are using.

**Comment by pH142857** [comment]
Hi, thanks for your detailed answer. Sadly (but happily for me), I am forced to contradict you: DASH seems to be disableable even with the Flash player. Indeed, I installed the Youtube Center **developer version** instead of the one available on https://addons.mozilla.org/en-us/firefox/addon/youtube-center/ that I had before, and unckeching the Dash button works like a charm. This also nullifies my post-DASH restriction hypothesis.
Thanks anyway, your commitment is appreciated.
