### ISSUE TITLE
"An error occured. Please try again later."

### ISSUE THREAD

**Issue by pH142857** [YePpHa/YouTubeCenter#1452]
Most of the time, when I activate YouTube Center, this message appears instead of any video. Also, the player becomes much bigger and centered, causing layout problems in the page, although I haven't modified any settings.
I'm on Firefox 35, using the Flash player last version.

**Comment by ErdeFB** [comment]
You forgot to mention which version of the add-on/script you are running.
Anyways, you might want to give the developer version a try if you have not yet. It's more up to date.
You can get it from here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by pH142857** [comment]
I downloaded Youtube Center from https://addons.mozilla.org/en-us/firefox/addon/youtube-center/ just today so I guess it's the latest. I am experiencing the dev version right now, and it seems to work so far. Thanks a lot. I hope for the people that whatever enhancement made to the dev version which fixed my problem will soon be released in the standard one.

**Comment by ErdeFB** [comment]
The Mozilla add-on page actually has even older version what the current stable version is so no wonder you had problems. Then again, I doubt the latest stable version would work without problems anyway, so getting the developer version was a smart choice for at least now.
