### ISSUE TITLE
Firefox html5 sizing error

### ISSUE THREAD

**Issue by Mattk50** [YePpHa/YouTubeCenter#1456]
The new htlml5 player for firefox was just rolled out on youtube, phasing out flash. It's great, except youtube center isn't resizing it properly The issue is pretty clear from the screenshot, good luck solving it.

![youtubeprob](https://cloud.githubusercontent.com/assets/11055436/6242858/8e830146-b704-11e4-9680-efaf337514de.png)

**Comment by Yonezpt** [comment]
This issue has already been fixed a long time ago in the developer version, you can download it from here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by Mattk50** [comment]
oh, duh, thank you.
