### ISSUE TITLE
Resizing video doesn't work

### ISSUE THREAD

**Issue by SnowGabe** [YePpHa/YouTubeCenter#1457]
I'm having problems with the aspect ratio. I want to use large video player but the video is still in default size. I removed Magic Actions for YouTube because it’s supported by advertising (and tracking). 

Latest version 2.1.7 installed with Tampermonkey (Google Chrome 40.0.2214.111 m 64-bit)
Are you still developing the extension?

![2015-02-17 20_16_26-fifty accents of grey with jamie dornan](https://cloud.githubusercontent.com/assets/11059234/6246859/0c3f6874-b776-11e4-9184-2e0ab8236e79.png)

**Comment by Yonezpt** [comment]
Install the latest developer version which has this problem fixed. You can find it here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by SnowGabe** [comment]
Does the developer build update automatically?

**Comment by Yonezpt** [comment]
Unless an error occurs it updates automatically.

**Comment by SnowGabe** [comment]
I can confirm my issue has been solved with the latest dev build. I hope it is stable enough to use.
