### ISSUE TITLE
Fill screen off-centre

### ISSUE THREAD

**Issue by sam288** [YePpHa/YouTubeCenter#1459]
When selecting fill screen as default option

Player has scroll bar and need to scroll to the right in order to see the complete player
![screenshot](https://cloud.githubusercontent.com/assets/10268922/6252832/50fecb4a-b79d-11e4-9955-521790a12ab4.png)

edit: using lastest dev build on chrome with tampermonkey

**Comment by YePpHa** [comment]
Seems to be caused by enabling flex on the watch page. It's fairly easy to fix.

**Comment by sam288** [comment]
Thanks for the quick solution :) appreciate your work
