### ISSUE TITLE
Player alignment problem

### ISSUE THREAD

**Issue by LazyBoot** [YePpHa/YouTubeCenter#1463]
Something added today (feb 18) seems to have messed up the alignment of the video player
With youtube center enabled:
![Imgur](http://i.imgur.com/JxeMIQS.jpg)

With youtube center disabled:
![Imgur](http://i.imgur.com/cYI7AAw.jpg)

**Comment by LazyBoot** [comment]
I should also probably mention that I'm not using any resizing from youtube center.

**Comment by KDsMax** [comment]
@LazyBoot Just curiosity, what is your player size? I really want that one so bad.

**Comment by LazyBoot** [comment]
@KDsMax It's the default size I get from youtube.

**Comment by KDsMax** [comment]
@LazyBoot I only get playlist there if I choose small size, if I choose default size then playlist goes under the video.

**Comment by LazyBoot** [comment]
@KDsMax It think it's related to the height of the window, because I only get that size on the monitor that doesn't have the taskbar on it. And only when maximized.

**Comment by KDsMax** [comment]
@LazyBoot Weird, when I disable Resize I don't get playlist nor description at all. And I still don't get the look you have (YouTube Center disabled). I do get the look you have when YouTube Center is disabled. Pretty weird thing.

**Comment by rayman89** [comment]
@KDsMax you need to configure the  predefined option you are choosing for resizing the video and tick off the wide video option. Also there you can change the size to your liking.

**Comment by YePpHa** [comment]
What's the resolution of your monitor? It might be an issue with those higher than 1920x1080.

**Comment by rayman89** [comment]
My monitor resolution is exactly 1920x1080.

**Comment by YePpHa** [comment]
@rayman89 weird, I was only able to get this issue when I went into the developer tools and set the device screen to be bigger than my current 1920x1080.

**Comment by KDsMax** [comment]
I think it's impossible to get this look when YouTube Center is enabled.

**Comment by LazyBoot** [comment]
Problem still persists in build 480. However I have discovered that toggling off "Flex width on page" will turn it back to normal, but that only lasts until the next time I load/reload a video page.

**Comment by YePpHa** [comment]
I will take a look at the flex width on page option to try figuring out what it does that makes this happen.

Also it needs an inner size of at least 1720x980 for the largest player size.

**Comment by KDsMax** [comment]
I think I fixed my problem.

Enable resize: Enabled
Player aspect: Default
Default player size: 1280x750 (Large player disabled)

Now playlist and suggested videos appears correctly. You can even keep taskbar visible.

**Comment by Yonezpt** [comment]
@LazyBoot is correct, the problem lies with flex-width. Should be a simple case of increasing the max-width for the flex option to accomodate the new YouTube max-width.

**Comment by YePpHa** [comment]
@Yonezpt the weird part is that I've added a CSS rule that sets the `max-width` to none.
![ss 2015-02-19 at 10 42 44](https://cloud.githubusercontent.com/assets/2348303/6276650/aaa275ca-b888-11e4-8445-42cc2d50d718.png)

**Comment by LazyBoot** [comment]
@YePpHa That CSS rule only shows up for me if I enable the player resize option.

**Comment by YePpHa** [comment]
@LazyBoot ohhh, I now remember that I added something in YouTube Center that removes the resize styles when the player resize is disabled. I will just have to move that CSS rule, which is quite simple.

**Comment by Yonezpt** [comment]
Was going to say exactly what @LazyBoot said, this is what I get when I have player resize disabled, which is when the problem appears:

![ss](https://cloud.githubusercontent.com/assets/8498057/6277060/eca9db60-b87a-11e4-9200-04604bcb9490.png)

**Comment by YePpHa** [comment]
I'm uploading a possible fix now.

**Comment by Yonezpt** [comment]
So far so good, the problem is not there anymore.

**Comment by Badgerconda** [comment]
I am still having this issue with the latest version, exactly as the original poster described. It also goes away temporarily if I disable the 'flex width on page' option, but re-occurs if I reload the page or load another video.

**Comment by LazyBoot** [comment]
That's weird, because the problem is now fixed for me.

**Comment by rayman89** [comment]
@Badgerconda Are you using developer version 481? check on the option menu bottom left corner.

It got solved for me too.

**Comment by Badgerconda** [comment]
Yep, build 481. Looking more closely at what the OP posted though, I think what I'm seeing might be slightly different. For me, If I maximize the window, everything aligns properly. But if I decrease the width of the window past a certain point, the video is offset from the left edge of the screen by a blank gap that wasn't there in earlier versions of YTC.

The issue goes away if I disable youtubecenter, so I would assume it's not an issue with a youtube update or another add-on (I've tried disabling everything else that impacts youtube, but the problem persists as long as YTC is active)

Let me try throwing in a screenshot to see if that makes it more clear. What I'm talking about is the gap to the left of the video.

![screeny](https://cloud.githubusercontent.com/assets/11082657/6279871/c1dc8b34-b862-11e4-8f00-f5fdf1f07c38.jpg)
