### ISSUE TITLE
Videos only show 720@30

### ISSUE THREAD

**Issue by dapal-003** [YePpHa/YouTubeCenter#1468]
When i'm looking at the main page of youtube all videos i see are labeled 720p 30 fps but when i go and watch them i can switch to 1080p. How can i fix it so all video's will be shown in 1080@60 fps ? I've try'ed looking trough all the settings but i couldn't find a setting that was set to 720p they where all at 1080

**Comment by Zarggg** [comment]
What version of YTC are you using? What browser are you using? Do you have any settings changed from the default that might affect this, e.g., forcing the Flash or HTML5 player to be used or a specific resolution?

**Comment by dapal-003** [comment]
Latest, Google chrome only settings changed is all auto-resolutions are set to 1080p use HTLM5 and dissabeld DASH playback

**Comment by Zarggg** [comment]
I reproduced the issue by modifying those settings from the default and found that it can be resolved by re-enabling DASH playback.

**Comment by dapal-003** [comment]
Darn, alright i hate youtubes DASH playback but if it fixes it all i will. Thanks for helping!

**Comment by HowellBP** [comment]
I opened another related issue, maybe it's the same one: #1485

Except in this case it doesn't apply to just the thumbnail but to video playback itself. Video playback defaults to 720p@30 every time regardless of whether or not DASH is enabled, as well as default resolution (I have to manually change to 1080p or 60fps).

**Comment by Zarggg** [comment]
Tested this again with Developer Version 481 and I am seeing the behavior @HowellBP is reporting now.

**Comment by HowellBP** [comment]
Build 483 seems to have resolved the selection issue. DASH still affects selection and thumbnail though, but that may be a limitation of YouTube's non-DASH playback.

**Comment by YePpHa** [comment]
@HowellBP there's an option to disable the separation of DASH on the thumbnails with the option `Separate DASH and non-DASH formats` in UI -> Video Thumbnail under the Quality section.
