### ISSUE TITLE
Recommended videos title not showing up when player resizing is disabled and on a large screen

### ISSUE THREAD

**Issue by Elassyo** [YePpHa/YouTubeCenter#1470]
The titles of the recommended videos on the right of the player don't show up when player resizing is disabled, when in the Default View and on a large screen (e.g. 2560x1440).

Player Resizing disabled:
![ytc_resize_off](https://cloud.githubusercontent.com/assets/3268661/6275939/72272db2-b883-11e4-9cef-707ef24030ec.png)

Player Resizing enabled
![ytc_resize_on](https://cloud.githubusercontent.com/assets/3268661/6275982/c7fca546-b883-11e4-9614-f922a6456e4a.png)

Browser: Chrome 40
YTC version: Dev build 480

**Comment by Yonezpt** [comment]
Same issue as #1463
