### ISSUE TITLE
changelog for dev builds

### ISSUE THREAD

**Issue by F43nd1r** [YePpHa/YouTubeCenter#1474]
I would like to see a changelog for the dev build, so I know when something should be fixed.
Is this anywhere and I missed it? Otherwise treat this as a request.

**Comment by AwesomeDonkey** [comment]
Read the commits: https://github.com/YePpHa/YouTubeCenter/commits/master

**Comment by YePpHa** [comment]
I wrote one yesterday on [/r/youtubecenter](http://www.reddit.com/r/YouTubeCenter/comments/2wcyfg/youtube_center_developer_version/).

Some changes from v2.1.7:

* Fixed issue where the video only takes up a part of the HTML5 player (see [#1117](https://github.com/YePpHa/YouTubeCenter/issues/1117))

* Fixed issue with comment width (see [#1061](https://github.com/YePpHa/YouTubeCenter/issues/1061))

* Fixed removal of artist details on search page (see [#1053](https://github.com/YePpHa/YouTubeCenter/issues/1053))

* Fixed padding for author country flag (see [#1064](https://github.com/YePpHa/YouTubeCenter/issues/1064))

* Fixed rare issue where settings were not restored to default.

* Fixed issue where ratings were not positioned correctly.

* Fixed consistency with the dash symbol in `auto-play`.

* Fixed issue where `{author}` tag didn't work for filenames (see [#1178](https://github.com/YePpHa/YouTubeCenter/issues/1178)).

* Fixed compatibility with e10s (see [#1079](https://github.com/YePpHa/YouTubeCenter/issues/1079)).

* Fixed issue where live streams were not loading (see [#1201](https://github.com/YePpHa/YouTubeCenter/issues/1201))

* Fixed issue with prevent auto-play for the HTML5 player (see [#1204](https://github.com/YePpHa/YouTubeCenter/issues/1204))

* Fixed issue where 'auto resolution' and 'auto lights off' don't work if SPF is enabled (see [#1217](https://github.com/YePpHa/YouTubeCenter/issues/1217))

* Fixed issue where YouTube Center caused an issue with recently closed tabs in Firefox (see [#1213](https://github.com/YePpHa/YouTubeCenter/issues/1213))

* Fixed issue where comments' country flag were loading permanently (see [#1159](https://github.com/YePpHa/YouTubeCenter/issues/1159))

* Fixed issue with the channel player (see [#1221](https://github.com/YePpHa/YouTubeCenter/issues/1221))

* Fixed issue where flags don't show the translated name of the country (see [#1224](https://github.com/YePpHa/YouTubeCenter/issues/1224))

* `/u/` and `/c/` will now be recognized as channels (see [#882](https://github.com/YePpHa/YouTubeCenter/issues/882)).

* The wiki links in settings will now have the same target (see [#1330](https://github.com/YePpHa/YouTubeCenter/issues/1330))

* Fixed issue where the playlist will show too many videos ([#1384](https://github.com/YePpHa/YouTubeCenter/issues/1384)).

* Fixed issue where older settings will be saved.

* Added option to disable footer (see [#1394](https://github.com/YePpHa/YouTubeCenter/issues/1394))

* Added option to go to videos without a playlist (see [#1383](https://github.com/YePpHa/YouTubeCenter/issues/1383))

* Added an option to hide the header when playing a video (see [#786](https://github.com/YePpHa/YouTubeCenter/issues/786), [#1393](https://github.com/YePpHa/YouTubeCenter/issues/1393)).

* Added option to reduce the width of the search page (see [#1385](https://github.com/YePpHa/YouTubeCenter/issues/1385)).

* Added option to replace an animated YouTube logo with a static logo (see [#1269](https://github.com/YePpHa/YouTubeCenter/issues/1269)).

* Added option to go to subscriptions at the end of a video (see [#481](https://github.com/YePpHa/YouTubeCenter/issues/481))

* Added option to hide the watch later button on the HTML5 player (see [#393](https://github.com/YePpHa/YouTubeCenter/issues/393))

* Added option to enable/disable the manipulation of the like/dislike button and the manipulation of the rating bar colors (see [#1186](https://github.com/YePpHa/YouTubeCenter/issues/1186)).

* Added default color to the sparkbar on thumbnails when there are no likes or dislikes (see [#1195](https://github.com/YePpHa/YouTubeCenter/issues/1195)).

* Added playlist auto-play button to radio playlists (see [#1192](https://github.com/YePpHa/YouTubeCenter/issues/1192)).

* Added option to prevent YouTube Center executing on embedded pages to minimize memory usage ([#1045](https://github.com/YePpHa/YouTubeCenter/issues/1045))

* Flag for unknown countries added

**Comment by F43nd1r** [comment]
Thanks
@YePpHa You could put one of these links on the wiki page, so this question does not arise again.

**Comment by YePpHa** [comment]
@F43nd1r done.
