### ISSUE TITLE
Borders appearing in "fill" player size.

### ISSUE THREAD

**Issue by Donbero** [YePpHa/YouTubeCenter#1475]
After a recent change, using the "fill" player size causes a border to appear on the left and right sides of the video, although only if the window itself has a width of under 1000px or so. Border size increases the smaller the window's width is.
![ytcbug](https://cloud.githubusercontent.com/assets/11082154/6277933/bd0b24d2-b860-11e4-8fcf-a3a14e922763.png)

**Comment by Yonezpt** [comment]
Same issue that @Badgerconda reported in https://github.com/YePpHa/YouTubeCenter/issues/1463#issuecomment-75173255 , which I will quote since it appears that his comment is not loading up:

>Yep, build 481. Looking more closely at what the OP posted though, I think what I'm seeing might be slightly different. For me, If I maximize the window, everything aligns properly. But if I decrease the width of the window past a certain point, the video is offset from the left edge of the screen by a blank gap that wasn't there in earlier versions of YTC.

>The issue goes away if I disable youtubecenter, so I would assume it's not an issue with a youtube update or another add-on (I've tried disabling everything else that impacts youtube, but the problem persists as long as YTC is active)

>Let me try throwing in a screenshot to see if that makes it more clear. What I'm talking about is the gap to the left of the video.

![screeny](https://cloud.githubusercontent.com/assets/11082657/6279871/c1dc8b34-b862-11e4-8f00-f5fdf1f07c38.jpg)

What is happening is that the player and the main page content is centered on the page itself, but since you are reducing the size of the window the page stays on the left side. If you move the horizontal scrollbar to the right you will see that everything is centered. What I assume it should be doing is to fit the player to the size of the window, regardless of the window size, increasing and decreasing in size to fit the available window space.
Let's wait to see what YePpHa says about this.

**Comment by YePpHa** [comment]
Seems like the issue us caused by the flex-width. The flex width is setting a minimum width for the #page element.

I think the solution is just to override the `min-width` rule, but I wonder if doing so will break something else.

**Comment by Badgerconda** [comment]
@YePpHa  The thing about flex-width, is that changing the setting temporarily fixes the problem, but only until you reload the page. Figured I'd mention that in case it impacts your fix.

**Comment by YePpHa** [comment]
@Badgerconda No need to worry. I can make it permanent in YouTube Center.

**Comment by Turbonator** [comment]
I still have this issue: (Chrome Canary 42.0.2311.0 - YouTubeCenter 486)

![image](https://cloud.githubusercontent.com/assets/11126118/6316524/c5e2920c-ba31-11e4-845b-a46893454d09.png)

**Comment by YePpHa** [comment]
@Turbonator please post your YouTube Center settings?

**Comment by Turbonator** [comment]
http://speedy.sh/7aYjk/ytcenter-settings.ytcs

(Theater mode and Default view works correctly without black borders).

**Comment by Yonezpt** [comment]
Kinda looks like an issue with setting the controls' bar visibility to hidden, but not working as it should.

**Comment by Turbonator** [comment]
Auto hide bar is set to Default.

**Comment by YePpHa** [comment]
Seems like there is a new bug, the settings file contained only `null`. Anyway, just a question @Turbonator is this present on all videos?

**Comment by Turbonator** [comment]
Yes it is.

**Comment by YePpHa** [comment]
Okay, as it seems like there's a bug with the settings exporter could you tell me the settings configuration for the player sizes?

**Comment by Turbonator** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11126118/6316644/41d04706-ba37-11e4-8491-f4622c8cb10b.png)

**Comment by Turbonator** [comment]
Black bars disappeared when I changed 750 to 720.

**Comment by YePpHa** [comment]
@Turbonator are you using your Custom player size? If you are I would leave the `Height` field blank as YouTube Center automatically calculates it if it's missing.

**Comment by YePpHa** [comment]
Okay, I think we have found the culprit. Just leave height blank and it should be fixed.

**Comment by Turbonator** [comment]
Yep.

**Comment by YePpHa** [comment]
Good to know.
