### ISSUE TITLE
Subtitle / CC can't be turned on

### ISSUE THREAD

**Issue by p1nkyy** [YePpHa/YouTubeCenter#1478]
As per subject, the subtitle / CC button can't be turned on. It just loads and loads and loads but nothing happened. I'm in FF 35, GM 2.3, YTC script Dev Build 4.81. I want to roll back to previous version but don't know how T__T Pls anyone help me...

**Comment by YePpHa** [comment]
You can find older versions [here](https://github.com/YePpHa/YouTubeCenter/commits/master/dist/YouTubeCenter.xpi).

**Comment by p1nkyy** [comment]
The subtitle button finally can be turned ON. I don't know whether other people also experienced this. If nobody does, pls close this issue.

**Comment by YePpHa** [comment]
I'm not sure where the issue could have come from, but if it's not happening then I will close this issue. Also if your issue does appear again then create a new issue with a reference to this issue.
