### ISSUE TITLE
Grid Subscriptions - 6 columns across instead of 7

### ISSUE THREAD

**Issue by GreenLego** [YePpHa/YouTubeCenter#1479]
Hi, I have recently switched from 2.1.5 to 2.1.7 and noticed that the grid layout in 2.1.7 is now 6 columns wide instead of 7 columns in 2.1.5. Was this an intentional change? Is there a way for me to make it 7 columns (or 8) in 2.1.7.

I switched to 2.1.7 because 2.1.5 no longer allows me to download the clips for offline viewing, but 2.1.7 does. As it is, I use 2.1.5 for normal day to day use, but switch to 2.1.7 when I need to download.

**Comment by YePpHa** [comment]
Yes, this was an intentional change. YouTube had their own standardized grid view on channel pages (see https://www.youtube.com/user/TotalHalibut/videos) and I didn't want two different layouts so I trashed mine and used YouTube's.

**Comment by GreenLego** [comment]
Thank you for your reply. It's a pity, as I really prefer the 7 column view. With 6 columns, so much of the screen is wasted.
