### ISSUE TITLE
Prevent auto-buffering doesn't work

### ISSUE THREAD

**Issue by Dol-phin** [YePpHa/YouTubeCenter#1481]
Prevent auto-buffering option doesn't work and the video seems to "buffer" even further. I've tested several times.

Dev Build 481
Google Chrome 40.0.2214.115 m (64-bit)

**Comment by BradJJ** [comment]
no matter what setting i choose, my current page won't buffer or play when i open it and ones i open in another tab always buffer but don't play. 
latest chrome, dev build 481.

**Comment by mzso** [comment]
I think the now pretty old autobuffering issue deservers a higher priority now that it seems MSE lands in firefox too in the next version.
Here's what I get with YTC:
(fully buffered video with a useless empty videoscreen)
![ab-ytc](https://cloud.githubusercontent.com/assets/4479090/6390920/2858eb3e-bdb1-11e4-9f3c-6a4a52061709.png)
And here's Magic Actions for comparison:
(I get the classic click to play screen which I only get with YTC if I click a recommended video with SPF enabled)
![ab-mag](https://cloud.githubusercontent.com/assets/4479090/6390979/7ab4be4e-bdb1-11e4-9259-b6fa3fbd9f73.png)

**Comment by mzso** [comment]
Oh by the way I'm on firefox nightly. But MSE videos should work with the new v36 without too common issues.

**Comment by mzso** [comment]
Any hope of this getting fixed? It makes browsing youtube rather unpleasant and problematic that every opened  video page starts to buffer.

**Comment by mzso** [comment]
Hmmm... It seems things changed with FF38 (or the player that youtube serves for it). 
Now only a smaller amount is buffered and it's not visible on the player until you start playback. Anyway it's a definite improvement.

**Comment by Dol-phin** [comment]
Seems to be fixed now, thank you!
