### ISSUE TITLE
[FF36/MSE Default On] Developer #481 | HTML5 Won't 1080p+

### ISSUE THREAD

**Issue by Aphetoros** [YePpHa/YouTubeCenter#1484]
**Browser name**: Firefox
**Browser version**: 36
**YouTube Center version**: Developer Version - Build #481 
**Issue description**: All HTML5 videos will only play in 720p. My auto-resolution tab option is set to Original Resolution. 

Is this related to Firefox or YouTubeCenter?

**Comment by Aphetoros** [comment]
Got the answer:
https://support.mozilla.org/en-US/questions/1046349

Closed.

**Comment by ErdeFB** [comment]
Just came to say that even though you managed to solve the issue, big thank you for making a properly formatted issue report and including all the relevant info. That is so rare to see here.

PS: Mailing list, please don't hurt me. :(
