### ISSUE TITLE
Resized Playlist videos

### ISSUE THREAD

**Issue by F43nd1r** [YePpHa/YouTubeCenter#1490]
Reference #1434

Detailed steps how to reproduce this issue:
- Load a playlist
- Disable Kino mode if active, should look like this:

![unbenannt](https://cloud.githubusercontent.com/assets/10252708/6316200/b07116ae-ba1e-11e4-910e-b811b4be5f8b.PNG)
- Go to Youtube Player Settings and toggle the 'hide footer' setting (doesn't matter if on or off)
Now it looks like this:

![unbenannt2](https://cloud.githubusercontent.com/assets/10252708/6316207/d3464654-ba1e-11e4-9f8e-dba38a73b85d.PNG)

Reloading the page fixes this.

Things that may have something to do with it:
Browser: firefox
Player resize: Disabled
Flex width on page: Enabled

**Comment by YePpHa** [comment]
Okay, I was able to reproduce it too. Seems like it's caused by the `ytcenter-site-watch` class being removed from the body.
