### ISSUE TITLE
Minor documentation issue: Broken anchor link from Chrome:CompatibilityError to wiki#Chrome & Opera 15+ Extension

### ISSUE THREAD

**Issue by 3ICE** [YePpHa/YouTubeCenter#1495]
Hi,

On this page:
https://github.com/YePpHa/YouTubeCenter/wiki/Chrome:CompatibilityError

There is a bad link:
https://github.com/YePpHa/YouTubeCenter/wiki/Home#Chrome-&-Opera-15--Extension

Which redirects to:
https://github.com/YePpHa/YouTubeCenter/wiki#Chrome-&-Opera-15--Extension

But that is still broken. Unescaped ampersand in URL, also it does not match any anchor tags on the page. ("&" gets replaced with "-" by Github automatically, while "+" just gets removed now. In the past it was replaced with "-".)

The correct link would be:
https://github.com/YePpHa/YouTubeCenter/wiki#chrome--opera-15-extension

Sincerely,
Daniel "3ICE" Berezvai

**Comment by YePpHa** [comment]
Fixed.
