### ISSUE TITLE
Videos are "bouncing" when played

### ISSUE THREAD

**Issue by Croxed** [YePpHa/YouTubeCenter#1498]
**Browser name**: Google Chrome
**Browser version**: 42.0.2305.3 dev-m
**YouTube Center version**: Developer Version - Build #488
__Debug log__: https://gist.github.com/350a2fe6a43d1b2b6f8f
**Issue description**: Videos keep bouncing while playing but not in fullscreen. 
[Video of issue](https://www.youtube.com/watch?v=leSz7akw9f4&feature=youtu.be)

**Comment by Croxed** [comment]
Issue was already posted...

**Comment by Zarggg** [comment]
Linking #1497 for reference in case a search brings up this report but not that one.
