### ISSUE TITLE
Unticking "Auto-play first video in endscreen" doesn't do nothing

### ISSUE THREAD

**Issue by Pircha** [YePpHa/YouTubeCenter#1510]
YouTube may have changed something.

Right now I'm using this external script:
```javascript
try {
  var node = document.getElementById("autoplay-checkbox").parentNode.parentNode
  if (node.className == "checkbox-on-off")
    node.parentNode.removeChild(node)
}
catch(e) {}
```

Can this be integrated to the next developer version?

**Comment by Eisys** [comment]
YT recently implemented this stupid thing:
http://prntscr.com/6an14s
Might have something to do with it.. I just disable it though and it doesnt play the next video..
