### ISSUE TITLE
Not working after cleaning browser with CCleaner/CCEnhancer

### ISSUE THREAD

**Issue by blue-lightning** [YePpHa/YouTubeCenter#1525]
I've just used CCleaner with CCEnhancer to clean my computer yesterday. In CCleaner, I check every option about Firefox except Cookies, Saved Form Information and Saved Passwords. After that, whenever I went to Youtube, while greasemonkey still had "Youtube Center Developer Build" in the script availabled, there's no trace of it anywhere: no gear icon, no Download button... just like a normal youtube layout.

Browser: Cyberfox 36.0 x64
YT version use: Developer 492, Greasemonkey script

**Comment by ErdeFB** [comment]
Have you tried the obvious steps of re-installing Greasemonkey and/or YTC?

**Comment by q1k** [comment]
ccleaner is probably the worst program there is

**Comment by blue-lightning** [comment]
I already did and it's working now. What I want to know is how CCleaner+CCEnhancer affects YTC and by what options. Just curious, that's all.

**Comment by Zarggg** [comment]
@q1k: That statement doesn't help anything.

@blue-lightning: I don't use CCEnhancer, but I do use CCleaner regularly and don't have this problem. I believe the "Site Preferences" option is responsible for losing your settings in YTC. Next time you run CCleaner, leave that option unchecked and see if you still lose settings.

**Comment by blue-lightning** [comment]
@Zarggg  It's not that the settings are lost, but the whole script does not run at all, leaving behind an unchanged YT

**Comment by Zarggg** [comment]
That's really unusual. I can't think of a way that CCleaner would interfere with a userscript functioning at all unless it's somehow set up to delete it all together.

In the interest of troubleshooting, what files (excluding the cache) come up for Firefox when you run it? Click Analyze instead of Run Cleaner so that it doesn't delete the files.

**Comment by blue-lightning** [comment]
Since this is an Analyze after cleaning up 3 days ago, it is probably less than normal. CCleaner/CCEnhancer detected lots of files in:
C:\Users\[Username]\AppData\Local\8pecxstudios\Cyberfox\Profiles\[ProfileDefaultName] - Internet Cache + Internet History
C:\Users\[Username]\AppData\Roaming\8pecxstudios\Cyberfox\Profiles\[ProfileDefaultName] - Session + Site Preferences

**Comment by Zarggg** [comment]
**Excluding** cache and history files, can you put a full list of the files on a pastebin somewhere and link it here? Ultimately, this may be an issue with CCleaner deleting something it should not be.

I see you mention you still have Site Preferences selected. That could very well be what is causing the problem.

**Comment by ErdeFB** [comment]
I'd have to agree with Zarggg. If you really have to get rid of such data (at least in Firefox or it's ports), do it from the browser and not via an external application.

**Comment by blue-lightning** [comment]
Yup, Firefox Site Preference alright. Since it's an option not of CCEnhancer, guess I can't look into it to figure out what cause the problem. Thank you @Zarggg !

@ErdeFB I have used CCleaner and CCEnhancer for years without a hitch (till now) despite a lot of people saying they were dangerous. Beside, having a centre program to clean up everything is pretty convenient.

Now how do I close this issue...

**Comment by Zarggg** [comment]
As a follow-up, situations like this are why I have CCleaner set to not delete the Site Preferences files in my own install. The program isn't inherently "dangerous," but it's not for the novice, either. Sometimes you need to do a bit of research into what the files it deletes are actually used for.
