### ISSUE TITLE
The new font youtube is using is blurry (low priority)

### ISSUE THREAD

**Issue by snintendog** [YePpHa/YouTubeCenter#1532]
and seems to only be on my account i have found the node and deleting it returns the font style back to normal temporally, having a simple drop menu with some Basic fonts would be nice too in case they do this again. If there is a way to do this on a site by site basis without bothering you i would be very grateful. Thank ya.

![horrible youtube font](https://cloud.githubusercontent.com/assets/5448989/6456875/d1259e48-c139-11e4-8c94-137003696a15.png)

![horrible youtube font temp fix](https://cloud.githubusercontent.com/assets/5448989/6456818/ccc77e9e-c138-11e4-83f8-e61352de01ec.png)

```
<head><style name="www-Roboto">@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto Regular'), local('Roboto-Regular'), url(//fonts.gstatic.com/s/roboto/v15/2UX7WLTfW3W8TclTUvlFyQ.woff) format('woff');
}
@font-face {
  font-family: 'Roboto';
  font-style: italic;
  font-weight: 400;
  src: local('Roboto Italic'), local('Roboto-Italic'), url(//fonts.gstatic.com/s/roboto/v15/1pO9eUAp8pSF8VnRTP3xnvesZW2xOQ-xsNqO47m55DA.woff) format('woff');
}
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 700;
  src: local('Roboto Medium'), local('Roboto-Medium'), url(//fonts.gstatic.com/s/roboto/v15/RxZJdnzeo3R5zSexge8UUT8E0i7KZn-EPnyo3HZu7kw.woff) format('woff');
}
@font-face {
  font-family: 'Roboto';
  font-style: italic;
  font-weight: 700;
  src: local('Roboto Medium Italic'), local('Roboto-MediumItalic'), url(//fonts.gstatic.com/s/roboto/v15/OLffGBTaF0XFOW1gnuHF0YbN6UDyHWBl620a-IRfuBk.woff) format('woff');
}
```

**Comment by Yonezpt** [comment]
YouTube is trying to make Android and Desktop versions as similar as possible, the font being another one of their steps, it is the same font that exists in <a href="http://en.wikipedia.org/wiki/Roboto">Android</a>.

With that said, it is counter-productive to create a new option for something so trivial so for your case I'd suggest you use the Stylish addon and create a new stylesheet for YouTube where you can force the default font with the following code:

````css
*{
  font-family:arial,sans-serif !important;
}
````

**Comment by snintendog** [comment]
Thank you Very much this fixed the problem
