### ISSUE TITLE
Default Folder for Video Downloads

### ISSUE THREAD

**Issue by weaz12** [YePpHa/YouTubeCenter#1535]
I am currently using Mac OS X Yosemite and I was wondering if anywhere in the "YouTubeCenter" settings there is a way to select a default destination folder for all video files that are downloaded. Currently, anytime I download a video, it immediately begins downloading and automatically gets saved to a general "downloads" folder in my file directory. I read through the entire list of features listed at the link below, however I was unable to find any information on setting default folders for downloads.

 <a href="https://github.com/YePpHa/YouTubeCenter/wiki/Features/">(YouTubeCenter Features)</a>

My preference would be to have an option that allows me to specify a default folder of my choosing, etc. If that's not possible, before a video download begins, I would at least like to have the option to first be able to select a destination/folder in my directory where I would like the video file to be saved.

If either of these options exist currently or could possibly be available in the near future, I would appreciate any feedback or insight that anyone may have. Thank you very much.

**Comment by Zarggg** [comment]
I believe YTC simply follows the browser's own settings for default directories. That seems to be the behavior in both Firefox and Chrome.

**Comment by weaz12** [comment]
Wow....i can't believe I didn't think about that. That definitely has to be
it. ....Thank you very much for the response.

**Comment by YePpHa** [comment]
It seems like your question has been answered and I will not be adding a custom destination option for downloaded videos.
