### ISSUE TITLE
Frame interpolation for Youtube videos

### ISSUE THREAD

**Issue by SnowGabe** [YePpHa/YouTubeCenter#1541]
I don't know if this is is possible to implement but frame interpolation would probably be the most significant improvement YouTube Center has ever seen. 

SmoothVideo Project (SVP) program can achieve this for local videos on PC. I tried SVPtube ("app to extract direct URLs to live streams from YouTube and Vimeo and send it to your preferred video player that can play the stream as normal video with SVP and/or any post processing enabled") from the same author but I had issues with the playback, audio, performance and freezing.
Homepage: http://www.svp-team.com/wiki/Main_Page

**Comment by Yonezpt** [comment]
This is entirely different from just changing YouTube settings, you are asking for a completely standalone software to play YouTube videos on your PC, basically to replicate SVP's framework.

If you already had issues with the dedicated program then you will have even more with a browser based software and that's only the first problem, the other one being the conflicts that might cause the YouTube player api to crash.

**Comment by YePpHa** [comment]
I have to agree with @Yonezpt. It is currently not feasible to implement and will not at all be practical due to limitations set by browsers.

You will have to use SVP or some other software alternative to get frame interpolation.
