### ISSUE TITLE
YouTubeCenter not active/working/available

### ISSUE THREAD

**Issue by silkmaze** [YePpHa/YouTubeCenter#1545]
I am running FF 36.0.1 and have installed the YouTubeCenter script version 2.1.7. I should, according to the documentation and the installation on Chrome, see the option/configuration screen as soon as I get to Youtube.com. I don't. 

When I click on a video on youtube, I should see, like I do on Chrome, not only the option/configuration screen, but also all the options under the youtube player. I do not see anything there.  I don't. 

Just to show the differences, I have added a couple of screenshots, taken today 7th March 2015.

First from Chrome, Shot 1 - where the gear wheel can be seen on the right hand side and Shot 2 where the options - Download, Repeat, Aspect and Resize can be seen:
![chrome - youtubecenter-2015-03-07_164200](https://cloud.githubusercontent.com/assets/11368548/6543222/b0e8694e-c4ea-11e4-803c-80c94d7fb388.jpg)

Chrome Shot 2
![chrome - youtubecenter-2015-03-07_164139](https://cloud.githubusercontent.com/assets/11368548/6543224/ca322b4c-c4ea-11e4-9912-1fb87c8dbb43.jpg)

Here are the same shots as above for Firefox (v.36.0.1), Shot 1 - NO gear wheel present, and Shot 2 - NONE of the options are available :

![firefox youtubecenter-2015-03-07_165128](https://cloud.githubusercontent.com/assets/11368548/6543233/47897f64-c4eb-11e4-83a9-c992d10e6a8c.jpg)

Firefox Shot 2
![firefox youtubecenter - 2015-03-07_170100](https://cloud.githubusercontent.com/assets/11368548/6543253/d4817304-c4eb-11e4-9179-efdd12c9a528.jpg)

What do I need to do to activate and use this script.

Thanks.

**Comment by Zarggg** [comment]
Version 2.1.7 is known to be incompatible with Firefox. Use the Development Version until a new stable release can be made.

**Comment by Yonezpt** [comment]
To add to what @Zarggg said, you can find the developer version here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by silkmaze** [comment]
Brilliant, it worked. 

Thanks guys.
