### ISSUE TITLE
No download button or link, can't Like videos

### ISSUE THREAD

**Issue by Kierne** [YePpHa/YouTubeCenter#1550]
There is no download link available for any videos. See screenshot. Also, if I click on the Like button for a video, the button turns blue but it doesn't seem to actually stick because if I return to the same video the button is grey again. I can add videos to lists just fine. I don't know if the two issues are related. AdBlock and Ghostery are both disabled on Youtube so nothing should be blocked.

Running the Tampermonkey script YTC v2.1.0 in Chrome. 

![screenshot 2015-03-09 09 10 45](https://cloud.githubusercontent.com/assets/6403104/6556594/81e8f322-c63c-11e4-80ed-0bcc3cd8fdb6.png)

**Comment by Yonezpt** [comment]
v2.1.0 is outdated, it is best to use the developer version until YePpHa publishes v2.1.8
You can download the dev version here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by Kierne** [comment]
That got it working. Thanks much!
