### ISSUE TITLE
Like/Dislike buttons sort of not working

### ISSUE THREAD

**Issue by Sethycakes** [YePpHa/YouTubeCenter#1555]
Hi, today I noticed that when I liked/disliked a video it appeared to do nothing and the buttons remained their usual color. Also, the notification on the upper-left wouldn't appear either. However, I discovered that upon liking/disliking a video then refreshing the page it turns out that the video was successfully liked/disliked. I tried disabling Youtube Center and this restored the proper function of the buttons.

**Comment by ErdeFB** [comment]
Duplicate of #1553

**Comment by Sethycakes** [comment]
Hmm I couldn't find that when searching for issues with the word "like" in them. Oh well, I'll go subscribe to that instead. Thanks!
