### ISSUE TITLE
dev version wiki entry: could break your computer -> wrong

### ISSUE THREAD

**Issue by Djfe** [YePpHa/YouTubeCenter#1556]
@yeppha you should change the info on the dev version page, that the addon could break your computer since that is definitely not the case

if someone experiences issues with youtube he/she can easily uninstall/disable the addon to use yt normally again

**Comment by Hubcapp** [comment]
I think that's just legal speak, or half-joke.

**Comment by ErdeFB** [comment]
It's a pretty common way to say that if something bad happens, be it anything, for using the add-on, the author takes no responsibility for it.

**Comment by KamranMackey** [comment]
Fixed! :smiley:
