### ISSUE TITLE
Sugestion: Prevent Auto-play first recommended video Button

### ISSUE THREAD

**Issue by guiaurelio** [YePpHa/YouTubeCenter#1557]
In Chrome Version 40.0.2214.115 m
Youtube Center Developer Build 493

Everytime that a video ended, the first recommended video start... Maybe the "Playlist auto-play freeze" button is not working... Or another button...

**Comment by ErdeFB** [comment]
YouTube also introduced to auto-play some Up Next -video. There is a toggle button you can click near the top right and the setting should save. Assuming that is what you mean and not playlists.

**Comment by guiaurelio** [comment]
But I think it's not working then...

**Comment by ErdeFB** [comment]
Wait a second, if you have selected the option Playlist auto-play freeze, no matter what you select for auto-play to be on playlists, the setting you chose in YouTube Center for playlist auto-play should always stay enabled/disabled even though you click the toggle button on YouTube interface.

So are you saying this option is broken and this does not happen? Or are you misunderstanding what the feature does?

**Comment by guiaurelio** [comment]
I think it was a Youtube problem... I try to turn off the Youtube Center and turn on again... And now it works fine...
I think this issue can be closed. :)

**Comment by ErdeFB** [comment]
Uh, I see.

Anyway, since it is not a YTC issue, please click the "Close Issue" -button at your earliest convenience. Thanks.
