### ISSUE TITLE
Can't change sorting type on channel

### ISSUE THREAD

**Issue by MIC132** [YePpHa/YouTubeCenter#1562]
When in channel "Videos" tab when I change sorting type (to Most Popular for example) the type changes, and then suddenly the site "reloads" and I'm back at default. It's impossible to use any other type than default.

**Comment by Yonezpt** [comment]
Does the same behavior occur with YTC disabled?

**Comment by MIC132** [comment]
Bizarrely, the problem fixed itself since yesterday. I can only assume it was something on youtube's end and it was changed. Closing.
