### ISSUE TITLE
HTML5 player progress bar only goes 50% across video window

### ISSUE THREAD

**Issue by endymion0000** [YePpHa/YouTubeCenter#1567]
So this just started. I have my player default to 1280x720, but the visible grey part of the progress bar only extends half way across the window, so when the video reaches the end, the bar ends in the middle of the window.

There seems to be an inline style setting the width to 640px on this element:
div.html5-progress-bar.ytp-force-transform.red

Seems like that element and the elements contained within could use some adjusting and/or whatever defines the range that the indicators crosses to reach 100%.

**Comment by Yonezpt** [comment]
If you are not using the latest developer version then try it out and see if the problem persists, you can download it here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by Puremin0rez** [comment]
I can confirm this - started happening a few hours ago, they must have made some changes on the YouTube side.

Running Build 493

**Comment by Yonezpt** [comment]
Yes, just checked it, for some reason YTC is failing to fetch the correct pointer for the progress bar. Will try to see why because on my standalone version it is working correctly.

**Comment by Yonezpt** [comment]
Found the culprit. @YePpHa in line 10961 change

````javascript
if (typeof playerInstance[i][j] === 'function' && /return"detailpage"/.test(playerInstance[i][j].toString())) {
````

to

````javascript
if (typeof playerInstance[i][j] === 'function' && /"detailpage"\!\=/.test(playerInstance[i][j].toString())) {
````

To the others in this thread you can also apply the same change directly on your script, but remember that scripts modified locally will not autoupdate, so if you do change it remember to force an update check when a new version is out.

**Comment by endymion0000** [comment]
Confirmed. That fixes it.

**Comment by Fofer** [comment]
Fixed for me too.  Thanks.

**Comment by YePpHa** [comment]
@Yonezpt I will apply the fix.
