### ISSUE TITLE
Black bars.

### ISSUE THREAD

**Issue by Puk4400** [YePpHa/YouTubeCenter#1572]
Since 17/04/2015 on dev build v493, youtube videos display black bars on the side, and the progressive bar doesn't go until the end. The progress bar is also a bit bugged, moving the cursor on the page (not necessarily inside the video) cause the progress bar to rise and it takes a while for it to go back down.
http://i.imgur.com/7hc0uzb.png

**Comment by Eisys** [comment]
Already reported in #1567!
Youtube must of done a little update recently to the video player and this is what is at cause. Just gotta wait 'til Yeppha updates YTC!

**Comment by YePpHa** [comment]
Duplicate.
