### ISSUE TITLE
Disabling dash playback

### ISSUE THREAD

**Issue by KerrangR** [YePpHa/YouTubeCenter#1575]
My internet is really slow here, so if i wanna see videos in 480 which is the max res i can see without waiting ages for videos to load...

Now, when i disable DASH playback, it disables 144p, 480p and 1080p from the video res selection so im bounded to see videos in 360p which is stupid because i already can see 360p without issues wih DASH enabled

Im using Dev Build 493 on Firefox 36.0.1

Edit: Close this, i just read that its something to do with youtube and not with the add-on it self

**Comment by ErdeFB** [comment]
You can close this by clicking the close issue button.

**Comment by KamranMackey** [comment]
Closing since @KerrangR wanted it closed.
