### ISSUE TITLE
Blank/black embeds

### ISSUE THREAD

**Issue by ROBMID8746** [YePpHa/YouTubeCenter#1578]
Embedded videos on Tumblr, Reddit, and other sites are popping up as black boxes. Disabling YTC fixes, I tried disabling YTC from doing anything to embeds other than initialization but they still didn't show up.

It has been like this for about a month.

![capture](https://cloud.githubusercontent.com/assets/11545586/6719599/11c575a4-cd92-11e4-96bc-3501582472e8.PNG)

**Comment by Zarggg** [comment]
This is a known issue. If you are still using 2.1.7, update to the current Developer Version. If you are currently using the Developer Version, please report on what browser you are using and what your settings under External Players are.

**Comment by ROBMID8746** [comment]
Ah, alright, I wasn't aware of the developer version. Thank you for letting me know about it. I'll close the ticket since it's fixed in the build.

Have a great day!
