### ISSUE TITLE
the "DASH" option when disabled, disables videos in 1080p and 4k.

### ISSUE THREAD

**Issue by JelumaGames** [YePpHa/YouTubeCenter#1584]
the "DASH" option when disabled, disables videos in 1080p and 4k.

When I turn off the "DASH" I can not see videos in 1080p!

**Comment by xur86x** [comment]
That is something about YouTube that this extension cannot change.
YouTube only offers higher resolutions if you enable DASH playback.

**Comment by JelumaGames** [comment]
ok, thanks.

**Comment by xur86x** [comment]
Don't forget to close this ;)
