### ISSUE TITLE
Player size bug

### ISSUE THREAD

**Issue by ToastSky** [YePpHa/YouTubeCenter#1585]
![g5fztfu](https://cloud.githubusercontent.com/assets/11589514/6766590/18aba84a-d047-11e4-98c8-2c18aeee421d.png)

This happens once in a while, the actual video and progress bar stays in default view and the border stays in theater mode. The button says Default View when hovering on it.
I'm using chrome on a Mac OSX 10.9.5 with and I turn the size adjustment for player off, please help.

**Comment by leandroprz** [comment]
I'm experiencing the same problem. I'm using Windows 8.1 with Chrome. Tried a lot of different settings in YT Center with no luck.

**Comment by knackrack615** [comment]
Same problem here

Using Windows 8.1 with Chrome

**Comment by Yonezpt** [comment]
Are you all using the latest developer version number 495? If not then install it from here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by knackrack615** [comment]
Just installed it right now.. it works like a charm! :)

**Comment by ToastSky** [comment]
Trying it, is there any issue I should know with this developer build?

**Comment by knackrack615** [comment]
Yes, some video images are not loading sometimes but if you hover over them they will load
![8hnjab7](https://cloud.githubusercontent.com/assets/2822335/6783119/c0ac3318-d180-11e4-9d42-ce426ee1545f.png)

**Comment by ToastSky** [comment]
I am pretty sure that's an option or something, sounds so specific to be a bug...

**Comment by KamranMackey** [comment]
@Yonezpt It would appear that it happens to me sometimes as well, and I'm on build 495, so I'm adding the bug label, since it is a bug.

**Comment by Yonezpt** [comment]
@ToastSky There's less issues than the stable versions which are outdated

@knackrack615 That's a YouTube issue, as far as I can see, because the same thing happens when I am not using YTC. Basically YouTube tries to only load images when they are visible to the user, to save bandwidth, and it does that by detecting scroll and window size, but some times it fails to get the correct info and some of the images don't show until you scroll down.

@KamranMackey In that case it appears that YTC is failing for some reason, posting your console log output when this problem occurs might help YePpHa when he has a chance to look at it.

**Comment by ToastSky** [comment]
@Yonezpt There's a very VERY minor bug with the developer build, when setting Auto Hide Bar to Default, instead of hiding just the Progressbar like default youtube, it hides everything. Only when you set it to Only Progressbar it works like default.  Like I said, it's a very minor bug that doesn't really interfere with the experience too much, but it's there.

**Comment by iNfz** [comment]
i've having the same problem with resize, using Build #498

**Comment by Yonezpt** [comment]
@iNfz Make sure you are not getting the new YouTube transparent player. If you are in Firefox or Chrome, press F12, select the console tab, paste this:

`ytplayer.config.assets.js`

press Enter and check if the returned text contains `html5player-new-`

**Comment by iNfz** [comment]
Just tried build 499, same problem, resetting YTC, disabling other addons doesn't help.
https://gist.github.com/anonymous/cf13496ec7df5948bfc8 No transparent player?

**Comment by Yonezpt** [comment]
@iNfz That is almost certainly a Firefox problem. Open in a new tab `about:config`, then search for `layers.offmainthreadcomposition.enabled` and set it to `true`. Restart Firefox, check if the problem still persists.

Also update Firefox to 37.0.1

**Comment by iNfz** [comment]
@Yonezpt That did the trick. Thank you :)

**Comment by Yonezpt** [comment]
Guess this issue can be closed now since it was related to something that has been fixed for quite some time now. The other issues reported here should be posted in a new thread instead or in a related thread if it already exists to avoid duplicates.
