### ISSUE TITLE
Youtube Center crashing firefox

### ISSUE THREAD

**Issue by willemi89** [YePpHa/YouTubeCenter#1586]
Hey everyone, I am having a serious problem with the youtube center, the addon keep crashing the firefox after sometime...disabling the addon I don't have the crashing problem anymore...I already tried many versions of the addon with no success...any help?

**Comment by Yonezpt** [comment]
In those many versions are you including the developer version 495? Which can be found here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by willemi89** [comment]
Yes, I am, but I just realized that the problem is with the firefox and flash, not with the addon, sorry...
