### ISSUE TITLE
HTML5 Space and arrow keys doesn't work

### ISSUE THREAD

**Issue by emicom** [YePpHa/YouTubeCenter#1596]
Before build 495 the arrow keys and space/pause/play have work fine. Now at build 495 the keys have no effect, though on flash it does work fine. IMO it is build bug.

Apart from that - on html5 - around minute 20-25 video freeze, but not the audio. The player have circles on as it try to establish connection. Player doesn't "report" to YT - ie - if you came back to this video YT will play it from the time of freeze of the player. 
(Pale Moon browser)

**Comment by Zarggg** [comment]
This has already been reported in #1546. If you have "Enable shortcuts on page" enabled, turn it off until a fix can be made.

**Comment by ErdeFB** [comment]
Why are replies made to this issue disappearing?

**Comment by Zarggg** [comment]
I originally posted a reply to that effect, but realized he's not asking about that issue. He's saying that the arrow keys and space bare are *not* being captured by the video, as opposed to the more common issue of being unable to use the space bar in comments as it is instead captured by the player.

**Comment by emicom** [comment]
@Zarggg  Yep, it seams you are right. I've selected "Enable player shortcuts" enabled in options, but the latest build have reset all settings to default. It happened before too with upgrading the YTC.
So, it was false alarm boys. Sorry.

But the freezing of movie (not audio though) around min. 25 stays.
