### ISSUE TITLE
Download option only shows 720p

### ISSUE THREAD

**Issue by sam288** [YePpHa/YouTubeCenter#1601]
I set my download preferences to "original definition"
I tried setting it to 1440p or 1080p but same result

When watching a video that is 1080p or better the best quality I can select to download is 720p

![image](https://cloud.githubusercontent.com/assets/10268922/6886035/ce924850-d630-11e4-8265-7880b9581cf3.png)

**Comment by LittleVulpix** [comment]
I believe this is because of how youtube works nowadays; (DASH). The biggest resolution you can get a "complete" file in is 720p. Anything above that is in two separate tracks, audio and video.

**Comment by ErdeFB** [comment]
Yes, @LittleVulpix is right. This is not a issue YTC can easily or plausibly solve.

As this is not a YTC issue and has already been reported/suggested earlier, please close this issue report at your earliest convenience.

**Comment by sam288** [comment]
Thanks for your comment now I know why:)

didn't find anything in search, sorry

**Comment by Zarggg** [comment]
@YePpHa: Would it be possible to add this explanation to the official FAQ?
