### ISSUE TITLE
4k resolution option disappeared

### ISSUE THREAD

**Issue by isaquefontinele** [YePpHa/YouTubeCenter#1605]
I uploaded a video that I made with my gopro. After finished, the 4k option was there, no problem. But some hours later and after I swap the audio of the video using the youtube editor, the 4k resolution was gone! Only Full HD top is available.

**Comment by Zarggg** [comment]
Does this still happen with YTC disabled?

**Comment by isaquefontinele** [comment]
Sorry, my bad. This problem is not related to YTC. Is some bug internal
from youtube.



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=isaquefontinele@gmail.com&idSignature=22>

On Tue, Mar 31, 2015 at 1:22 AM, Tom Ditmars <notifications@github.com>
wrote:

> Does this still happen with YTC disabled?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YePpHa/YouTubeCenter/issues/1605#issuecomment-87942363>
> .
>



-- 
Isaque Fontinele
Graduando em Ciência da Computação
Universidade Federal de Campina Grande

**Comment by xur86x** [comment]
I recommend closing this issue since it's a YouTube bug.
