### ISSUE TITLE
Updated from (Developer Version) 495 to 496, now no longer works in Safari 8.0.4

### ISSUE THREAD

**Issue by Fofer** [YePpHa/YouTubeCenter#1608]
Hello:

I just updated my installed Developer Version from 495 to 496 and now, YTC is no longer working at all in Safari 8.0.4.  I have tried both the userscript as well as the Safari extension.  How do I get it back?  Is there a link to be able to download the previous version?  

Or is this some sort of cruel April Fools prank? ;)

**Comment by peterpan11** [comment]
I am currently having the same issue, but in Maxthon v4.4.3.4000 (Windows 8.1 x64). After upgrading from 495 to 496, not even the settings button shows up anymore. It's as if it isn't installed at all. I already tried re-installing the newest version for Maxthon but had no success with it so far. It shows up as installed in the extension tab as you can see below:

![ytc](https://cloud.githubusercontent.com/assets/2178506/6952604/81fb86a6-d8c3-11e4-95e2-466c05d655c7.png)

**Comment by mikewinq** [comment]
Same here, but Opera <15. The settings button won't load, tried both Userscript and .oex installer.

**Comment by blaqkplastic** [comment]
I had the same problem, I just downgraded to 495.

https://github.com/YePpHa/YouTubeCenter/tree/91d3225ef8c8df78e03d7aa08be0148d8d392270/dist
After choosing which one you want, select "View Raw"

**Comment by MichaelMKenny** [comment]
I'm also experiencing this issue. I'm running Safari 8.0.4 on Yosemite 10.10.2 also, and have downgraded to 495, but YouTube Center keeps bugging me about the new version (496) every time I refresh a page with the extension on.

**Comment by endymion0000** [comment]
Just joining the chorus. 496 no longer working in Safari. Downgraded to 495 works.

**Comment by YePpHa** [comment]
I think I know what the issue is. It seems as though the object EventTarget doesn't exist in Safari and Maxthon. I will update a new version with this fixed.

**Comment by MindTooth** [comment]
@YePpHa Just wanted to stop by and say thank you :+1:
