### ISSUE TITLE
Comment Country Flags don't display in newest dev. build (496) [chrome extension]

### ISSUE THREAD

**Issue by random6969** [YePpHa/YouTubeCenter#1610]
After updating to the latest dev. version today, I noticed that the country flags in comments no longer display.

**Comment by audjack99aus8** [comment]
not showing in firefox as well

**Comment by Inyokus** [comment]
Most likely duplicate of #1540.

**Comment by random6969** [comment]
This bug still exists in the current dev. version, 501. 
YePpHa, please fix this soon as it was an incredibly useful and interesting added feature, thank you!

**Comment by ireun** [comment]
Migrating all issues about country flags not working to one issue, check out issue number "1877".
