### ISSUE TITLE
New HTML5 Player design broke resizing

### ISSUE THREAD

**Issue by pezam** [YePpHa/YouTubeCenter#1612]
Hey,
I just got hit with a new HTML5 Player Design which broke resizing. Using Build 497 on Chromium  41.0.2272.118
![screenshot from 2015-04-02 13 24 25](https://cloud.githubusercontent.com/assets/8513777/6963154/e321c72e-d93b-11e4-9d11-7be2fc7410d6.png)
In fullscreen, the changes are more evident
![screenshot from 2015-04-02 13 24 40](https://cloud.githubusercontent.com/assets/8513777/6963159/fc0781d4-d93b-11e4-9ff5-a8c008b673d6.png)

**Comment by Yonezpt** [comment]
Haven't yet received the transparent player. Can you open your console, enter this:

````javascript
ytplayer.config.assets.js
````

And share with me the link it shows? I want to try forcing the script on my side to see if I can get it to cooperate.

**Comment by Vashetti** [comment]
Can confirm this is also occurring on Safari on the latest dev version. Feels like I've had this bug for over a year now. I just want videos to fill the actual player size...

**Comment by Yonezpt** [comment]
@Vashetti Are you also getting the transparent player like the original poster? If so can you do what I asked in my reply above so that we can study the code and try to find a solution?

**Comment by CrisBRM** [comment]
Happening on FF dev build.

**Comment by Yonezpt** [comment]
@CrisBRM Can you do what I asked in my replies above? Otherwise it will be impossible to find a solution if we do not have access to the same player that you guys are receiving.

**Comment by CrisBRM** [comment]
"//s.ytimg.com/yts/jsbin/html5player-en_GB-vflii3He3/html5player.js"

This video: https://www.youtube.com/watch?v=I2qBBBvYQOA

**Comment by Vashetti** [comment]
@Yonezpt I don't have the transparent player, no.

**Comment by Yonezpt** [comment]
@Vashetti Then your issue is different than this one, you should create a new issue because this one is specific to the new YouTube transparent player.

**Comment by Vashetti** [comment]
@Yonezpt My issue has had several threads on it in the past. Safari videos rarely fill the screen, people say download the dev version, but it never seems to fix the specific Safari issues, despite people saying the video size filling issue is fixed on Chrome, Firefox, etc.

**Comment by Yonezpt** [comment]
@Vashetti Then it's a matter of waiting until the addon author has the time to address the issue. It has been reposted recently in #1606

**Comment by Yonezpt** [comment]
Alright, after fiddling around with the script shared by @CrisBRM I can conclude that the resizing fix that I created is still working correctly. I replaced the YouTube player script I am receiving with the one shared by Cris and the video resizes as normal, so the issue lies somewhere else.

@CrisBRM Does your YouTube player also have transparent controls like the one shown in the screenshots posted by pezam?

**Comment by CrisBRM** [comment]
@Yonezpt No, it's the normal YT player.

**Comment by Yonezpt** [comment]
@CrisBRM Then your problem is also not the same issue as the one reported by the OP, but most likely the same as @Vashetti

**Comment by pezam** [comment]
Hey, sorry, my cookies get deleted every time my browser exits, so I don't have that player anymore. Hopefully someone else can get you that info, I'm sure they'll roll it out further soon.

**Comment by Yonezpt** [comment]
@pezam So am I correct in assuming that the issue is no longer present now that you have the normal player?

**Comment by Uoipka** [comment]
Because of this problem did not use HTML5 long time. On FLASH all works well
Use Opera 29.0.1795.30

**Comment by Yonezpt** [comment]
@Uoipka Unless your player also has transparent controls like the one displayed in the OP's screenshot, then your problem is not related to this one and has already been reported. Also make sure that you are using the latest dev version 497 which can be downloaded from here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by CrisBRM** [comment]
@Yonezpt You're right, it works now.
Thanks!

**Comment by Uoipka** [comment]
@Yonezpt, well dev version fix problem "broke resizing" but i can watch only 360/720p quality now seems like new problem

**Comment by CrisBRM** [comment]
@Uoipka Are you sure it's still forcing Flash? Can you try with both player types?

**Comment by Uoipka** [comment]
@CrisBRM flash have all 360,480 etc... HTML5 have only 360,720HD

**Comment by Yonezpt** [comment]
@Uoipka Check that you don't have DASH disabled in YTC options. I don't know Opera's HTML5 capabilities, but if they are like firefox 36 and below then you will only get 240p/480p and 720p when using the HTML5 player. See  #1197 and #1080

**Comment by Uoipka** [comment]
@Yonezpt oh, it's problem from opera. i try same and waiting for opera developers... he have MSE & H.264 support at opera://flags/ but it buggy.

**Comment by pezam** [comment]
@Yonezpt Yes, I suppose for the time being it can be closed.
