### ISSUE TITLE
scroll to player button gone

### ISSUE THREAD

**Issue by nikmurder** [YePpHa/YouTubeCenter#1615]
firefox 37 w/497 build as addon (not script) both on xp sp3 (x32) and w7 sp1 x64
after some of the latest YTC updates (can't figure out which exactly - there were like 3 of them during last several days) scroll to player button disappeared (next to upload). so did the annoying self-scroll bug (which i know was discussed here already)
deselected "scroll to player button" in fill settings (i use fill screen size) selected it again, saved - nothing(

**Comment by Raydor** [comment]
Confirmed, the same on Chrome

**Comment by SGOrava** [comment]
i have this problem too
Firefox 36
UserScript and Extension

**Comment by LaVey-Charkus-Veros** [comment]
I have the very same problem and I'm using Firefox 35. This issue started a few weeks ago. At first I thought it was related to a bunch of malware that took over my browser. I was able to get rid of it and I thought the disappearance of the button was a leftover. However, it seems many people have this issue too. Please fix this, it's driving me crazy!

I'm using YouTube Center 2.1.7.

**Comment by LaVey-Charkus-Veros** [comment]
When will this be attended to? Many revisions have been released recently but this issue still goes on.

**Comment by YePpHa** [comment]
@LaVey-Charkus-Veros one bug at a time :)

**Comment by LaVey-Charkus-Veros** [comment]
Thanks a lot! :¬D

**Comment by SGOrava** [comment]
Thanks :)
You saved my life, again :)
