### ISSUE TITLE
Getting "Error" message on hovering on any video

### ISSUE THREAD

**Issue by chankeypathak** [YePpHa/YouTubeCenter#162]
Video works fine but on the thumbnail I get the error as shown below

![img](https://f.cloud.github.com/assets/424822/1615616/d0207e40-55fc-11e3-8cc1-adaf4c90eb83.jpg)

**Comment by frdmn** [comment]
Yup, same for me. Chrome plugin, version 2.1.1.

**Comment by Haysooooom** [comment]
@frdmn  use the latest developer version which can be found here.
https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by frdmn** [comment]
@Haysooooom Thanks a lot, this fixed it for me! :)

**Comment by ErdeFB** [comment]
Glad to hear you got it fixed. Please close this issue at your earliest convenience.

**Comment by frdmn** [comment]
@ErdeFB It's closed, i just commented on it since it was the same issue.

**Comment by ErdeFB** [comment]
Didn't notice that. I got this mixed up with another issue. ;D
