### ISSUE TITLE
Fix for the resize issue with the transparent player, hopefully

### ISSUE THREAD

**Issue by Yonezpt** [YePpHa/YouTubeCenter#1634]
I thought I would have to stay up late for days again trying to find a fix for the resize issue with the transparent player, but fortunately I think I found a fix, which is far simpler than the previous one.

I am posting this in case YouTube decides in the future to make the transparent player permanent or for anyone that needs it now.

So basically the transparent player consists of two files, both have `-new` in their links:

The player module: `https://s.ytimg.com/yts/jsbin/html5player-new-vflkiLxkD/html5player-new.js`

The player skin: `https://s.ytimg.com/yts/cssbin/www-player-new-vfl2ujh_c.css`

There's no fixed cookie that allows us to try this feature willingly, as far as I could see they are testing this randomly and pontually, so if you have it and log out then you will lose it, or if your cookies are disabled/removed as well (https://github.com/YePpHa/YouTubeCenter/issues/1633#issuecomment-90956462).

Thanks to @viion (https://github.com/YePpHa/YouTubeCenter/issues/1633#issuecomment-90954817) I was finally able to track down the player module and study it to understand which resizing method they were using for this particular player.

In the standard player they are using fixed tables which set the player to default preset sizes which increase and decrease with the browser size, this one is a bit like the same thing, but this time it has a catch: it falls back to whatever size the player has if a certain condition is not met.

In this case they are using a condition that checks if the browser has the `matchMedia()` method in order to use the size tables, otherwise it uses whatever sizes the player has.

In the above mentioned player module you can find this condition: 

````javascript
f.Fb = function () {
    var a = this.A.T();
    if(window.matchMedia) {
        if((a.ub || a.Jb) && window.matchMedia('(width: ' + window.innerWidth + 'px) and (height: ' + window.innerHeight + 'px)').matches) return new H(window.innerWidth, window.innerHeight);
        if('detailpage' == a.ka && 'blazer' != a.j && !a.Jb) {
            if(window.matchMedia(T4.C).matches) return new H(426, 240);
            if(window.matchMedia(a.G ? T4.o : T4.j).matches) return new H(1280, 720);
            if(a.G || window.matchMedia(T4.A).matches) return new H(854, 480);
            if(window.matchMedia(T4.B).matches) return new H(640, 360)
        }
    }
    return new H(this.element.clientWidth, this.element.clientHeight)
};
````

As you can see, it's pretty straight forward. If there is no `matchMedia`then the function jumps to the last line where it returns the element sizes (in this case it's the player).

The biggest issue was locating this condition while inspecting the entire code.

@YePpHa I don't know if you think it is worth implementing this fix yet because they appear to be testing this player based on the A|B testing method and there's no guarantee yet that they will make it permanent, but the fix is pretty simple; just "brick" the matchMedia function like so:

`window.matchMedia = false`

I have been inspecting the YouTube pages and the only time that method is used is for the HTML5 player so I don't think it will cause any issues other than fixing the one that we want.

**Comment by ErdeFB** [comment]
Even thought it is not really appropriate to make comments like these, I'd still like to take the opportunity to thank you for your continued hard work, @Yonezpt when it comes to user improvements to YTC functionality.

Now that it has been said, other users should refrain from making similar comments.

**Comment by YePpHa** [comment]
This is actually very interesting. It seems like they have gone from using the [CSS media rule](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Media_queries) to using [matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) for checking the viewport size. Your suggestion to remove "brick" `matchMedia` seems like a valid method.

I will try to look into a way to enable the transparent player somehow.

**Comment by Yonezpt** [comment]
@YePpHa You need to prevent the default html5 script from running, which can only be done in Firefox via the `beforescriptexecute` event listener and then switch the default files in the `ytplayer.config.assets` object with the transparent player's. At least I found that to be the most effetive method.

Here's a script I made for my debugging that does this automatically: https://gist.github.com/Yonezpt/f9ae0de1376ae89cd2e8

**Comment by YePpHa** [comment]
I was able to get the new transparent HTML5 player.

You need to set `VISITOR_INFO1_LIVE=Q06SngRDTGA`. However, you need to do this through an extension due to all cookies set by JavaScript is marked as HTTP only, which means that the cookie can't be used on the https protocol. Anyway, I used [Cookie Inspector](https://chrome.google.com/webstore/detail/cookie-inspector/jgbbilmfbammlbbhmmgaagdkbkepnijn?hl=en-US), which makes a new tab named `Cookies` in the Developer Tools in Chrome (F12). I then edited the already existing `VISITOR_INFO1_LIVE` (just create it if it doesn't exist) and made sure that HTTP only was unchecked and then changed the value to `Q06SngRDTGA`. After that I just refreshed the YouTube page and I got the transparent player.

Also, this reminds me that I need to fix an issue where YouTube Center can't set cookies as non-HTTP only.

**Comment by YePpHa** [comment]
@Yonezpt That you can also do.

I set `window.matchMedia` to `undefined` and the video immediately filled the player. So your method of "bricking" the matchMedia API is working. I will try to create a method that can recognize the new player and then "brick" the `matchMedia`.

**Comment by Yonezpt** [comment]
Ohhh, only now I read those instructions on reddit. Too bad I didn't saw it earlier, could have saved me all of this trouble. Glad to hear that you found a better and easier method.

To distinguish between the transparent player you could check if the HTML5 file or CSS file contain `-new` in their links, it's the only easy diffence I found out so far.

**Comment by YePpHa** [comment]
@Yonezpt Exactly what I did. I now have a version that can detect if you're using the new player and will then just "brick" `matchMedia` instead of using your patch method.

**Comment by viion** [comment]
Fantastic work guys :+1:
