### ISSUE TITLE
Grid Subscriptions Layout broken

### ISSUE THREAD

**Issue by endymion0000** [YePpHa/YouTubeCenter#1640]
Not appearing as grid anymore. Now the thumbnails are stacked like the default layout except all the text is removed and there's even more vertical space between the thumbnails than default.

**Comment by ErdeFB** [comment]
Confirmed. Latest YTC Dev version (unpacked add-on) and Chromium at the time of writing.

**Comment by MaxBK** [comment]
same problem
Firefox 37.0.1 - YTC Dev 497
![grid](https://cloud.githubusercontent.com/assets/8518425/7098236/4717c32c-dfb4-11e4-9efd-ded6d6895215.jpg)

**Comment by MAGICCC** [comment]
Yup, YT changed their weird layout again .___. Why would they even do it

**Comment by jaryth000** [comment]
Not that this topic needs another report, but why not.
Same issue.
Full debug report: https://gist.github.com/bdd9a1edc8fe3eb9138f

**Comment by greatwroth** [comment]
I can confirm this as well

**Comment by deathdragon1987** [comment]
Same here. Running the latest version of chrome (43.0.2357.10 dev-m (64-bit)) and extension 497. http://i.imgur.com/cAjQV3U.jpg

**Comment by JaykeBird** [comment]
Doesn't really need to be said at this point, but I can confirm this as well.

Layout with YTC off: http://i.imgur.com/EKRPuFq.png

**Comment by TetraSky** [comment]
Same here, Grid subscription is broken. Disabling grid subscription fixes it, but then, you don't have grid subs anymore... but at least you still retain most of not all of the other YTC features.

**Comment by Roadcrosser** [comment]
I can confirm as well.

**Comment by snintendog** [comment]
Can Confirm as well. I should have expected this when they changed their flavicon again.

**Comment by ExcalibursZone** [comment]
I can also confirm. I noticed glitches a few days ago, but they seem to have been fixed. Now it's all borked. Firefox v37.0.1 YTC 497

**Comment by FabriciusRex** [comment]
Can confirm for Opera 28.0 YTC v2.1.7
