### ISSUE TITLE
Subscription Grid seems to have changed

### ISSUE THREAD

**Issue by Trueffel** [YePpHa/YouTubeCenter#1650]
I get the vertical list that is default, and on top, the info disappears, meaning only thumbnails are visible

**Comment by Zarggg** [comment]
What version of YTC are you using? This was fixed in a Developer Version released earlier today.

**Comment by Trueffel** [comment]
Oh yeah, stupid me, sorry.

 Build 497 latest Chrome 41.0.2272.118 m (64-bit)
