### ISSUE TITLE
After switching to html5 player, all videos got really choppy.

### ISSUE THREAD

**Issue by LittleVulpix** [YePpHa/YouTubeCenter#1654]
Disabling YTC allows me to use html5 and play 1080p 60fps video without a problem, no lags stuttering or anything. But with YTC on, even the 720p 30fps videos get really choppy. My CPU / GPU are not utilized much so that's not it.

Latest dev version of YTC and latest FF. (Oh, and using flash player works well with YTC on, but then I can't watch in 60fps).

**Comment by Zarggg** [comment]
What are your settings?

**Comment by LittleVulpix** [comment]
Which settings specifically?

Also I tried with/without hardware acceleration in the browser.

**Comment by LittleVulpix** [comment]
I found the cause, it is the "Player Glow" option. When enabled, html5 videos become incredibly choppy. Upon disabling it, all html5 videos play just fine @60 fps. Bug?

**Comment by LittleVulpix** [comment]
I guess I will close this, cause using the glow on non-chrome browser is unsupported and it is documented (even though not apparent at first sight).
