### ISSUE TITLE
My Subscriptions text not visible

### ISSUE THREAD

**Issue by Maverynthia** [YePpHa/YouTubeCenter#1655]
The My Subscriptions text on videos (Titles, desc, etc.) disappear now since I guess Youtube updated the look (again) and broke something.

Feature Request:
Bring back the grid view. It looks like they got rid of that grid view that lays out everything side by side for the OLD view.

EDIT: using v. 2.1.7

**Comment by pquerner** [comment]
I can confirm this. This happens if option "Grid Subscriptions" is enabled (General -> Layout).

**Comment by YePpHa** [comment]
This has been fixed in the [developer version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version).

**Comment by spideyx** [comment]
Do you please have an ETA for release? My browser is unstable enough as is.

**Comment by Zarggg** [comment]
You can install the Developer Version right now. In fact, it's generally recommended.

**Comment by spideyx** [comment]
Done, thanks. The warning had me a bit concerned.

**Comment by Maverynthia** [comment]
Awesome thanks, installed the dev version and it seems to be working right. Even the playlists are fixed on the page.

**Comment by kiwistrongis** [comment]
Just adding that the dev version fixed the issue for me too. (Recommending someone closes the issue)
