### ISSUE TITLE
High memory usage with no YouTube tabs open

### ISSUE THREAD

**Issue by azizLIGHT** [YePpHa/YouTubeCenter#1659]
YouTubeCenter is using 20MB+ memory according to [about:addons-memory](https://addons.mozilla.org/en-US/android/addon/about-addons-memory/) even though no YouTube tab is open. This is 4-5 times higher than the average extension I have installed which are actually acting on pages across many tabs. Can anything be done about reducing the memory profile to help those with limited resources?

I am on: 
* Ubuntu 14.04 x64
* Firefox 37.0.1
* Greasemonkey 3.1
* YouTube Center Developer Build 499

**Comment by Pontiac76** [comment]
Thanks for that addon.  Useful.

I don't see that issue with a brand new run of FF.  YTC-Dev499 is using
less than 2meg.  Total FF memory used apparently is 33meg.

**Comment by KamranMackey** [comment]
@azizLIGHT No, because f*ck Ubuntu.

**Comment by azizLIGHT** [comment]
@Pontiac76 I tested on a brand new run of FF and its around 2mb as you said. Sorry about that. I should have tested on a clean slate before posting here. Looks like @KamranMackey is correct. Either it's Ubuntu or something peculiar about my combinations of addons in my regular Firefox profile. I will mark this as closed.

**Comment by KamranMackey** [comment]
@azizLIGHT Might I recommend Manjaro Linux? It's less of a memory hog, and it's freaking awesome. It is based on Arch Linux, but has a much easier install process.
