### ISSUE TITLE
Grid subscriptions & Grid collections broken in Opera 12.xx

### ISSUE THREAD

**Issue by mikewinq** [YePpHa/YouTubeCenter#1661]
Grid layout doesn't work with Opera 12 & YTC anymore! I have tried both Developer Version 495(newer versions are not working with O12) and the latest stable v.2.1.7. 
![clip](https://cloud.githubusercontent.com/assets/11059760/7127550/43312a7a-e246-11e4-9bf1-260f1132db9c.jpg)

**Comment by patq911** [comment]
I have the same error except with no description or title, it's just the thumbnail. Chrome  43.0.2357.10 dev-m, v2.1.7 (pls 1.8 soon)

**Comment by indeedwatson** [comment]
I have the same error as patq911 except on Firefox 39.0a2 Developer Edition.

**Comment by evanroheff21** [comment]
I'm also seeing broken grid view (just thumbnails, no text) on Firefox 37.0.1 and Windows 8.1. 

![firefox youtube center grid broken](https://cloud.githubusercontent.com/assets/3443256/7128532/bbb4e67a-e210-11e4-893a-b76df3641c2f.PNG)

**Comment by Yonezpt** [comment]
For the users that are using the outdated version 2.1.7 please install the developer version 499 instead, you can download it from here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

@mikewinq Does the dev version 499 also not work with Opera? It doesn't work at all?

**Comment by KamranMackey** [comment]
@Yonezpt He's running Opera 12, the old one that was released before the new Opera came out. @mikewinq I don't recommend using Opera 12. That thing has security issues. Upgrade your Opera version, or switch to another browser such as Chrome or Firefox.

**Comment by mikewinq** [comment]
@Yonezpt No, anything newer than 495 is not loading in Opera 12.xx. 

@KamranMackey No, I haven't found a suitable replacement for presto Opera, I'm following the development of Vivaldi, but it's still to early in its development to be used as a default browser.

**Comment by KamranMackey** [comment]
@mikewinq Vivaldi? What? And anyway, fudge Opera. That browser's kinda stupid.

**Comment by Piter432** [comment]
@KamranMackey https://vivaldi.com

**Comment by YePpHa** [comment]
Fixed #1625. Opera v12 will now work with the newest dev version.
