### ISSUE TITLE
[Feature request] Add option to disable script update notice

### ISSUE THREAD

**Issue by Kanegasi** [YePpHa/YouTubeCenter#1663]
I opened YouTube today and got an annoying banner telling me to update the dev version to 501, even though it's supposed to update itself. I am using Greasemonkey and the addon has always updated from time to time by itself.

**Comment by Kanegasi** [comment]
As a preemptive comment, just in case this suggestion is rejected, the following entry in AdBlock will cut it out anyways for anyone else interested:

youtube.com##div[class="alerts-wrapper"]

**Comment by Yonezpt** [comment]
@Kanegasi Be aware that YTC makes use of YouTube's warning box, so by blocking it you will also not receive any warning given by YouTube.

Also It would be best if you'd change the title to something like `[Feature request] Add option to disable script update notice`

**Comment by Kanegasi** [comment]
@Yonezpt That's nice to know, even though I haven't recalled a YouTube site notification I was interested in. What specifically annoys me about that update box is that it is nested in the player's div, pushing the player down. I use the fill option so that the player fills my browser window automatically. It's a workaround to get a fullscreen html5 player by using f11. When that update notification popped up, the entire player was pushed down past the bottom of the displayed part of the browser.

I also changed the title as you suggested.

**Comment by Zarggg** [comment]
Does disabling ``Enable update checker`` setting under Update not disable the update banner?

**Comment by Inyokus** [comment]
It does for me.

**Comment by rayman89** [comment]
Also you can set the update interval to higher times so it doesn't bother you every video. Once you close it it wont appear again after that amount of time have passed if you are interested in knowing when there is an update but don't want to be bothered.

**Comment by mirogg** [comment]
@Kanegasi Could you send me your source script please ? There is problem with newer version of the developer build and I want to rollback to the previous one but cannot find it.

**Comment by Kanegasi** [comment]
Sorry for the length of time since I last replied.

@Zarggg @Inyokus @rayman89 I honestly thought that option was what did the updating. I guess updating is entirely through Greasemonkey itself. I unchecked the box. I assume I won't get any update banners now. If this option is exactly the feature I am requesting, I guess this ticket can be closed.

@mirogg Sorry to be blunt, but do you not understand what Github's purpose is? Every version of a piece of code is archived and all changes tracked. That's the point of a repository. I'll give you step-by-step instructions to access any version of YouTube Center as well as the direct raw link to the last version, 500.

1. On the main page to the YTC repository (click the bold YouTubeCenter link at the top of the page), click "dist" in the list of folders.

2. Click "YouTubeCenter.user.js".

3. Click "History" on the right, next to "Raw".

4. Click the carrots "< >" next to "2c47938".

5. Click "View Raw".

[Here's that "View Raw" link] (https://raw.githubusercontent.com/YePpHa/YouTubeCenter/2c479384813bbe0a3189b0bbc6dcf6e36cdac636/dist/YouTubeCenter.user.js)

Since the version numbers are internal to the script, they won't show anywhere in Github's UI. In that list where you clicked the carrots, the top entry is the current version, so just count down the rows.

**Comment by Kanegasi** [comment]
Noticed that the script updated to 503 with the check update option turned off. Confirmed to be the feature I'm requesting since I didn't see any update notification. Closing the issue.
