### ISSUE TITLE
My Subscriptions page not displaying text.

### ISSUE THREAD

**Issue by MystPhysX** [YePpHa/YouTubeCenter#1666]
Starting from around two days back, Youtube Center stopped formatting the My Subscriptions page properly.

Details:
Youtube Center v2.1.7
Safari 7.1.3

Please see attached screenshot and let me know what else I need to provide!
![screen shot 2015-04-16 at 4 26 36 am](https://cloud.githubusercontent.com/assets/6554675/7171017/01f39230-e3f1-11e4-88a3-46b25246d68e.png)

**Comment by Yonezpt** [comment]
This has been reported before, please update to the latest dev version which can be downloaded here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by MystPhysX** [comment]
Oh, hey thanks!
