### ISSUE TITLE
Thumbnails blocked from uploading

### ISSUE THREAD

**Issue by PureChaosX** [YePpHa/YouTubeCenter#1668]
This seems to have been an ongoing issue for a while now.

Currently using the Developer Build 501, thumbnails will not upload while YTC is enabled. All that happens is "Try Again" appears where the Custom Thumbnail button was.

Once I disable YTC and upload again, the thumbnail successfully gets uploaded. It's quite annoying and frustrating having to disable YTC EVERY time I wish to upload a thumbnail.

**Comment by Inyokus** [comment]
Appears to be a duplicate of #666. Are you using Firefox?

**Comment by ireun** [comment]
Merging issues regarding this to one github issue: Check out issue number "1932".
