### ISSUE TITLE
I cannot start video long time when 'prevent auto-play' is enabled and browser use HTML5-player

### ISSUE THREAD

**Issue by okpc-okpc** [YePpHa/YouTubeCenter#1671]
Browser is waiting response from host 'yt3.ggpht.com' and I cannot start playing video before he don't get it (usually it's about 1 or 2 minutes). But when I disable 'prevent auto-play' in YTC options or choose flash player in YouTube option - I can start video immideately, without waiting response from 'yt3.ggpht.com'.

Browser: Opera 28.0.1750.51
YTC: Developer Version - Build #501

**Comment by Yonezpt** [comment]
Could you tell us which operating system are you using? Is it windows 8.1?

**Comment by okpc-okpc** [comment]
It's Windows 7

**Comment by okpc-okpc** [comment]
Guys, it's all right today! Maybe it was problem with YouTube hosts with thumbnails and images... YTC works fine today.
