### ISSUE TITLE
Grid Mode

### ISSUE THREAD

**Issue by Corphix** [YePpHa/YouTubeCenter#1673]
Videos on Subscription page in grid mode do not show video title or description.
![ytc](https://cloud.githubusercontent.com/assets/10669251/7236152/62e4dd80-e750-11e4-9712-9fce51f0d06e.jpg)

**Comment by Yonezpt** [comment]
If you aren't using the latest developer version then download it from here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by Brottweiler** [comment]
Should be closed, there's another problem now, this perticular one doesn't exist anymore I think.
