### ISSUE TITLE
Video Content Not Resizing Properly

### ISSUE THREAD

**Issue by Tokthree** [YePpHa/YouTubeCenter#1674]
No matter how I change my settings the actual content displayed in a non-fullscreen video will not change it's dimensions properly and most videos will be off-center and have black space around them while others will resize beyond the boundaries of the player itself resulting in large portions of the video being cut-off.

![](http://i.gyazo.com/22687458165cfb48858dec1dac265c0a.jpg)

![](http://i.gyazo.com/97ab6aee1ace9304d40efe503bd8828b.jpg)

I am using the standard userscript version of YouTube Center, v2.1.7, and my browser is Google Chrome 64bit version 42.0.2311.90, though I have had this problem for several months now while the resize worked fine in the past

**Comment by Yonezpt** [comment]
Download the developer version instead, the 2.1.7 is outdated. You can download the dev version from here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by Tokthree** [comment]
Thank you very much, my problem has been fixed.
