### ISSUE TITLE
Watched videos badge has different color

### ISSUE THREAD

**Issue by Tester798** [YePpHa/YouTubeCenter#1686]
Watched videos badge added by YouTubeCenter has different color than the one which is added by YouTube itself. Seems like it's caused by adding it into slightly wrong place than it should be.
![bug](https://cloud.githubusercontent.com/assets/8844478/7294713/7ded503e-e9b8-11e4-99c2-14aa54d3ea7f.png)

**Comment by Yonezpt** [comment]
The thumbnail is being placed over the watched badge. They are essentially the same thing, but in different layer order.
