### ISSUE TITLE
Graphical bugs with fullscreen top player, dark UI theme, and lights out

### ISSUE THREAD

**Issue by aztectornado** [YePpHa/YouTubeCenter#1696]
First bug report ever, sorry if there's a format I'm not following.

Just noticed several features of the Youtube Center Developer build for Chrome (build 501) cut out on me, which is strange considering another tab opened about an hour ago still has all these features working and intact.

For starters, the new tab no longer initialized fullscreen top player. On scrolling to the top, it'll scroll up, widen, then about 50% of the time I'll see a severely offset version of the player at about 25% size scroll off the bottom right of the monitor, but never resize right, instead showing a black screen which I can exit out of by scrolling down, as usual.

That's the simplest issue, though things get stranger. The dark UI I formerly had, with a wide, grey box behind the player as shown here (https://i.imgur.com/4Yub8xN.png) is absent in the new tab. (https://i.imgur.com/gn4U6Rg.png)

Comparing the two in lights out (as I have it set to start this way on load) gets weirder. The old tab functions properly much like you'd expect (https://i.imgur.com/QH346ja.png), but the new tab displays a large black rectangle which continues off vertically below where it should be presumably under the player, offsetting the title, description, related section and comments. (https://i.imgur.com/qfeXQEQ.png)

Initial observations lead me to guess it's probably a youtube update that somehow broke everything, but I'm not fluent in python, and barely know HTML. I did not touch the settings between opening either tab, and have done a full cache refresh on the new tab with no noticeable change in graphical errors. There was also no update to the script that Tampermonkey reports, with the last update occurring 14 days ago.

**Comment by aztectornado** [comment]
Whoops, someone opened another issue documenting the black rectangle over at issue #1695 while I was documenting my issue. Sorry. .-.

**Comment by Long-Horse** [comment]
Yeah my top fullscreen thing is black too. Damnit youtube, if it aint broke, don't fix it.

**Comment by Greenphlem** [comment]
I'm getting the same thing, scrolling up to enable to fullscreen player causes a black screen as seen [here](http://gfycat.com/OffbeatCautiousHerring)

**Comment by SINE** [comment]
Related
#1695
#1697

**Comment by SanyaIV** [comment]
The black bars on the side of the videos are gone for me in version 502 however fullscreen top player is still 100% black for me. Just Sanyain.

**Comment by SanyaIV** [comment]
Thew new 502 version has fixed the black bars for me but fullscreen top player still shows me a black screen. Just Sanyain.

**Comment by Tailszefox** [comment]
Yes, it seems the fullscreen top player is still broken. When enabled, it just displays a completely black page.
