### ISSUE TITLE
Grid Subscription doesn't work the right way

### ISSUE THREAD

**Issue by fat2slow** [YePpHa/YouTubeCenter#1698]
![screenshot 2015-04-28 22 24 39](https://cloud.githubusercontent.com/assets/10214549/7384312/124568f2-edf6-11e4-8071-14e909cc32d5.png)
![screenshot 2015-04-28 22 25 01](https://cloud.githubusercontent.com/assets/10214549/7384313/12470c66-edf6-11e4-8054-9f028d66332d.png)

I don't know whats wrong but it's really annoying and when you put the Grid Subscription on it makes the YouTube center settings button disappear

**Comment by eduardog3000** [comment]
Upgrade to the [newest dev version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version).

**Comment by Brottweiler** [comment]
This doesn't happen anymore, we have this bug https://github.com/YePpHa/YouTubeCenter/issues/2064 instead now.
