### ISSUE TITLE
[Fullscreen Top Player] Mouse scroll up produce black screen

### ISSUE THREAD

**Issue by andykamezou** [YePpHa/YouTubeCenter#1699]
The video player does not go fullscreen anymore, but only produce black screen.

Chrome 42.0.2311.135 m
YTC Developer Version - Build 501

**Comment by andykamezou** [comment]
Sorry, dupe https://github.com/YePpHa/YouTubeCenter/issues/1696

**Comment by Greenphlem** [comment]
Getting the same
