### ISSUE TITLE
Fit to content player not alligned, has scroll bar

### ISSUE THREAD

**Issue by sam288** [YePpHa/YouTubeCenter#1703]
Using dev version 501 on chrome

![untitled](https://cloud.githubusercontent.com/assets/10268922/7387613/e6807fae-ee5e-11e4-8e74-b84dbdf80778.png)

**Comment by fishbiscuit13** [comment]
Getting this too, also breaks Fullscreen Player. Instead of video it's just black when it's active. Also scrolling right activates the broken Fullscreen as well.

**Comment by fishbiscuit13** [comment]
There's an extensive thread about this same issue at #1695.

**Comment by sam288** [comment]
Sorry, didn't use search, please refer to #1695 as advised by fishbiscuit13
