### ISSUE TITLE
player not centered, fullscreen top player completely broken 

### ISSUE THREAD

**Issue by MammothJerk** [YePpHa/YouTubeCenter#1705]
![](http://puu.sh/huZY8/58d17f92e9.jpg)
this happened this morning

and scrolling up to use fullscreen top player does the animation but only shows a black screen

![](http://puu.sh/hv08F/bf8a5d16ca.jpg)
waterfox 37.0.1
Developer Version - Build #501

**Comment by SINE** [comment]
duplicate of
#1695
#1696
#1697
