### ISSUE TITLE
Fullscreen Top Player is broken.

### ISSUE THREAD

**Issue by kilara1988** [YePpHa/YouTubeCenter#1710]
Triggering Fullscreen Top Player option leaves just a big black space instead of the player.
Using Stable FF with GM + Script.
Tested both HTML5 and Flash player.
![untitled](https://cloud.githubusercontent.com/assets/1025376/7396325/e62999a6-eea8-11e4-8928-7a3d61610096.png)

**Comment by Choonce** [comment]
Same here, using latest dev build and FF 39.

**Comment by loatroll** [comment]
Same with Chrome Version 44.0.2383.0 dev-m & Tampermonkey + Script.

**Comment by kilara1988** [comment]
It seems that build 503 that fixes [url=https://github.com/YePpHa/YouTubeCenter/issues/1696]#1696[/url] also fixed this.
