### ISSUE TITLE
Dark Player Background no longer works

### ISSUE THREAD

**Issue by bjornenalfa** [YePpHa/YouTubeCenter#1711]
I am using FireFox 37.0.2 and YouTubeCenter Dev version 503. The Dark Player Background hasn't been working for a couple of days.

**Comment by deusexcalamus** [comment]
Having this issue as well. FF 38,  YTC dev 503.

**Comment by yoshinatsu** [comment]
Yeah... the update seems to have fixed the misaligned player...
But unfortunately, YouTube seems to have broken the dark background.

**Comment by NicotherZ** [comment]
Possible to fix it or dark background is completely broken ?

**Comment by aztectornado** [comment]
duplicate of #1696

**Comment by ImmortalKnight** [comment]
i also have this issue. and if i disable youtube center, dark background works but the alignment + the black bar bug (something like  #1695 )returns. (new transparent player enabled)

**Comment by leandroprz** [comment]
I'm also having this problem on Chrome 42.0.2311.135 m (64-bit) / Win 8.1 x64
