### ISSUE TITLE
Autoplay button?

### ISSUE THREAD

**Issue by SuperSajuuk** [YePpHa/YouTubeCenter#1713]
So I'm using the developer version and I'm confused. How do I get the "Up Next" button switch to always be on? the documentation isn't very clear about how I should make it always enabled.

**Comment by fireattack** [comment]
Its can be On or Off just as normal as you don't have YTC. However, YTC broke the UI for it: so it always looks like "off". Check #1677

**Comment by SuperSajuuk** [comment]
@fireattack Okay, thanks for clarifying this issue. No point keeping this open, I'll wait for an update.
