### ISSUE TITLE
"Theater view" video doesn't show on center when play size feature is off

### ISSUE THREAD

**Issue by fireattack** [YePpHa/YouTubeCenter#1720]
1. Reset all settings to default.
2. Turn off Player size in Player entirely. Don't need to change anything else.
3. Open any video (force refresh recommended, otherwise more weird result would show up), go to theater view.
4. The video is not on center, but left.

**Comment by ToastSky** [comment]
Same problem, here's a picture of what it looks like. Using Dev Build 503
![2015-04-30 5 54 07](https://cloud.githubusercontent.com/assets/11589514/7410518/2334dc2a-ef62-11e4-9a77-ab767f7ec52e.png)

**Comment by ToastSky** [comment]
Same problem, here's what it looks like, using Dev Build 503
![bugged alignment](https://cloud.githubusercontent.com/assets/11589514/7410538/5d601608-ef62-11e4-917a-453bd95f27e5.png)

**Comment by Huskeyhund** [comment]
Same problem on dev build 503.

**Comment by liny-odell** [comment]
Caused by the fix for #1695. Reverting to build 501 fixes the problem: https://github.com/YePpHa/YouTubeCenter/tree/eb35b4c3375b88244fadd53bded5d62129ae682e/dist

**Comment by ToastSky** [comment]
>liny-odell
 It does, but every time I relaunch Chrome it auto updates even when I don't have that option enabled.

**Comment by fireattack** [comment]
THis one is fixed
