### ISSUE TITLE
Small gap appearing between header and video

### ISSUE THREAD

**Issue by caeldom** [YePpHa/YouTubeCenter#1723]
![image](https://cloud.githubusercontent.com/assets/6067646/7414841/8a15e890-ef98-11e4-8eed-7161e9c31c50.png)

Just updated to dev503 and gap was not there previously. I have my video resized to fill the window and the header to auto-hide, so that when I scroll up to the top, the top of the video would be at the top of the window, however now this small gap appears there instead.

**Comment by Piter432** [comment]
But while the player is 720p or 1080p this small gap is good ;)

**Comment by LiamBM** [comment]
I much prefer there being a small gap. Makes the page look neater.

**Comment by caeldom** [comment]
:( unfortunately when I have the video filling my window, that gap is very visibly annoying.

![image](https://cloud.githubusercontent.com/assets/6067646/7414994/8018f67e-ef99-11e4-9666-d4641e313c43.png)

**Comment by LiamBM** [comment]
Ah, for 100% size I can see how it could become very annoying. It looks much nicer when the player is at 90% or lower though. Maybe they should change it so that only 100% removes the gap :smiley:

**Comment by caeldom** [comment]
Yeah! I used to have it at a lower size and definitely liked there being a small gap up the top, but after discovering the hide header option, realised how easy it is to basically do the same thing as the fullscreen top player without needing to enable that, by auto-hiding the header and making the player go full size. But alas, now there is a gap ;_;

**Comment by Yonezpt** [comment]
The gap has been force by YouTube during their recent layout update yesterday. Shouldn't be too hard to fix.

**Comment by caeldom** [comment]
Dang YouTube! Think they own everything... oh wait, they do.

**Comment by Piter432** [comment]
Maybe a option for "Fill" option in player resize? :)

**Comment by MammothJerk** [comment]
![](http://puu.sh/hwOuX/3e77667da8.jpg)
i got the gap aswell

**Comment by LaVey-Charkus-Veros** [comment]
That damned gap is so incredibly annoying while using "Fill" size. Worst of all, as seen in the image posted above, it pushes the player slightly down, leaving the bottom half part of the controls hidden when I want to have my screen filled just with the player. It doesn't help that the "Scroll to player" button now is missing (issue #1615) and who knows when it will be restored.

**Comment by Inyokus** [comment]
Please don't remove this gap entirely, I really like it being there. Without it the player looks so densely packed to the top/header.

(kind of OT: To the people who use 100% size: I do in no way intend to tell you how to use YouTube(Center), but have you considered using the Fullscreen Top Player?)

**Comment by LiamBM** [comment]
As long as they don't remove the gap for 90% width. I do think the 100% width should have no gap though. As Inyokus said, when using 90% width, no gaps looks like something went wrong with the player and seems too densely packed at the top. Leaving a gap makes everything more evenly spaced out, making everything seem more neat.

**Comment by caeldom** [comment]
In the meantime @LaVey-Charkus-Veros I have changed my Fill settings to 100% width, and 102% height which for me offsets it enough so that the bottom of the video won't be cut off. You may have to fiddle around with your values to find what works for you.

@Inyokus I actually was using Fullscreen Top Player before but found it way too clunky, and the options for 'Enter on video play' and 'Exit on video pause' did not seem to work. Also you can't have the header appear while in Fullscreen Top Player mode. When I realised I could create exactly the same effect by having the header auto-hide, and the video size to fill the screen, I stopped using the Fullscreen Top Player mode completely. The amazing thing is, when the header unhides, the video actually resizes to accommodate space for it, so there is no need for scrolling whatsoever.

**Comment by Yonezpt** [comment]
@caeldom If possible, it is best to use `calc(100% + 10px)` instead of `102%` because those `2%` will vary drasticly whenever the browser height changes or if it is different between other users.

**Comment by caeldom** [comment]
@Yonezpt Yes, 102% will be arbitrary so dependent on your resolution, give or take 1% to compensate. How would you input calc(100% + 10px) within the width for the Fill setting though?

**Comment by Yonezpt** [comment]
If it allows you, insert the calc exactly like I said and CSS will automatically calculate the correct height to account for the 10px excess.

**Comment by caeldom** [comment]
Does it work for you? Mine won't allow me to type anything but numbers, not even pasting.

**Comment by Yonezpt** [comment]
You are right, the player sizes' input are sanitized for numbers only. Guess the appropriate way would be to use it with the Stylish add-on or patch it with 102% like you did, at least until YePpHa has time to consider the issue.

**Comment by ViperCode7** [comment]
Don't know what happened to Youtube enter and all of these fast/broken fixes.

Why does the player scroll up?

I can't use stylish to insert a gap because the player always scrolls down to fit the control bar on screen after stylish applies fixes.

The way I've always set it was to fill the screen with as much contents as possible, and the control bar was slightly cut off, but enough for most controls to work. Now it just hides top part of video and shows me controls.

**Comment by caeldom** [comment]
Yay the gap has disappeared for me! Seems like it was YouTube's end cos YTC hasn't updated.

**Comment by MammothJerk** [comment]
gap dissapeared for me too but the player controls are not onscreen fully
!(http://puu.sh/hEMG8/6286e00044.png)

**Comment by caeldom** [comment]
Try adjusting your width and height settings for the player size?

**Comment by MammothJerk** [comment]
it appears that its my Stylish theme Black youtube by panos that causes the misalignment turning it off seemed to fix the problem

however i can still see a 1 pixel white border at the top of the webpage which seem to indicate that the header is not completely removed because the 1 pixel border scrolls with me throughout the page
![](http://puu.sh/hENM9/4235e37194.png)

**Comment by caeldom** [comment]
Oh yes, I have that too, only realised after I disabled Lights Off. But it doesn't bother me as much as I have Lights Off set to 90% black which makes that 1px gap barely visible.

**Comment by MammothJerk** [comment]
still, not everyone uses lights off so its a bug nonetheless

**Comment by Yonezpt** [comment]
YouTube has been changing their vidoe page layout non-stop recently, so expect some issues to "go away" while others appear. Since the gap issue has already been fixed natively this issue can be closed, until it happens again which we hope it does not.

**Comment by Piter432** [comment]
<blockquote>Since the gap issue has already been fixed natively</blockquote>
Argh, damn YouTube -.- Can @YePpHa bring it back as option?

**Comment by YePpHa** [comment]
@Piter432 probably :)

**Comment by MammothJerk** [comment]
gap is still there on the latest version, its just the 1 pixel gap i commented about earlier
![](http://puu.sh/hG85D/49fdd016e9.png)

**Comment by YePpHa** [comment]
Hmm. Might be browser specific. I haven't noticed this on Chrome.

**Comment by YePpHa** [comment]
The gap might be something that can't be fixed. I sat the page background to pure black and you can still see a white line. I can't do anything about that as the white line seems to be not part of the page, but the browser itself.

![2015-05-08_21-48-28](https://cloud.githubusercontent.com/assets/2348303/7544305/091fb5a6-f5cc-11e4-8f95-37b320ed8319.png)

**Comment by MammothJerk** [comment]
what if its the header not being removed properly? i can tell that the white line follows throughout the page when scrolling, it would be weird for both browsers to have that specific one white line only on youtube.

ive also tried various dark themes and they seems to mask the white line.

**Comment by Long-Horse** [comment]
@caeldom unrelated, but how is your button bar transparent-ish?

**Comment by Zarggg** [comment]
@Long-Horse: That is the experimental player YouTube is testing right now. You can activate it at https://www.youtube.com/testtube

**Comment by YePpHa** [comment]
@MammothJerk I found the issue. It seems like it was caused by the header not being hidden completely. It was 1px inside the viewport.

**Comment by YePpHa** [comment]
@MammothJerk new dev version out with the fix.

**Comment by MammothJerk** [comment]
alright thanks a lot for fixing this :D love the script

**Comment by caeldom** [comment]
@Long-Horse yep what @Zarggg said (: though I activated it by changing a youtube cookie lol

thanks for the fix @YePpHa !
