### ISSUE TITLE
Youtube comment country flags don't load

### ISSUE THREAD

**Issue by random6969** [YePpHa/YouTubeCenter#1731]
@YePpHa I'm aware that this issue has already been posted multiple times by others and myself, but I feel that it isn't receiving enough attention. Youtube country flags on comments was one of my favorite features of this extension, in addition to letting me set my own auto-resolution for embedded videos. I'm sure many other users feel the same way. Please look into this issue, as it was a very interesting feature that I am sad to see missing. (Dev build 503, chrome extension)

**Comment by Inyokus** [comment]
I agree with you that this feature was great and it should be brought back. But opening a new ticket for expressing that will only make things confusing in the issue section. If you have anything to add to an issue that has already been reported, post a comment to that ticket, in this case #1540.

**Comment by random6969** [comment]
Apologies, I couldn't remember what my previous ticket number was so I started a new one.
