### ISSUE TITLE
Can't import settings 

### ISSUE THREAD

**Issue by thinkpad4** [YePpHa/YouTubeCenter#1738]
Firefox 17esr Greasemonkey 1.11beta1, Userscript version of dev build 506 and I can't import my settings.  I browse to the .part file and it says The File Is Not Valid.

**Comment by Inyokus** [comment]
The exported settings should have a ".ytcs" file extension. *.part are usually temporary files browsers create during downloads (and delete after the download is completed). Are you sure you're picking the correct file?

**Comment by thinkpad4** [comment]
On Firefox it saves as a .part file.  It never had a issue importing it before.  Would renaming the extension from .part to .ytcs work?

**Comment by Inyokus** [comment]
I just tested with the Firefox extension, it gives a *.ytcs file by default for me. However, when I renamed the file to a .part extension, YouTubeCenter wouldn't import it, so you should try renaming it as you suggested.

**Comment by Zarggg** [comment]
Firefox saves partially-downloaded files as .part until the download is complete. Your initial settings export did not completely save, which is why the import is not working.

**Comment by thinkpad4** [comment]
Yes renaming the extension from .part to .ytcs works

**Comment by YePpHa** [comment]
I've set a restriction on YouTube Center to only allow files with the `.ytcs` extension. This is to prevent people from accidentally upload the wrong file.
