### ISSUE TITLE
New layout and Prevent Autoplay

### ISSUE THREAD

**Issue by mleyen** [YePpHa/YouTubeCenter#1749]
As you know, YouTube has rolled out [a new player](https://www.youtube.com/testtube), which is nice and all, but clashes with YTC's Prevent Autoplay feature.

If the feature is enabled, the controls will not appear at all (but the right click menu works), showing only a black box.

The workaround for now is to press K to start the video manually. But this is not how most users would do it.

As the new layout will most likely be forced to everyone in the next months, you may want to fix it before this time.

**Comment by Yonezpt** [comment]
Their player is still incomplete, they haven't even added a cue mode for the watch pages which is why you only see a black box when autoplay is off. Working on it when itself isn't even complete/stable will very likely face more problems and waste time that the author doesn't have, it is best to wait until they have the product finished before working on it, unless YePpHa thinks otherwise.

**Comment by YePpHa** [comment]
The new player does not have a layout for when the video is stopped. If you call directly to the player API with `playVideo` the video will resume playing. I don't know if YouTube have planned on adding the layout for when the video is stopped. Normally, YouTube have implemented all the base features of a new player when they release them as a beta (alpha?). Anyway, the embedded player does in fact have the layout for when `stopVideo` is called. So I'm not sure if it will get added.

I will take a look at it and see if it's an easy fix.

**Comment by YePpHa** [comment]
It seems like YouTube intentionally hid the overlay, which should appear when the video is stopped. This is quite easy to fix and should be in the next dev version.

**Comment by mleyen** [comment]
Still not fixed for me, the player controls don't appear. Do I need to clear my cookies or something?

**Comment by YePpHa** [comment]
You should not be required to clear your cookies. I will try to look further into this.

**Comment by cxrn** [comment]
Yeah, I'm having the same issue. Firefox 37.0.2 with YTC Build #525

**Comment by Zarggg** [comment]
Just wanted to report that the overlay *does* appear on Chrome, but *does not* appear on Firefox.

**Comment by Starfox** [comment]
Ah that referenced issue is me!
Using Build 525 on Firefox 38.0.1
When I hit spacebar, as Zarggg suggested, the video begins to play and everything shows up suddenly (before that it's just a black square)
