### ISSUE TITLE
Rating count doesn't appear on thumbnails anymore

### ISSUE THREAD

**Issue by Mohamed3on** [YePpHa/YouTubeCenter#1751]
As said in the title, I have the rating count to be always visible on the video thumbnails, but now suddenly they all show 0 likes and 0 dislikes, even though the videos clearly have likes and dislikes. 
ex:
![capture](https://cloud.githubusercontent.com/assets/12295159/7514814/56ac8350-f4c1-11e4-95a3-d20a0b8c3e28.PNG)

**Comment by YePpHa** [comment]
Seems like the rating data from the gdata request doesn't exist. Wonder if it will reappear or if it will be forever gone.

The request YouTube Center makes:
`https://gdata.youtube.com/feeds/api/videos/{VIDEO_ID}?v=2&alt=json`

Here's an example:
[https://gdata.youtube.com/feeds/api/videos/cv8msHbqaFE?v=2&alt=json](https://gdata.youtube.com/feeds/api/videos/cv8msHbqaFE?v=2&alt=json)

**Comment by YePpHa** [comment]
Switching to V3 fixes this issue. An option have been created to use V3 in the settings where you also can use your own API.

**Comment by Yonezpt** [comment]
@YePpHa gdata v2 is supposedly deprecated as per the last year's announcement, now only v3 exists. Will the quota limits be sufficient for this kind of software application?

**Comment by Mohamed3on** [comment]
So the bug is fixed in a new version? is is released?

**Comment by Mohamed3on** [comment]
I'm sorry, where can I find the option to switch to v3? thanks a lot.

**Comment by Mohamed3on** [comment]
found it in general settings. works like a charm.

**Comment by YePpHa** [comment]
@Yonezpt True, but you can still use the v2 API somewhat. Though, they did remove the rating statistics yesterday and later they might remove other things too.

I have looked at the graph for today's requests and the quota limit seems to be sufficient for the time being. Today, there has been a total of ~400,000 requests out of 50,000,000. If the quota becomes an issue users can use their own API keys or I might look into increasing the quota.

Here's a little screenshot with a graph and stuff:
![2015-05-08_21-36-18](https://cloud.githubusercontent.com/assets/2348303/7544112/9ab57c6e-f5ca-11e4-82bd-a23d00f4a4fc.png)

**Comment by Inyokus** [comment]
Another measure to take if the quota doesn't suffice, would be to change the default to only load the rating data on hover.
