### ISSUE TITLE
playlist misaligned

### ISSUE THREAD

**Issue by ImmortalKnight** [YePpHa/YouTubeCenter#1753]
playlist is misaligned and is placed on top of the suggested videos on the side.

![capture](https://cloud.githubusercontent.com/assets/12203627/7523421/4795e918-f504-11e4-8979-b5f283d3a8af.PNG)

a page with a video without a playlist works fine. 

anyone else experiencing this issue?

i only have reverse playlist script on greasemonkey but enabling or disabling greaskmonkey doesn't make a difference. 

YTC build509
firefox 37.0.2
32" lcd tv

**Comment by Zarggg** [comment]
This happened to me shortly after updating to build 507, but stopped after restoring default settings. It may have something to with setting a custom player size.

**Comment by tenkuu** [comment]
Custom player sizes causes the issue.
Either disable custom player sizes or [revert to the old player.](https://www.youtube.com/testtube)

**Comment by Cyguard** [comment]
disabling custom player sizes does not change anything (at least for me) as the play list is still shoved down to the comments area or just jumps around and somehow ends up collapsed so you cant see whats in the playlist.
