### ISSUE TITLE
No gap on top of video...

### ISSUE THREAD

**Issue by LiamBM** [YePpHa/YouTubeCenter#1755]
![screen shot 2015-05-08 at 01 06 08](https://cloud.githubusercontent.com/assets/11802806/7528362/a2ec6d40-f51e-11e4-93d9-b114544ba007.png)

It seems as if the nice gap on top of the player has now gone in Build #509. Would love to see an option to bring it back, as it looks really strange gone.

**Comment by Yonezpt** [comment]
@LiamBM That isn't a YTC change, it was YouTube that reverted the change. The gap wasn't suppose to be there in the first place.

**Comment by LiamBM** [comment]
@Yonezpt Hmm strange. I guess this is a feature request then.

**Comment by Yonezpt** [comment]
@LiamBM In that case it would be best if you'd change the title to reflect a feature request instead of an issue.

**Comment by YePpHa** [comment]
An option has been added to add the gap.
