### ISSUE TITLE
Since ~509 Layout is broken (see screencaps) (possible fix in the last comment)

### ISSUE THREAD

**Issue by CaptainLeChimp** [YePpHa/YouTubeCenter#1768]
Hello...the layout is messed up lately ...the lower elements like comments and stuff scale with the player-size or sth like that have a look :
![ytcenter issue1small](https://cloud.githubusercontent.com/assets/10194458/7549063/49389cba-f627-11e4-8d4b-60e22b1330a7.JPG)
----------------
![ytcenter issue2small](https://cloud.githubusercontent.com/assets/10194458/7549066/524d0d68-f627-11e4-97f7-f658f7cc07d9.JPG)

hope youll fix it soon -love this plugin/script great work !!

**Comment by CaptainLeChimp** [comment]
two more... looks like the videothumbs have a div-issue or something ...theyre floating to the left overlaying comments etc

![capture3small](https://cloud.githubusercontent.com/assets/10194458/7549090/912f7880-f628-11e4-9d79-cbde88a2968c.JPG)
![capture4small](https://cloud.githubusercontent.com/assets/10194458/7549091/952451f4-f628-11e4-94ad-5dba3dfb42de.JPG)

**Comment by CaptainLeChimp** [comment]
![settings1](https://cloud.githubusercontent.com/assets/10194458/7549111/51dfb658-f629-11e4-9317-cf14fa357b5e.JPG)

**Comment by CaptainLeChimp** [comment]
Okay ... this would fix the issue

<div id="watch7-main" class="watch-sidebar">  has a "margin-left:645px"  ....when deactivated the issue is fixed for me....

![issuefix](https://cloud.githubusercontent.com/assets/10194458/7549226/e38e8f54-f62c-11e4-8bbc-1711a581d6ed.JPG)

**Comment by CaptainLeChimp** [comment]
proof :-P
![fixedproof](https://cloud.githubusercontent.com/assets/10194458/7549245/bf82f00e-f62d-11e4-9730-4d195bc9fe85.JPG)

-excuse the spam ;)

**Comment by YePpHa** [comment]
It seems to be an issue with [this](https://userstyles.org/styles/92164/youtube-lights-out-a-dark-youtube-theme) style. It adds a stylesheet to the page, which breaks it (the one you disabled in the dev tools):
```CSS
.watch-wide #watch7-sidebar {
  margin-left: 645px !important;
}
```

**Comment by CaptainLeChimp** [comment]
oh ...thx :) now im feeling stupid... totally forgot that i used the youtube löights out userstyle.... -_-

thx =)

**Comment by Eisys** [comment]
https://userstyles.org/styles/105165/youtube-dark-2015
I use this style, now that Lights Out is broken completely. Works just as well.

**Comment by ireun** [comment]
So, if that's not a YTC bug I'm closing this one. ;)
