### ISSUE TITLE
Problem with player

### ISSUE THREAD

**Issue by DaNTaF** [YePpHa/YouTubeCenter#1771]
Hello.
I use YouTube Center Developer Version.
after the last 2 updates i have bug.
my youtube in Hebrew and it RTL
![unnamed](https://cloud.githubusercontent.com/assets/9018485/7550829/85e25c1c-f679-11e4-96eb-4f63627956f2.png)

**Comment by gangsthub** [comment]
Youtube ES, seems different, but guess it's part of the same problem:

![image](https://cloud.githubusercontent.com/assets/6775220/7553455/4efc6e78-f6fa-11e4-9de8-c72b5e484fba.png)
