### ISSUE TITLE
Comments not loading

### ISSUE THREAD

**Issue by crosstiger** [YePpHa/YouTubeCenter#1774]
Im using Firefox 37.0.2 with YT-Center Dev 518.

The comments wont load on any video. It just says "loading...". It works with the main version of YT-Center 2.1.7 but i can't use that version because with it, my subscriptions list is just blank.

Any ideas?

**Comment by SINE** [comment]
Try the newest dev version, reset all the settings, clear your browser cache.

**Comment by crosstiger** [comment]
Thanks. I managed to fix it.

It was not the fault of YT Center. A cookie called "VISITOR_INFO1_LIFE" messed with Firefox.
