### ISSUE TITLE
Subscriptions grid display breaks the layout

### ISSUE THREAD

**Issue by LouisTakePILLz** [YePpHa/YouTubeCenter#1777]
It looks like the subscriptions list grid layout no longer renders correctly.

Here's how it looks like with the `Grid Subscriptions` option turned on:
![yc - subscriptions grid layout](https://cloud.githubusercontent.com/assets/920910/7551272/ce78ffcc-f650-11e4-9042-f0fede174168.png)

I don't have much of an idea what's going on here, as I don't really use the subscriptions list at all anyway.

Oh, and it seems like the configuration cogwheel icon doesn't show up on that page either.

**Web browser** -  Chrome 42.0.2311.135
**Script version** - 2.1.7

**Comment by ErdeFB** [comment]
When reporting an issue:

1) Make sure you are on the latest developer version.
2) Search that the issue has not been reported before.
3) Include your browser and its version number and the add-on version information in the report.

You failed all three.

**Comment by LouisTakePILLz** [comment]
@ErdeFB Yep, my bad, although I fail to see why you had to phrase that so harshly.
It seems like the issue has been recently fixed too.

Duplicate issues: #1670 #1698
Main issue tracking this problem: #1084
