### ISSUE TITLE
The video player size is all jacked up

### ISSUE THREAD

**Issue by cblupodev** [YePpHa/YouTubeCenter#1781]
![it broke](http://i.imgur.com/UYkzW0D.png)

https://gist.github.com/anonymous/4fdc8c8db98cd1b83edd

http://aboutbrowser.com/view/8gDZZ

**Comment by Yonezpt** [comment]
Update YTC, you are still using version 406 when the most recent version is 520, this bug has been fixed already.

**Comment by cblupodev** [comment]
Huh?

---
from the git hub page
![github current version 2.1.7](http://i.imgur.com/36WUSFZ.png)

---
from my extensions page
![installed version is also 2.1.7](http://i.imgur.com/y2w6nvE.png)

---

**Comment by Zarggg** [comment]
Correct, 2.1.7 has been obsolete for a long time. @YePpHa has not yet published a new "stable" version. Until that time, please use the [Developer Version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version).
