### ISSUE TITLE
Playlist Hidden Somehow

### ISSUE THREAD

**Issue by gangsthub** [YePpHa/YouTubeCenter#1788]
![image](https://cloud.githubusercontent.com/assets/6775220/7553627/0304b8b8-f704-11e4-94f5-2121740430e5.png)

I have this problem with Chrome extension current version **(2.1.7)**.

Weirdest thing is that it appears when the content is being loaded, and disappears when the whole DOM is painted, leaving it's `div`'s height empty.

![image](https://cloud.githubusercontent.com/assets/6775220/7553633/4c7425ec-f704-11e4-9210-b99cd9e17a89.png)

Another example:

![image](https://cloud.githubusercontent.com/assets/6775220/7553651/416b7514-f705-11e4-89e3-29865b7a7b8b.png)
![image](https://cloud.githubusercontent.com/assets/6775220/7553655/5d6a83e0-f705-11e4-8fdc-2662a66367d4.png)

**Comment by ErdeFB** [comment]
2.1.7 is obsolete. Please update to the latest developer version for the time being.

**Comment by gangsthub** [comment]
I've upgraded to Developer Edition and I can say: it's solved.

**Comment by Yonezpt** [comment]
@gangsthub Then could you close your issues if they have been solved? Right below the comment box you have the Close issue button.

**Comment by gangsthub** [comment]
@Yonezpt thanks
