### ISSUE TITLE
Likes and dislikes colored bar on thumbnails will only show the default one

### ISSUE THREAD

**Issue by campaignsong** [YePpHa/YouTubeCenter#1789]
Enable Rating Bar = checked
Position= Bottom
Download data = at start of page
Visible = Always
Default color = whatever color
Likes color = blue
Dislikes color = red

It's stuck to the default color and it has been that way since the last 3 versions.

I want my blue and red back.

What can I do, please, thank you.

**Comment by Zarggg** [comment]
Changing the setting works for me. Did you refresh the page after changing your settings?

**Comment by campaignsong** [comment]
I always refresh it after any changes.

The "default" option will take over the likes and dislikes colors anyway. Why is it there?

**Comment by campaignsong** [comment]
I just downloaded v525 and still no changes.

Also, similar problem with the thumbnail rating count: both thumbs up and down show zero
likes and dislikes.

**Comment by Zarggg** [comment]
The "default" color bar (grey by default settings) will display if there are no likes or dislikes on a video, or the script is unable to load the like/dislike count for some reason.

**Comment by campaignsong** [comment]
Yeah, it now works! It was that API v3 that I had to check. I had no idea.

Thank you, much appreciated!
