### ISSUE TITLE
Animated thumbnails partially broken + too many HTML elements on them

### ISSUE THREAD

**Issue by mleyen** [YePpHa/YouTubeCenter#1791]
It's hard to show with a screenshot, but some animated thumbnails are broken.
When I hover over a thumb, it may skip one frame very quickly, then show the next one for the normal duration, or even just loop on the first 3 frames (not the same as legacy frames). When i unhover and hover again, it will work normally again.

Also, when the mouse leaves the thumbnail, it may be replaced with blankness rather than the original thumbnail. This seems to only be happening on sidebar recommendations, not on the My subscriptions page.

http://pastebin.com/4YXiavMc ← here's a Firebug log of an instance of the bug happening. I hovered over two thumbnails, left them, and they became blank.

As I used the Firebug inspector to investigate the glitch, I found this on one of the blank thumbnails : 
http://pastebin.com/9cLsPTQw
The attributes are just being re-added over and over instead of being replaced. This may be the cause of the previous bug – and in any case, this is not good news.

**Comment by dastefster** [comment]
Uhg I loggen on to report the same bug! My YTC no longer will display the the "likes/dislikes" in video thumbnails, even though my settings haven't changed, I still have Animations checked in settings. Weird thing is, it DOES display video quality,..but every video just displays "0-likes/0-dislikes" not matter how many the video actually has. I tried to show this in a screen shot the best I could 
![screen shot 2015-05-13 at 11 04 04 pm](https://cloud.githubusercontent.com/assets/10735136/7625959/d87c0d08-f9c4-11e4-8b16-833ecc3c16c2.png)

**Comment by Zarggg** [comment]
@dastefster: You need to explicitly enable API v3. For some reason, that option is not enabled by default. YouTube's API v2 (which YTC uses by default) is deprecated and no longer contains like/dislike data.

**Comment by SINE** [comment]
I have v3 active and the issue still exists.

**Comment by mleyen** [comment]
Supposedly solved by build 528, thank you vey much Yeppha !
