### ISSUE TITLE
[Build 525 + Firefox] YTC desactivates MSE Support in Firefox

### ISSUE THREAD

**Issue by Lebon14** [YePpHa/YouTubeCenter#1796]
Hey guys.
I noticed something while running YTC and Firefox 37.0.2. If I run YTC Build 525, I only get 360p and 720p available for videos. If I desactivate YTC, I get the who range of resolution: 144p, 240p, 360p, 480p, 720p30/720p60, 1080p30/1080p60. Other Youtube addon I'm running:
- Youtube Dark - 2015 (w/Stylish)
- Youtube Subscription Grid 1.11.2

Anybody else have this issue?
Thanks.

**Comment by Zarggg** [comment]
Ensure that "DASH Playback" is enabled in YTC's player settings.

**Comment by Lebon14** [comment]
That was it. That kind of sucks coz I liked to charge the whole video :-(

**Comment by Yonezpt** [comment]
@Lebon14 If your issue is solved could you close it? The "Close issue" button is located below the reply box.
