### ISSUE TITLE
Video doesn't fit to player window

### ISSUE THREAD

**Issue by ultimo01** [YePpHa/YouTubeCenter#1812]
Browser name: Firefox
Browser version: 37.0.2
YouTube Center version: Developer Version - Build #525
Addon type: Firefox extension

That how it looks in 720p player size:
Resolution 480p:
![480p](https://cloud.githubusercontent.com/assets/12449038/7637925/b60ab14a-fa71-11e4-9e4f-e831c520e1e3.png)
Resolution 720p (that how it should always look):
![720p](https://cloud.githubusercontent.com/assets/12449038/7637926/b6470b22-fa71-11e4-876c-a2de70983be2.png)
Resolution 1080p:
![1080p](https://cloud.githubusercontent.com/assets/12449038/7637927/b64a28ca-fa71-11e4-91ab-3144b5c36b53.png)

**Comment by Yonezpt** [comment]
That's a Firefox issue, not YTC. 

Either update Firefox to v38 (think this issue is fixed in that version) or got to `about:config` and search for `layers.offmainthreadcomposition.enabled` and change it to `true`.

**Comment by ultimo01** [comment]
Thanks, now everything works.

**Comment by TheCuza** [comment]
I'm using Firefox 38 and that config setting was already set to true for me, and every video looks like OP's top picture, regardless of resolution.

It's only with the HTML5 player and it wasn't like it earlier today. I'm guessing it's Youtube's fault.

**Comment by SuperSajuuk** [comment]
That's apparently a bug that was since fixed in YouTube Center. You should use the developer version if not using it already.

**Comment by Yonezpt** [comment]
@TheCuza see https://github.com/YePpHa/YouTubeCenter/issues/1844#issuecomment-106014318 because your issue is not the same as OP's
