### ISSUE TITLE
Addons mozilla has an older version of YTC

### ISSUE THREAD

**Issue by Pazitos10** [YePpHa/YouTubeCenter#1813]
I've noticed that the link to the current version (2.1.7) posted here: https://github.com/YePpHa/YouTubeCenter/wiki.
More precisely: https://addons.mozilla.org/en-us/firefox/addon/youtube-center/
Shows that the addon version is 2.1.0, and if I try to install it, it doesn't work. When I'm in youtube, the initial configuration never pops up and the configuration button is no longer there.
Firefox version: 37.0.2
There is another way to use the lastest version of YTC in Firefox?

**Comment by Zarggg** [comment]
2.1.7 is obsolete. Please use the [developer version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version) until a new stable build is released.

**Comment by Pazitos10** [comment]
Ok, I will install developer version and wait for new versions. Thanks!

**Comment by SINE** [comment]
Try Greasemonkey and install the Userscript (you can find it here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version)

**Comment by Pazitos10** [comment]
Thanks! I will keep that in mind if something goes wrong. By now, I installed .xpi file from here (dev version), and its working again.
