### ISSUE TITLE
Buffering stops randomly, ala DASH

### ISSUE THREAD

**Issue by elimccl** [YePpHa/YouTubeCenter#1818]
This began probably around developer build 520 or 519, but videos on youtube no longer auto-buffer correctly. Similarly to how buffering behaves when DASH playback is enabled, videos will buffer to a seemingly random point and then stop. The rest of the video will not begin to buffer until playback reaches that point in the timeline. (To be clear, DASH is indeed disabled when this is happening; no settings had changed between versions.)

Some videos will buffer entirely, while others may as well not be using youtube center at all, as they split the video into dozens of chunks. I have a poor internet connection, hence my need for YTC; I mention this because possibly the buffer is stopping due to a connection interruption, as far as I know, although that's a guess. Again, in prior versions, I personally had no issues at all.

**Comment by SINE** [comment]
I just can say that when I disable DASH, the whole video buffers entirely.

To get rid of any problem you have, please reset the YoutubeCenter settings, uninstall the AddOn, then restart your browser, install it again, restart the browser, and then disable DASH and then start a video to test it.

If you keep having the problem, provide the following infos:

- What version of the YoutubeCenter are you using (developer or stable, what version (on the bottom left in the settings)).
- What browser are you using? (+ Version)
- Are you using a Browser AddOn version or Userscript version of YouTube Center?

**Comment by elimccl** [comment]
Sadly, doing a complete wipe and reinstalling everything didn't do the trick.

I am running Developer Version - Build #525, which is the userscript version found at: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

Firefox version 37.0.2.

As mentioned, the problem has existed for me since at least build 520. I had thought since the builds had been released so frequently, it was a well known issue they'd been trying to fix, but I guess it's just me. Is there any way to roll back or download an older version of the developer builds? I searched for a couple of days but could never find the means.

**Comment by SINE** [comment]
Shut the browser, navigate to %APPDATA%\Mozilla\Firefox\Profiles\default\gm_scripts and delete all files where the name begins with "YouTube_Center_".

Also make sure to update your FF to the newest version (currently 38.0.1)

**Comment by elimccl** [comment]
Firefox is up to date, all cached or old versions of files deleted, and so on. Sadly, it did not work. Still randomly stops buffering in places.

I get the impression this a very specific problem to our connection, as we have to use an air to air ISP provider (transmitted via local dishes rather than over a wire). As a result, latency is very bad and full connection drops and timeouts are very common. Something about one of the updates seemed to exacerbate that, if I had to guess.

I suppose I'll just have to tolerate it, or rely on manually downloading the videos. Thanks for the help, regardless!

**Comment by Zarggg** [comment]
@elimccl: Please close this issue, as it does not seem to be related to YTC.
