### ISSUE TITLE
Youtube Center settings button (icon) 

### ISSUE THREAD

**Issue by Stacz13** [YePpHa/YouTubeCenter#1840]
I have a problem. After firefox upgrade (to version 38.0.1) settings button (icon) disappeared from you tube and I don't have access to settings. What should I do?

**Comment by SINE** [comment]
Do you use the Greasemonkey Script or the Firefox Add-On?
If it is the Add-on, uninstall it and use the Greasemonkey script.
If it's the Greasemonkey Userscript, re-install it (use the Developer Version you can grab here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version )

That didn't help? Uninstall the script, close Firefox, then:

In Windows, navigate to
%APPDATA%\Mozilla\Firefox\Profiles\PROFILENAME\gm_scripts
(replace PROFILENAME with your firefox profile name)
In that folder you will find multiple files that names start with:
YouTube_Center_Developer_Build
delete all of them.

Then restart your browser and re-install the script.

**Comment by Stacz13** [comment]
Thanks for help :)) For now everything is ok :)

**Comment by SINE** [comment]
You're welcome, please close the issue.
