### ISSUE TITLE
youtube center search and screen size

### ISSUE THREAD

**Issue by strawbery123** [YePpHa/YouTubeCenter#1843]
Can someone please help me and tell me how to get rid "search through" new option in the  youtube search bar and the player size to stay the same not to get large? Please. Thanks

**Comment by ireun** [comment]
You can set the desired size of the player in YTC settings, click on the cog in the upper right corner. And i don't get what is "search though" option. If you still got an issue please describe it better, and open a new one..

*Closing..*.
