### ISSUE TITLE
The video size is 720p, though the picture appears only on a part of it + AutoPlay is enabled although I've disabled it.

### ISSUE THREAD

**Issue by djsavta** [YePpHa/YouTubeCenter#1847]

**Comment by Zarggg** [comment]
Possibly related to #1844 ?

**Comment by djsavta** [comment]
Looks about the same error.
But this has been solved for me by installing the Dev build.
This has now returned with the latest Dev build update.

**Comment by AgEnT-x19** [comment]
I can confirm the problem.
It existed in version 2.1.7
I then moved to Dev builds and it was fixed.
Now it has returned.
YouTube is testing out a new player design and they have changed something over the past week. I think that's what causing the problem.

**Comment by ireun** [comment]
@djsavta Can you tell me if it still occurs? If Yes, please post in existing issues, to avoid duplicates.

Resizing bug: #1844
Auto-play not working: #1869

**Comment by AgEnT-x19** [comment]
@ireun 
It works fine with the new player
