### ISSUE TITLE
Video Player not resizing right

### ISSUE THREAD

**Issue by SlimSterling** [YePpHa/YouTubeCenter#1849]
When i go from default view to theater mode it causes the video to resize wrong were the video stays the same but the player is resized.

![imgur](https://i.imgur.com/Z3pUub2.png)

**Comment by andyb2** [comment]
Many posts on this already

**Comment by SlimSterling** [comment]
sorry i looked through a few pages of issues but didn't see anything

**Comment by andyb2** [comment]
Everything below this is mostly about this problem.

**Comment by WPettersson** [comment]
Both #1847 or #1844 discuss this problem.

**Comment by ireun** [comment]
Yup, a duplicate of #1844, please write there if the problem still occurs.
