### ISSUE TITLE
Only 360p and 720p quality selectable

### ISSUE THREAD

**Issue by ATA250** [YePpHa/YouTubeCenter#1850]
Was working fine for a few vids, now I only have 360p and 720p quality that can be selected, no other options.

Firefox 38.0.1
Dev build 525

**Comment by SuperSajuuk** [comment]
That is a symptom of users who disable DASH playback in the preferences.

**Comment by ATA250** [comment]
Great :( Disabling DASH was literally the only reason I wanted to use this for.

**Comment by SuperSajuuk** [comment]
DASH playback is actually pretty cool. I still don't get why people want to turn it off. :/

**Comment by ATA250** [comment]
My internet connection maxes out at about 1.5mbps is why.

**Comment by SuperSajuuk** [comment]
@ATA250 Not much of an excuse, because I also have about 1.5mbps (sometimes hitting 2mbps) and can buffer 720p60 without issues at all.

**Comment by ATA250** [comment]
I'm also one of 5 people using the connection at once :)

**Comment by Aolorn** [comment]
I concur. My Internet connection can get really slow and unstable so being able to preload just a few seconds of the video and having to preload everything from scratch everytime I want to replay the video or return to specific point used to be major pain in the backside.

**Comment by FichteFoll** [comment]
I have the same problem on FireFox 38.0.5 with DASH enabled, but only on my laptop. The problem appeared for all videos, until I finally found [this](http://superuser.com/a/903715/457075) fix. `media.mediasource.webm` was disabled for me and enabling it also made the [HTML5](https://www.youtube.com/html5) page show a check mark at VP9. However, some videos were still only watchable in 360p.

The only way I managed to fix this was to tell YTC to use "Flash" and not HTML, as you can't even switch to HTML5 on the youtube html5 page.

Video that worked after first fix: https://www.youtube.com/watch?v=sb9fHU4d3Ds
Video that required flash: https://www.youtube.com/watch?v=lki1y2wa820

**Comment by Zarggg** [comment]
@FichteFoll: Both videos work properly for me using the [experimental HTML5 player](http://youtube.com/testtube). 
Using the standard HTML5 player gives me a WebM video for your first link and an MP4 video for the second.

Curiously, the only encode using WebM/VP9 on the second video is in 360p in non-DASH format.

My guess is that your installation of Firefox is unable to properly load the HTML5 player, thereby excluding the 480p+ DASH streams. Again, the WebM encode for the second video is not a DASH stream, thus can be loaded by the Flash player (which doesn't even support DASH). YouTube still falls back to Flash if the HTML5 player fails to load for any reason.

**Comment by FichteFoll** [comment]
@Zarggg can you check if your `media.mediasource.webm` setting is set to true? The first video served a vp9 video 720p video after I did that while the second was only vp8 360p. Propably because, as you mentioned, it doesn't feature DASH Webm/VP9 videos for the other resolutions. Here's another video that seemingly has the same limitations: https://www.youtube.com/watch?v=qsQPEqPCtuk

**Comment by Zarggg** [comment]
Yes, that preference is set to `true`. When set to `false`, Firefox will not load WebM videos.

I generally use the beta versions, so I'm on 39b2 right now. I do not recall having any issues with WebM/VP9 when 38.0.5 was still in beta, but I don't think YouTube was preferring that format back then as much as they are now; the move to VP9 only started in April if I recall corrected.

Something strange seems to be going on, but I believe it is related to Firefox or YouTube, not YTC itself. As I was writing this comment, the HD options for the video you just linked disappeared and the only quality YouTube will give me with YTC disabled is 360p MP4.
