### ISSUE TITLE
No settings are applied to channels

### ISSUE THREAD

**Issue by Synetech** [YePpHa/YouTubeCenter#1855]
It has already been reported before that auto-play/buffer settings don’t work with channels, but in fact, *no* settings are being applied to channels.

Whenever I am on a user’s YouTube home page (e.g., [this one](https://www.youtube.com/user/numberphile)), the first video in the list will automatically start playing. Moreover, it will be using the HTML5 player even though I have set YTC to use “Aggressive Flash” for channels. Also, if I happen to want to watch that video and make it fullscreen, it will switch to HD even though I have set everything to use the lowest resolution. (Neither my system nor connection can handle HD, so switching back to SD is really difficult with the 100% CPU usage, but I don’t believe that Google understands or cares about that.)

**Comment by SuperSajuuk** [comment]
You should really be using the HTML5 player, Flash Player support will be removed in time on YouTube (it may start around the time that NPAPI support is disabled in Chrome 45). HTML5 has a benefit of allowing you to watch videos at higher frame rates and gives better statistical data when you use the "Stats for nerds" option, so I suggest switching over.

**Comment by Synetech** [comment]
> SuperSajuuk commented a day ago
> You should really be using the HTML5 player…  HTML5 has a benefit of…

It also has the “benefit” of automatically playing videos (and in HD no less), thus sucking up my limited bandwidth and completely hanging my system by pegging the CPU at 100%. ◔_◔

Like [most people](https://www.google.com/search?q=youtube+html5+site%3Aproductforums.google.com), I have no intention of using the HTML5 player [until it works better than the Flash player](https://productforums.google.com/d/msg/youtube/gtlrDPt_ypU/qalGtVYYzaIJ) (or at all).

It’s just yet another example (in a long list of examples) of Google fascistically ignoring user feedback and tyrannically telling us what to want and like. It takes people like Jeppe to wasting their time and effort to work around Google’s dictatorship to make life tolerable again.

**Comment by Synetech** [comment]
Oh, and I forgot to mention that I was using version 2.1.5. I upgraded to 2.1.7 and it seems to be working now, so I’ll close this, and thanks!

**Comment by Zarggg** [comment]
2.1.7 is obsolete. Please keep that in mind.

**Comment by Synetech** [comment]
Huh? ಠ_ఠ [It says 2.1.7 is the current version.](https://github.com/YePpHa/YouTubeCenter/wiki)

**Comment by Zarggg** [comment]
It does, and if we wanted to be pedantic we could say that it is the latest *stable* release. Unfortunately, there have been many changes on YouTube's end (and to Firefox, I believe) that break that version.

@YePpHa has been doing all bugfixes and updates on the Developer Version and has not yet released a new "stable" version. He has stated that he plans the next stable release to be 2.1.8, but none of us are sure when that is going to be, particularly given the fact that addons.mozilla.org is very slow to approve submitted extensions and the Chrome Web Store has decided to not accept this extension.
