### ISSUE TITLE
Problem with player

### ISSUE THREAD

**Issue by DaNTaF** [YePpHa/YouTubeCenter#1858]
Firefox 39 beta 1
YouTubeCenter  #525
![2015-05-29_17-00-59](https://cloud.githubusercontent.com/assets/9018485/7884190/c2875482-0624-11e5-91ba-741daf23e6fc.png)

**Comment by SuperSajuuk** [comment]
See #1844

**Comment by danilaml** [comment]
Same problem. Strange thing - I only noticed it after I updated ytc to latest build. Before it was working OK I think (was 505 version +-3). And refresh usually fixes it.

**Comment by MIC132** [comment]
Same problem on 525, refreshing does nothing to it unfortunately.

**Comment by rayman89** [comment]
Read the link provided on the second post. There are workarounds till it gets fixed.
