### ISSUE TITLE
Firefox will soon allow only signed extensions in Stable and Beta channels

### ISSUE THREAD

**Issue by mikhaelkh** [YePpHa/YouTubeCenter#1859]
More info [here](https://wiki.mozilla.org/Addons/Extension_Signing). I hope developer version will be signed and the stable version will be updated in FIrefox AMO.

**Comment by Long-Horse** [comment]
fucking hell Chrome did this and I switched to FF...Opera is a shitty/gimped version of Chrome since v13...I need to make my own browser...

**Comment by Pontiac76** [comment]
I hear you loud and clear LH.  FF has been doing crappy UI stuff, now
they're dictating what plugins I can use.  I tried their "Dev" version, and
3/4 of the addons aren't available because they're not 'certified' to run
with the dev version of FF.

**Comment by Piter432** [comment]
@Pontiac76 Mozilla will not dictate what extensions we can use. All
extensions must be only signed by Mozilla, if that extensions don't want to
be installed inside Mozilla Addons page. The Google's way for installing
extensions outside from their Web Store is crappy as hell, really.

**Comment by KamranMackey** [comment]
@Piter432 Google is not called The Google, they are just called Google. :stuck_out_tongue:

**Comment by mikhaelkh** [comment]
@KamranMackey, you can see "the" was adressed to "way", not "Google" ;) It's funny how people start discussing about their feelings and things that are appropriate to some forums, not GitHub though.

**Comment by rayman89** [comment]
Relax guys is not as natzi as it's made to sound. There will be always workarrounds or ways to disable it. They are jsut doing it so inexperienced users dont fall for scams. Also YTC has the script version that you can use that IMO is better than using the add-on.

**Comment by Piter432** [comment]
@rayman89 Uhm... Mozilla already announced that this will can't be disabled
in any way :P

**Comment by rayman89** [comment]
@Piter432 By about:config or command line no because add-ons can do that but in other ways it could be possible. Also firefox is always open source so there will be builds with that disabled by default.

**Comment by fredkilbourn** [comment]
Just install YTC in Greasemonkey in FF or Tampermonkey in Chrome.
