### ISSUE TITLE
YouTube Center not worked on last FireFox 38+

### ISSUE THREAD

**Issue by MayaLodd** [YePpHa/YouTubeCenter#1861]
YouTube Center not worked on last FireFox 38+ please FIX problem, nice addon!!!

**Comment by Zarggg** [comment]
I am currently using YTC Developer Version 525 in Firefox 38.0.5. If you are still using 2.1.7, that version is obsolete and you will need to update to the Developer Verison.

If you are using the Developer Version and it is still not working, you will need to be more specific with your issue.

**Comment by SINE** [comment]
The Add-On is outdated, try using the Userscript instead.
First, install GreaseMonkey: https://addons.mozilla.org/de/firefox/addon/greasemonkey/

Then, click on this link: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version
click on the link for "Userscript".

Please note that this is the "developer version", meaning it will have bugs and not work sometimes.

If it works, please close this issue.

**Comment by Chivas78** [comment]
wow thank you so much ! i've been looking all over the place for a working version. btw this works great on chrome. about to install it on firefox now. I've been using youtube center for a long time and everything else out there cant satisfy my need when it comes to YOUTUBE !

Please keep this beautiful userscript/extension updated.
Bloody aweomse, now ratings are back working again  :dart: :+1:
