### ISSUE TITLE
Country-flag downloadbuttons on comments broken randomly

### ISSUE THREAD

**Issue by SINE** [YePpHa/YouTubeCenter#1864]
Sometimes the download buttons for the countryflags next to the usernames on the comments on YouTube are broken.

They start looking like this:
![Image of broken Buttons](http://i.imgur.com/N26mK6T.jpg)

This happens randomly, reloading the website fixes it most of the time / or breaks it again.

YouTubeCenter Dev Build 525
Greasemonkey on Firefox 38.0.1
Windows 7 x64

**Comment by ireun** [comment]
Migrating all issues about country flags not working to one issue, check out issue number "1877".
