### ISSUE TITLE
Last YouTube Center Developer Build?

### ISSUE THREAD

**Issue by asd55** [YePpHa/YouTubeCenter#1867]
#525

**Comment by kaugnebulixo** [comment]
I am not exactly sure what you are talking about. You can download the latest one here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version but nowhere does it say what the latest version number is. You have to turn on the update checker to see what the latest dev version is.

**Comment by SuperSajuuk** [comment]
@YePpHa is probably just busy atm, updates come through as and when they can. If there's a new version, you'll see the notice on youtube to update.

**Comment by rayman89** [comment]
You can see the version number when you click on the script to install it or you can see it if you go to the script manager on your browser list of installed scripts or on the list of installed add-ons if you are using the add-on.

**Comment by ireun** [comment]
Also, you can look at recent commits, and see what's the build number in one of them. ;)
