### ISSUE TITLE
Videos not saving in history.

### ISSUE THREAD

**Issue by MIC132** [YePpHa/YouTubeCenter#1868]
I just noticed that videos that I watch while Youtube Center is active don't save to youtube history. I only have videos that I watched from my phone there, or ones when the addon was disabled.

Is this intended? I would like them to appear in history.

**Comment by Fofer** [comment]
Strange, my watched videos are appearing just fine here:   https://www.youtube.com/feed/history

Did you by any chance accidentally click "pause watch history?"  If so, click "resume watch history."

**Comment by MIC132** [comment]
No, the button says "Pause (...)" for me, so that's not it. Hmm, maybe it's some other addon, but I'm not using anything else youtube-related. Is it possible that and ad-blocking addon (uBlock Origin) could cause that?

**Comment by Fofer** [comment]
Anything's possible, I suppose. And yes, especially if it involves "tracking" web activity (which some ad blockers aim to block.)  So try it!  Turn off uBlock Origin, watch some YouTube videos, and see if they appear in your YT History.  

For what it's worth, I am also running the main uBlock project, with no ill effect here.  https://www.ublock.org/faq/

**Comment by MIC132** [comment]
It looks like it's neither uBlock, nor Youtube Center. But then what? The only other tracking/blocking-related addon I have is "Facebook disconnect" and it shouldn't do anything to youtube.

Well, anyway, I'm closing the issue, as it's not problem with Youtube Center.

**Comment by Piter432** [comment]
I think this is YouTube Center problem, but I don't know where in the code.

**Comment by MIC132** [comment]
Doubt it, as disabling Center didn't fix it for me.

**Comment by Fofer** [comment]
What about if you temporarily turn off all extensions, does it work then?  Or try another browser?

**Comment by MIC132** [comment]
I think I know what is causing it. I recently added some stuff to my hosts file, for blocking all sorts of bad sites. Maybe there was something in there that is causing it. Will have to check.
