### ISSUE TITLE
Add 'watch later' button back to new player

### ISSUE THREAD

**Issue by SnowGabe** [YePpHa/YouTubeCenter#1872]
YouTube removed the "watch later" button in the new transparent player. Can we get it back with YT Center?

![2015-06-03 19_34_31-fallout 4 - official trailer](https://cloud.githubusercontent.com/assets/11059234/7965770/5985e086-0a28-11e5-9e9e-4fba9a9d83c5.png)

**Comment by SnowGabe** [comment]
Has happened already.

**Comment by cg9999** [comment]
I don't see it yet. Where exactly should it be?
