### ISSUE TITLE
Video size bug?

### ISSUE THREAD

**Issue by dragons4life** [YePpHa/YouTubeCenter#1876]
<img src='http://i.imgur.com/AKdz3tQ.png'/>

**Comment by Chromelon** [comment]
I have the same issue.

**Comment by jasonycw** [comment]
This is not a new issue.
Same issue as #1873 #1849 and #1844

The only "temp solution" is to enable the new player from https://www.youtube.com/testtube

**Comment by Yonezpt** [comment]
To add more to what @jasonycw already said, follow the temporary fix suggestions in the previously posted related issue https://github.com/YePpHa/YouTubeCenter/issues/1844#issuecomment-106976683

**Comment by TetraSky** [comment]
Another solution would be to just disable video resize
Player > Player Size > Enable Resize (Untick)

**Comment by dragons4life** [comment]
Thanks ya'll, going to try them later on my pc.

**Comment by naobug** [comment]
I have this bug too.
But only when I allow "https://r14---sn-aigllnll.googlevideo.com" in Noscript.
If you block that URL in NoScript it correctly enlarges the video without that black area.

**Comment by ireun** [comment]
A duplicate of #1844
