### ISSUE TITLE
Feature Request: Option to View Comments in New Tab When Comments Are Othewise Disabled

### ISSUE THREAD

**Issue by PamboHambo** [YePpHa/YouTubeCenter#1886]
I untick "Enable comments" in YTC's settings, but there are occasions when I actually want to read the comments on a particular video. Would it be possible to have an option somewhere to load all the comments in a new tab/window even if the user has disabled them on the main player page?

Cheers :)

**Comment by q1k** [comment]
middle mouse click the All Comments link (right click open in new tab)
![clipboard02](https://cloud.githubusercontent.com/assets/7927176/8094866/00b03752-0fca-11e5-8cb3-b9fa119fae96.jpg)

**Comment by Yonezpt** [comment]
@PamboHambo When you disable "Enable comments" a new button should appear in the comments place, clicking on it will load the comments when you want to read them.

![ss](https://cloud.githubusercontent.com/assets/8498057/8096077/d4434b0c-0fc2-11e5-8c12-5f0112c9f6f0.png)

**Comment by PamboHambo** [comment]
I'm an idiot - I have uBlock installed, and it was blocking the "Load Comments" button.

Cheers guys, and apologies for the useless thread.

**Comment by SuperSajuuk** [comment]
@PamboHambo Don't forget to close the ticket! :)

**Comment by PamboHambo** [comment]
Haha sorry again, closed :)
