### ISSUE TITLE
Grid layout not appearing - Youtube Subs page

### ISSUE THREAD

**Issue by amheretohelpu** [YePpHa/YouTubeCenter#1889]
Hello, I am running the latest version of YouTube Center 2.1.7, but even though the box i checked for the grid layout option on the YouTube, My Subscriptions page, the grid layout doesn't appear.  

Instead it looks like what's shown here in the
![subs](https://cloud.githubusercontent.com/assets/12868916/8142970/9d455dc4-1162-11e5-9906-73c0fc2af309.png)
 screenshot.

**Comment by clontarfx** [comment]
Same here (using Chrome). Have tried uninstalling and re-installing both Tampermonkey and the script, no dice. Developer build works however I like having the show/hide toggle (and developer build has a bug where "watched" videos have a leftover YT menu button).

**Comment by amheretohelpu** [comment]
Do you think someone might get to this one?  It would be appreciated.  -Michael

**Comment by SuperSajuuk** [comment]
Use the developer version, 2.1.7 is not a stable build and miles from being the "latest" version.

**Comment by amheretohelpu** [comment]
Thank you for this recommendation.  Could you please tell me where to download the developer version from?

**Comment by SuperSajuuk** [comment]
@amheretohelpu It's linked on the wiki pages on the right side, but here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by amheretohelpu** [comment]
Thank you SuperSajuuk, your help is very much appreciated.  It does not appear that this particular solution has been effective.  When I opened the Youtube Subs page right after installing the developer version I get the following screen shot:

![image](https://cloud.githubusercontent.com/assets/12868916/8363335/32944794-1b4c-11e5-8499-9a1f297c5540.png)
![Uploading image.png…]()
