### ISSUE TITLE
something wierd is going on. bandwidth issue?

### ISSUE THREAD

**Issue by plaguewolf** [YePpHa/YouTubeCenter#1892]
ok let me first state that its doubly noticeable for me with my atrocious internet speeds, ie: 146KB/s

so when i load a video, the page begins to load fine, and youtubecenter isn't enabled at first, the "flash player" that youtube uses is there, but it only takes up ~80% of the black box where the video should be, then its like the page refreshes and youtube center loads properly, however both the original player (youtube) and the youtube center player are downloading the same video, or at least it appears to be.

in chrome i right click on the top bar beside tabs and open the task manager, and sort by descending bandwidth, and i have 2 sources downloading, one, the flash plugin, and the other is the page with the video. both are roughly splitting my bandwidth, with fluctuations up and down as they jockey for bandwidth.(ie: flash plugin ~60-70KB/s, YTC ~60-70KB/s) videos are loading at 360p, dash is disabled, player type is flash. using YTC dev build 525 (the non dev release no longer works, video loads and description/related videos are superimposed on top of the bottom of the player.

seriously considering uninstalling chrome, its complete BS that they are allowed to disable something i want to install. unacceptable behavior.

**Comment by TetraSky** [comment]
For the video not taking the entire screen
Disable this option in youtube Center : 
Player > Player Size > Enable resize

For the videos loading twice
The current version of youtube center doesn't work with the new changes to youtube. Get rid of Flash and use HTML5
change the following
Player > General > Player Type
To HTML5.
As youtube doesn't use Flash anymore, forcing Flash will cause two players, HTML5 and Flash, to download videos and playback at the same time/with a slight delay. The only solution right now is to use HTML5 exclusively.

**Comment by plaguewolf** [comment]
cool, thats what i figured was happening, as i had already switched the player type over to html5 and it started working better.
