### ISSUE TITLE
Just too few of these

### ISSUE THREAD

**Issue by Cuds** [YePpHa/YouTubeCenter#1896]
THANK YOU YEPPHA ET AL. I would literally stop watching YouTube if I YTC went away, it did for a while for me when i was making a transition between Magic Actions (just felt sketchy from the start) to YouTube Center :).  Anyways, just in case you guys don't get enough love from the community sucking your souls via time spent, I felt the need to shout out my love for all your hardwork and effort. *hugs* or if you feel uncomfortable *air hugs*

**Comment by ireun** [comment]
On behalf of @YePpHa - Thank You! :smile:
