### ISSUE TITLE
Firefox + YTC 525 video not filling entire space of video section

### ISSUE THREAD

**Issue by foss-** [YePpHa/YouTubeCenter#1900]
Firefox 38.0.5 + YTC dev 525
same with Firefox nightly from today

This happens when using a narrow browser window. Narrow not as in extremely narrow, for me on a 27" screen left screenhalf seems to be narrow enough to trigger this issue 100% reproducible. When increasing the browser window in width, the issue is gone and the video fills the entire video space as expected.

Would be great if you could look into this.

![ff 38 0 5 ytc dev 525](https://cloud.githubusercontent.com/assets/5708172/8207013/a172cd92-14fe-11e5-9995-d8d2a6112a40.jpg)

**Comment by LittleVulpix** [comment]
https://github.com/YePpHa/YouTubeCenter/issues/1873 , https://github.com/YePpHa/YouTubeCenter/issues/1876 , https://github.com/YePpHa/YouTubeCenter/issues/1858 , https://github.com/YePpHa/YouTubeCenter/issues/1849 , https://github.com/YePpHa/YouTubeCenter/issues/1847 , ..... they're all the same issue. YTC hasn't been updated in a while, author is taking a break most likely. Give it some time and use flash player until then, there are no issues in flash mode.

**Comment by SuperSajuuk** [comment]
@LittleVulpix Switching to Flash Player is not a solution as it simply masks the problem and prevents the user from watching high fps content.

@foss- Enable the new transparent player here: http://youtube.com/testtube

**Comment by foss-** [comment]
Hey all, sorry for posting a dupe then. That's the problem if only a single person maintains such a widely used add-on. Maybe one or two volunteers could step up and at least keep the bug tracker in shape. Since this report quickly received two comments there seems to be quite an active community.

Closing since this is a dupe. Links to open issues in first comment.

Flash will not live on my system. Time to get rid of that security issue...
Interestingly the new transparent player indeed does not have this problem. So waiting for Google to make that the new default would also solve this problem. I really like that change so can't wait until they do the roll-out. Hope it's not too far away.

**Comment by SnowGabe** [comment]
Also I won't use Flash because of security issues.
