### ISSUE TITLE
"Hide video" is misaligned.

### ISSUE THREAD

**Issue by GrahamFinch** [YePpHa/YouTubeCenter#1902]
I think YouTube made some changes to their site, because the "Hide video" option is way off to the left.

<img src="http://i.imgur.com/jlBkuO7.jpg">

Note the red arrow. That white box is where I have to click to remove the video from my subscriptions.

I have Pale Moon 25.5 and the latest Developer Version.

**Comment by Yonezpt** [comment]
Yes, YouTube recently changed the layout in the subscriptions page, specifically to that three dot menu and message.

**Comment by GrahamFinch** [comment]
Finally, the bug is fixed as of Developer Version 533!

Thank you!
