### ISSUE TITLE
4k/1080p not working

### ISSUE THREAD

**Issue by dramatech88** [YePpHa/YouTubeCenter#1904]
I have used this youtube center for a while and I started to notice no matter what I did either resetting all the settings or turning all auto resolution off or even forcing html5 nothing worked. I cannot play 1080p or 4k with youtube center. Neither developer build or the 2.0.1 version that shows up on the firefox addon list work. I miss all the features it comes with but as of now I can't use it because all I get is 720p and nothing else. Please come up with a fix thank you :D.

**Comment by Huskeyhund** [comment]
Same experience, when "DASH Playback" disabled.

**Comment by Zarggg** [comment]
DASH Playback is mandatory for 1080p or higher resolutions.

**Comment by Huskeyhund** [comment]
That's sad. Thx.

**Comment by SuperSajuuk** [comment]
DASH is actually quite useful. You should use it, rather than disabling it (I think the option to disable DASH should just be removed and people who want it should download an older version).

**Comment by dramatech88** [comment]
The only thing that sucks is when you have DASH enabled it doesn't load the video all the way so you can skip forward without reloading. That feature I like the most. Any way you can make that work with having DASH enabled?

**Comment by Zarggg** [comment]
No. The main purpose of DASH is the ability to load a stream in "chunks," both to conserve bandwidth (by not loading an entire HD stream at one time) and also to dynamically raise or lower the video quality if necessary to prevent stuttering or buffering.

**Comment by blackdragonbird** [comment]
Same here. Only 720p enabled whem Dashplayback is disabled. Any ETA when this bug will be corrected?

Thanks. =)

**Comment by ErdeFB** [comment]
It's not a bug so it won't be corrected. Please read the other messages in the issue report.
