### ISSUE TITLE
Flags are dead

### ISSUE THREAD

**Issue by asd55** [YePpHa/YouTubeCenter#1905]
no show the flags

http://i.imgur.com/fzMPq9j.png

**Comment by SuperSajuuk** [comment]
They've been like that for a while. There's really no sign that @YePpHa is actually doing anything about this script anymore, having been inactive for at least a month with no updates. There's so many bugs now that it's getting to the point where this script only showcases a broken YouTube.

**Comment by mzso** [comment]
Yep they are but I only remember them dying a few weeks ago. It was removed much earlier from Magic Actions.
Hopefully there's still a way to bring them back.

**Comment by Betsy25** [comment]
I really miss this option.

**Comment by ireun** [comment]
Migrating all issues about country flags not working to one issue, check out issue number "1877".
