### ISSUE TITLE
Video viewing problems and Subscription page problems

### ISSUE THREAD

**Issue by RamiIsABear** [YePpHa/YouTubeCenter#1907]
I don't know what this is called but the video is centered and the youtube page itself doesn't adjust to the new video, I tried playing with the size pixels but discovered that no matter what the size is, youtube treats the you tube center player as a separate player 

![2015-06-21 16_23_35-greenshot](https://cloud.githubusercontent.com/assets/5544689/8271994/6724d392-1832-11e5-8c33-1547fcf0565a.png)

Also my subscription page looks like this:
![2015-06-21 16_28_34-greenshot](https://cloud.githubusercontent.com/assets/5544689/8271999/9d78f70c-1832-11e5-8654-7c3cbb5c55e8.png)

Note: As you can see from the images there also seems to be a problem with displaying images other than video thumbnails (like channel images)
Here's a photo of a random channel:
![2015-06-21 16_31_24-greenshot](https://cloud.githubusercontent.com/assets/5544689/8272009/137d22a2-1833-11e5-8d1e-636e4a28646f.png)

**Comment by RamiIsABear** [comment]
I think an update has been long overdue to confront the issues that many users have been facing

**Comment by ModerateWinGuy** [comment]
I've been having those same issues for a while, so have just disabled it for the moment unfortunately.

**Comment by Yonezpt** [comment]
Try the developer version instead: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by RamiIsABear** [comment]
Guys Developer Version Works!!!, thank you for the link Yonezpt, it didn't solve the issue of the images but I think the problem is that I just need to restart google chrome or clear cookies or something in that area, even if it's not it's not a major problem anyway.
I'm also glad to say that now my subscription page works!

**Comment by ireun** [comment]
@RamiIsABear  Happy to hear that. ;) 

*Closing..*
