### ISSUE TITLE
Video Player not filling the entire player window

### ISSUE THREAD

**Issue by StormAssassin** [YePpHa/YouTubeCenter#1912]
Hey YePpHa can you fix this because it always show like this glitchy youtube
![untitled](https://cloud.githubusercontent.com/assets/13017452/8306514/1e0b755c-19eb-11e5-8cde-b38e6df44223.png)
I Hope You Can Fix IT !!

**Comment by KamranMackey** [comment]
That's a bug with the old HTML5 player, and won't be fixed until @YePpHa returns from his vacation or finishes his exams. However, that bug doesn't occur with YouTube's new HTML5 player, and you can enable it [here](https://youtube.com/testtube).

**Comment by SuperSajuuk** [comment]
Make sure you are also using the developer version and not the "stable" (I use that loosely because it's hardly a stable build anymore and should be removed from the wiki pages) build.

**Comment by StormAssassin** [comment]
https://github.com/KamranMackey it doesnt work i tried it do i have to use the HTML5 or flash?

**Comment by KamranMackey** [comment]
@StormAssassin HTML5.

**Comment by zmwangx** [comment]
@KamranMackey Hey, that was very helpful advice. Maybe it's worth adding to the top of README at the moment? I suppose many, if not the majority of users who have enabled player resizing are affected by this annoying issue.

**Comment by SuperSajuuk** [comment]
@zmwangx The Collaborators here do not make commits to the repository, simply due to how the code is built. If you mean the wiki, I don't know who is able to edit the pages.

**Comment by ireun** [comment]
@SuperSajuuk Every collaborator can do this, i will add something in a moment..

**Comment by SuperSajuuk** [comment]
@ireun Cool. Also, I see you've been busy labelling issues, which helps things to a degree. A lot of tickets should be closed, since there are tickets open that date to 2013, which obviously have either been fixed or ignored.

**Comment by zmwangx** [comment]
@ireun Actually I think this particular issue has been fixed (at least for me) in a recent build. That's with the old player, I mean.

**Comment by ireun** [comment]
@SuperSajuuk Done, I've added a big box on the left, it's visible on every page, though it's collapsing list of pages, but i think we can deal with that for now. ;) And yes, right about time to do that. ;)

@zmwangx Alright, if so i will close this issue, reopen it in case it would still occur. ;)
