### ISSUE TITLE
Embeds don't work

### ISSUE THREAD

**Issue by mallo15** [YePpHa/YouTubeCenter#1915]
~~No matter what I choose in embed options, any embeds are just black rectangles. If I right click->frame->open frame, it opens /embed/*vid id* but it's still a black rectangle. I have this issue for like, 2 months now but only today I realized it's a problem with YTCenter. I'm using SeaMonkey - basically Firefox but with built-in email client.~~

EDIT: Updating to developer version fixes the issue, but settings (like player color) don't work. =/

**Comment by ireun** [comment]
I will close this now, also about setting not being applied on embeds you can read #1225.
