### ISSUE TITLE
Playlist Auto-Play no longer functioning

### ISSUE THREAD

**Issue by RoboGigas** [YePpHa/YouTubeCenter#1919]
Running Dev 526 and Firefox 38.0.5. 
For a while now, my playlist autoplay has no longer functioned and I have to attribute this to Youtube Center. Not entirely certain what's causing it but with the script disabled, my playlists move on to the next video just fine but I haven't exactly fooled around with auto-play settings in the script so I can't give any exact idea on what causes/caused this to occur.

**Comment by PiZZAD0X** [comment]
Confirmed for this version and the last dev version. Also, this only happens with the HTML5 Player. Any combination of the playlist settings in the plugin and youtube will not yield playlist autoplay. Flash works fine, but... come on, who uses flash?

**Comment by Pontiac76** [comment]
I do as I've NEVER had an HTML video play longer than 20 minutes with
completely borking out.
