### ISSUE TITLE
720p@30FPS is highest res+fps I can use

### ISSUE THREAD

**Issue by Paradox949** [YePpHa/YouTubeCenter#1920]
The only other option is 360p@30FPS. This is with the old HTML5 player, and the new HTML5 player, which apparently supports 2160p@60FPS, but as I can't access it, it is currently an okay UI update. 

Any ideas on why this is?

**Comment by ErdeFB** [comment]
Please make sure you have DASH playback enabled in the settings.

**Comment by Paradox949** [comment]
That is slightly odd as having DASH disabled before this update was fine. 

I can't complain as enabling it works.

**Comment by ErdeFB** [comment]
It would be rather odd if it indeed had worked as you claimed as to my understanding YouTube has not offered video streams in those resolutions with non-DASH format for the longest time to my knowledge, but glad to hear you got the issue solved regardless.
