### ISSUE TITLE
Safari Extension automatic build "failed"

### ISSUE THREAD

**Issue by pawi** [YePpHa/YouTubeCenter#1924]
The Safari extension is build but extension creation itself (compression & signing) failed:
You can verify by review the directory listing: 
https://github.com/YePpHa/YouTubeCenter/tree/master/dist

**Comment by nihj09** [comment]
I have the same problem.  I go to youtube.com on safari 8.0.7 and it shows a dialog message at the top that a new developer build #526 is available. When I download and install it youtubecenter still shows version #525 as the current version. Youtube.com continues to show the same dialog message at the top.

**Comment by Ello2003** [comment]
Same probs as nih09, i have no idea how to build the safari folder one, but the actual extension download was updated 2 months ago hence the 525 build i'm assuming

**Comment by YePpHa** [comment]
Should be fixed.

**Comment by pawi** [comment]
Thanks, the plugin itself is updated now.
Please mind that in the Safari extension pane the plugin is labeld as YouTube Center Developer Build 525. The plugin itself is right now build 527.
![bildschirmfoto 2015-07-05 um 09 51 18](https://cloud.githubusercontent.com/assets/608692/8510796/66c5caf4-22fb-11e5-8928-b416a0ce55d0.png)
