### ISSUE TITLE
Build #526 seems to report itself als #525

### ISSUE THREAD

**Issue by Helmi** [YePpHa/YouTubeCenter#1926]
Hi,

the actual dev build seems to report itself a wrong version. It shows up as 526 in the extension panel but on youtube the message appears telling i should install a new dev build, in the settings it shows 525.

Not a big deal but though i'll report it.

**Comment by LiamBM** [comment]
Same thing happening on safari. I keep downloading the new dev build 256, however it shows up as 525. Once again, not a big deal, just something to note.

**Comment by rdamiano** [comment]
Does 526 even fix anything? Youtube Center is completely unusable on Firefox as of one of the recent FF updates. Memory leak or something.

**Comment by harveyadcock** [comment]
Yeah, memory leaks are really killing the experience in Safari. Don't know whether 526 addresses it or any of the other bugs as I've tried multiple times to install it without success - doesn't show as 526 in YTC settings or Safari->Preferences->Extensions. Have tried completely uninstalling and reinstalling with no effect.

**Comment by Ello2003** [comment]
I can't seem to install 526 in safari at all!  Any ideas?  I click on the latest dev build but its still 525.  In the dist folder it shows as updated 2 months ago but a folder with 3 files in, not sure how to build/compile this or if this is actual tech lingo for it?

**Comment by YePpHa** [comment]
Safari should be built again.

**Comment by Helmi** [comment]
And Chrome too
