### ISSUE TITLE
Youtube center ruins layout of subbed chennel's frontpage

### ISSUE THREAD

**Issue by fireattack** [YePpHa/YouTubeCenter#1927]
All default settings.

You need to be logged in and subscribed this channel to see this problem (otherwise "what to watch next" won't appear).

With YC:

![qq 20150703223421](https://cloud.githubusercontent.com/assets/4130991/8506332/27908fb8-21d4-11e5-837d-15431afdb584.png)

WIthout YC:

![qq 20150703223435](https://cloud.githubusercontent.com/assets/4130991/8506341/c5f8cc7e-21d4-11e5-9a24-982500be2362.png)

**Comment by Nuriell** [comment]
It just make the title of the first video visible, is not a big problem but it can do better by adding the video name on the right of the original informations below the video.

**Comment by fireattack** [comment]
Do you mean invisible? Anyway I agree with you it's not a big deal, but still there is no reason to change the layout. especially then it lost some information for users :/
