### ISSUE TITLE
Grid Subscriptions not working after update

### ISSUE THREAD

**Issue by jrod716** [YePpHa/YouTubeCenter#1930]
I have an issue with the grid subscriptions after the recent changes made to the developer version 527.  The odd thing is that the extension works perfectly in incognito mode for chrome. (see picture).  I have disabled any extensions that are different between the regular and incognito mode browsers, but I cannot seem to fix this issue.  If anyone has a solution, I would be grateful.  Thank you.
![yt issue 2](https://cloud.githubusercontent.com/assets/13113887/8562377/4f3b921c-24f7-11e5-9aa3-5fd21ec3e6f6.JPG)

**Comment by ireun** [comment]
It's working for me on Chrome, so i would recomend wiping cache..

**Comment by jrod716** [comment]
Thank you @ireun that worked.  I guess sometimes scary looking bugs can be solved with simple fixes.
