### ISSUE TITLE
Can't get likes/dislikes to show up since API changes.

### ISSUE THREAD

**Issue by AndrewRJ** [YePpHa/YouTubeCenter#1933]
I can't figure out why either. Whether I use a key or not the likes/dislikes won't show up. When I change the setting to only show them when I hover over thumbnails I get a "connection failed" message. Strangely enough it was working on my laptop with the same developer version. But since the recent updates to the dev version it stopped working on the laptop as well.

**Comment by AndrewRJ** [comment]
Just for the record this issue isn't the same as likes disappearing with a page refresh. This is regarding the likes/dislikes that you can have show up on the thumbnail so you know beforehand how many likes/dislikes the video has.

**Comment by ireun** [comment]
Right, sorry for that, though someone said that it works, that's why I've closed it, at least conditionally. ;)

**Comment by AndrewRJ** [comment]
I had it working on Chrome but then it stopped as well. I'm on Firefox 39 right now. I don't know what the cause could be. I've tried settings from another computer, I've even tried uninstalling, removing all traces of YTC and installing fresh and that didn't do the trick either. Just still getting "connection failed".

**Comment by Shem13** [comment]
Noscript or some other script blocking addon might be the problem.

**Comment by AndrewRJ** [comment]
Holy crap I feel stupid! Thank you Shem! Turns out NoScript was blocking googleapis.com. As soon as I allowed it, the likes/dislikes showed up on the thumbnail.
