### ISSUE TITLE
gear icon on right @ you tube page no longer there - where are settings menu?

### ISSUE THREAD

**Issue by hwrdmltn** [YePpHa/YouTubeCenter#1942]
What happened to the settings gear icon on right of the you tube page and all the oodles of settings that were possible with earlier versions of youtube center?

How do I access the menu (and as others pointed out, auto-play off does not work anymore)

**Comment by hwrdmltn** [comment]
Using Firefox 39 and YTC 2.1.0.1

**Comment by Cnuut** [comment]
use the dev version! 2.1.0.1 is really old and outdated
https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by ireun** [comment]
Yup, use the DEV builds..

**Comment by hwrdmltn** [comment]
Thanks much for the heads-up! Works again but does this mean that auto-update does not work anymore? If 2.1.0.1 is very old, then FF and/or an update should disable it instead of leading me to believe that I am at the latest version...no?
