### ISSUE TITLE
Prevent auto-load broken

### ISSUE THREAD

**Issue by rayman89** [YePpHa/YouTubeCenter#1943]
Prevent auto-load makes the video unloadable after today's update.

**Comment by ireun** [comment]
@rayman89 Have you tried searching for similar issues? I would recomend that, i'm sure there is already an issue like this one (#1898), please post a comment there and close this issue. Thanks!

**Comment by rayman89** [comment]
prevent auto play =/= prevent auto load but we can use the old topic for both if they have the same cause.

**Comment by ireun** [comment]
Issue that I've referenced is about auto-buffer, which I think is the same as auto-load. If you are talking about something else please describe it better.

**Comment by rayman89** [comment]
auto buffer is  auto pause that means the video will load (star buffering automatically) but it'll be paused. Prevent auto load will make the video not load and only start buffering when you click on it.

**Comment by ireun** [comment]
Dafuq am I reading..

Preventing auto-play = the video will be paused.
Preventing auto-buffer = the video will not be downloading itself, unless you start playing it. And this is also called preventing auto-load.

And i still have no idea what is you issue. @Yonezpt  come over here, please. ._.

**Comment by Yonezpt** [comment]
Auto-buffer = Auto-load, both mean the same thing since buffering is the process of loading new data.

Auto-play is different, it can prevent the video from loading and playing completely (cued mode) or just from playing (video is paused as soon as it tries to play on first load), depending on the method YePpHa is using.
