### ISSUE TITLE
Incorrect player ratio

### ISSUE THREAD

**Issue by Brottweiler** [YePpHa/YouTubeCenter#1945]
I think Youtube must just have pushed some update that made this all wonky suddenly;

![image](https://cloud.githubusercontent.com/assets/1613137/8725330/ec1c45d0-2bd3-11e5-9152-abf325742156.png)

**Comment by baardstra** [comment]
browser: chrome
just after 1600(CEST) it changed.
i'm using the latest DEV build 528 with tampermonkey, I tested it with and without browser hardware acceleration and both do nothing.

fullscreen does show the correct image.

**Comment by Eisys** [comment]
Same problem here. Latest Dev build, using Tampermonkey on Chrome Version 43.0.2357.134 m (64-bit)

**Comment by drickerby** [comment]
Yeah this has only just started happening for me. Youtube must be messing around with things again.

**Comment by SnowGabe** [comment]
@drickerby Same specifications and issue here.

**Comment by 1112e** [comment]
Yup, same thing in both Firefox and chome
