### ISSUE TITLE
Missing resolutions

### ISSUE THREAD

**Issue by Atulin** [YePpHa/YouTubeCenter#1952]
![1080_ytc](https://cloud.githubusercontent.com/assets/11233299/8746270/ee6f5552-2c87-11e5-9ce0-b48a5f3e6de3.png)
![720_ytc](https://cloud.githubusercontent.com/assets/11233299/8746271/ee6fe918-2c87-11e5-9f0c-822ce35ba5ff.png)

With YTC enabled: only 720p and 360p are available.
With YTC disabled: 1080p, 720p, 480p, 360p, 240p and 144p are available.

Mozilla Firefox, up to date

Problem occurs with both: Firefox extension, and Greasomonkey script

**Comment by Yonezpt** [comment]
Did you disable DASH playback? Because this is exactly what happens when you disable DASH: https://github.com/YePpHa/YouTubeCenter/wiki/Features#DASH_Playback

**Comment by Atulin** [comment]
Yes, looks like I did. Well, the issue is solved then.

Thanks for the help.
