### ISSUE TITLE
video ads shown despite option to not show em being on

### ISSUE THREAD

**Issue by Owyn** [YePpHa/YouTubeCenter#1953]
https://www.youtube.com/watch?v=0n5RTCh0vT4
autoplayed from previous video and saw a video add for some seconds before I could click "skip it", then in next video (https://www.youtube.com/watch?v=-mcb8Ysf-NQ) I saw a banner add.
![ad](https://cloud.githubusercontent.com/assets/1309656/8748576/0fc48de6-2ca4-11e5-85e6-928ca84b9514.jpg)

was playing in fullscrean, exiting it flickers a page for a while then gets rid of ads,
here's the debug log: https://gist.github.com/04d4653e81479e3b07a2 

youtube center beta (latest, just downloaded)

**Comment by Yonezpt** [comment]
From what I could see, YTC is simply not able to block ads during fullscreen due to the way the players fetch the new information from the server without changing pages (the flash player uses its own internal coms, the html5 uses a different method).
