### ISSUE TITLE
Subscriptions page completely broken

### ISSUE THREAD

**Issue by MIC132** [YePpHa/YouTubeCenter#1958]
Subscriptions page looks like this:

![2015-07-17 20_19_00-subscriptions](https://cloud.githubusercontent.com/assets/5782727/8754085/434d857e-2cc1-11e5-9866-399ba1b9cfa4.jpg)

Yesterday it was all good.
529 build.

**Comment by ireun** [comment]
Please read #1940. And tell if it would fix it.. If it would, please close this issue. :)

**Comment by MIC132** [comment]
Seems like clearing cookies did fix it. Thanks.

**Comment by ireun** [comment]
No problem! ;)
