### ISSUE TITLE
Grid Subscriptions option leads to very strange layout

### ISSUE THREAD

**Issue by tylendel** [YePpHa/YouTubeCenter#1964]
With it off, my subscriptions seem to already be in a grid with sections for "Today", "Last Week", etc (maybe youtube changed something).  Turning it on does some weird, wild stuff to the layout, giving me some arrows on the right side similar to the "What to Watch" section, while it also seems to attempt to make the grid behind it all.  Using Firefox 39 on Linux, YouTube Center Developer Version - Build 531

Edit: Build with (#) in front was linking to issue 531, removed the (#).

**Comment by ireun** [comment]
Can you please try clearing cache and cookies, also post a screenshot.

**Comment by tylendel** [comment]
Cleared cache and cookies, disabled all other addons.
![firefox_weird](https://cloud.githubusercontent.com/assets/857363/8785954/4d74b092-2ef9-11e5-9317-825e2726a163.png)

**Comment by Yonezpt** [comment]
YouTube is rolling a new subscription layout. Well, they are actually reverting it to the grid layout: https://www.reddit.com/r/youtube/comments/3dtt7n/youtube_just_updated_the_subscriptions_feed/

This might be the cause of your issue. Disable YTC and check your subscription feed, see if it stays in Grid layout.

**Comment by tylendel** [comment]
I guess I could have made it more clear.  It works fine with the grid subscriptions option turned off, and it is in a grid with it turned off.  So I don't need to disable the addon, just turn off the option.  I thought I'd mention it here since it may not be a necessary option anymore.

**Comment by Yonezpt** [comment]
So you are being served the new subscription layout that YouTube is testing. Thanks for letting us know, it might help others with the same problem.

**Comment by tylendel** [comment]
Of course today I am not being served the new layout, and I needed the option again.

**Comment by Brottweiler** [comment]
Old bug I think that doesn't happen anymore, instead there's this bug https://github.com/YePpHa/YouTubeCenter/issues/2064.
