### ISSUE TITLE
YTC data folder location

### ISSUE THREAD

**Issue by Dol-phin** [YePpHa/YouTubeCenter#1969]
Where does YouTube Center userscript store settings? I had to refresh my Firefox installation because of performance issues and naturally I don't want to move the whole "old Firefox" folder back. 
I copied the whole profile directory/gm_scripts/ folder, no success.

I haven't exported YTC settings, but I doubt that's necessary.
I'm using Greasemonkey.

This isn't in the FAQ.

**Comment by ireun** [comment]
You should ask where user scripts keeps their data.. And my guess would be somewhere in AppData, but try searching for that in Google.
