### ISSUE TITLE
HTML5 Player Issue in Safari

### ISSUE THREAD

**Issue by neil94** [YePpHa/YouTubeCenter#1970]
Hey guys,

I have an issue when I enable the "Enable resize" option under "Player Size". The layout of the page goes all crazy. I have also tested out all the pre-loaded player sizes, and they all seem to be affecting the layout in similar ways. I have decided to turn off this option for the time being.
This is what it looks like when I have the option enabled:
![screen shot 2015-07-22 at 6 39 34 pm](https://cloud.githubusercontent.com/assets/13449174/8822039/c0f3309a-30a5-11e5-860f-2fdec39303f7.png)
________________________________________________________________________

I also have another issue relating to the "Lights off" feature. Whenever I turn the lights off, a black box appears under the video player, pushing the rest of the page contents down:
![screen shot 2015-07-22 at 6 47 33 pm](https://cloud.githubusercontent.com/assets/13449174/8822041/c18189ee-30a5-11e5-91b4-c27480f91e1b.png)
It does not happen all the time (it is quite random)

**Comment by evliu** [comment]
+1 same issue for me

**Comment by Yonezpt** [comment]
@neil94 @evliu Are you using the latest developer version? You can download it from here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

However, the Safari extension seems to be in need of a correction, see #1948, so I'd suggest using the userscript version instead with the Tampermonkey extension

**Comment by evliu** [comment]
Oh got it, sorry I forgot to test against the dev version. just discovered this extension yesterday. i'll try out your suggestions

**Comment by evliu** [comment]
works well with the userscript. i'll be sticking with that instead!

**Comment by neil94** [comment]
@Yonezpt The userscript works perfectly, thank you for your help!
