### ISSUE TITLE
Rating bar not shown

### ISSUE THREAD

**Issue by SammysHP** [YePpHa/YouTubeCenter#1974]
I'm using developer version 531 (as addon version) and my own API key, but the rating bar is not shown. I can see few requests logged in the developer console, but only 9 instead of 500+ expected.

I've reset the configuration of YouTubeCenter, no luck. I tried all three possible triggers for loading the rating (onload, scroll, hover), nothing.

**Comment by Long-Horse** [comment]
same

**Comment by mrjpaxton** [comment]
I can see the rating bar just fine now. Try going to Settings > UI > Placement then click Move Elements, see if you can find it there. You can also try going to the Rating Bar tab in UI, enable and disable it, or export and save your settings, reset to default settings and try that. If it works, then it's a settings problem.

**Comment by SammysHP** [comment]
> I've reset the configuration of YouTubeCenter, no luck.

**Comment by SammysHP** [comment]
Damn! www.googleapis.com was not whitelisted in NoScript.
