### ISSUE TITLE
Can't install dev Version Safari

### ISSUE THREAD

**Issue by casiej** [YePpHa/YouTubeCenter#1975]
I can't install the most recent dev version on my macbook 10.10.5.

<img width="425" alt="screen shot 2015-07-27 at 14 58 17" src="https://cloud.githubusercontent.com/assets/373753/8906564/fd08892c-346f-11e5-88c5-24e8107816ef.png">

<img width="808" alt="screen shot 2015-07-27 at 14 58 00" src="https://cloud.githubusercontent.com/assets/373753/8906584/2cc355fc-3470-11e5-8cee-afd63fe5de0d.png">

**Comment by SuperSajuuk** [comment]
See #1948 for more information.
