### ISSUE TITLE
When will the safari dev build be fixed?

### ISSUE THREAD

**Issue by LiamBM** [YePpHa/YouTubeCenter#1976]
haven't been able to use safari in ages now due to the dev extension not installing. Any chance it will be fixed soon?

**Comment by LiamBM** [comment]
Thanks for that great answer

**Comment by ireun** [comment]
No problem, no one knows that, also, a good habit is to not ask for ETA.

**Comment by LiamBM** [comment]
Alright, my bad. Il take note.
