### ISSUE TITLE
Translation issue PT-BR

### ISSUE THREAD

**Issue by tiagodamian** [YePpHa/YouTubeCenter#1978]
In Player > Auto Play > Prevent Tab Auto-Play  the string is translated as: 
"Impedir reprodução automática na aba?"
Which dosent explain the function of the markbox, a more correct tanslation would be:

"Impedir reprodução automática nas abas desfocadas"

which would in itself be: prevent autoplay on unfocused tabs.

**Comment by ireun** [comment]
You can correct it via Crowdin, look here.. :)

https://crowdin.com/project/youtube-center
