### ISSUE TITLE
Subscriptions show in small frame

### ISSUE THREAD

**Issue by User-47186985** [YePpHa/YouTubeCenter#1983]
When I upgraded to Windows 10, this problem appeared. When the add-on is disabled, it works fine. I'm using Firefox 39 and the latest dev build of YT Center.
![capture](https://cloud.githubusercontent.com/assets/7759619/9021609/6b29214e-384b-11e5-889c-40eddfbf5412.PNG)

**Comment by Tobblish** [comment]
Have the same issue in Chrome but works fine in Firefox.
Both running Developer Version - Build #531 with the exact same settings and account.

**Comment by ireun** [comment]
Try clearing cache and cookies..

**Comment by Tobblish** [comment]
That actually worked which is odd since this was a clean install of Windows o0
Thx

**Comment by Yonezpt** [comment]
YouTube is testing the grid layout for the subscriptions (yes they are considering reverting the design to how it was before), this is being applied via cookies. When you cleared yours it removed the cookie that enabled their new grid layout test, which is very likely creating conflicts with YTC.
