### ISSUE TITLE
Unable to install dev version

### ISSUE THREAD

**Issue by GrapeCode** [YePpHa/YouTubeCenter#1987]
<img width="532" alt="screen shot 2015-08-03 at 1 36 34 pm" src="https://cloud.githubusercontent.com/assets/8679670/9047154/c441117a-39e4-11e5-848f-2e95bb9311f4.png">

**Comment by c010rb1indusa** [comment]
I'm having the same issues. Latest dev build. Safari Version 8.0.7 (10600.7.12)
