### ISSUE TITLE
Don't shows the country's flag in the comments

### ISSUE THREAD

**Issue by Hobbix** [YePpHa/YouTubeCenter#1988]
Don't shows the country's flag in the comments.
![555](https://cloud.githubusercontent.com/assets/8199105/9050784/adba2aec-3a5a-11e5-906d-4c5759cc8cce.png)

**Comment by Zarggg** [comment]
As per @YePpHa on #1877:
> I have switched everything from the v2 API to v3 API as the v2 API can't be called anymore. One thing I noticed very early on in my implementation is that no country information is returned with the v3 API as a lot of you have noticed.

**Comment by ireun** [comment]
New API doesn't allow us to check country of a user, thus cannot be repaired.. Closing..
