### ISSUE TITLE
Issue with non-DASH buffering (video "de-buffers" when skipping)

### ISSUE THREAD

**Issue by Kupursk** [YePpHa/YouTubeCenter#1993]
Hi, I've been trying out this extension mainly because I want to get rid of DASH on youtube. It's looking promising but I'm having this issue.

I've disabled DASH in the extension and switched to Flash mode (as apparently non-DASH doesn't work with HTML5). The videos buffer all the way to the end, and I can watch them from start to finish without problem. So far, so good...

However, if I try to skip (in the progress bar) to a point later or earlier in the video, sometimes it will do it correctly and just play the buffered video from there, but very often it will "de-buffer" the video and start loading everything again from that point on as though it had never loaded the video to start with.

Is there a way to avoid this by fiddling with the options?

Because this sort of defeats the purpose of the addon for me, as it ends up re-buffering the video all the time anyway.

Note: If the addon is turned off and DASH is back on, this doesn't happen. As long as the chunks of the video are buffered, I can skip forward and back anywhere throughout the already-buffered parts and everything that was already loaded remains loaded.

Note2: I tried enabling Custom Buffer with different buffer sizes too. Don't know exactly what this does but in any case it didn't help either.

Thank you.

**Comment by Zarggg** [comment]
Please be aware that DASH is now a central feature and streaming method used by YouTube. By intentionally disabling DASH, you are limiting what playback options are available to you.

Using DASH, YouTube buffers videos in chunks. Without DASH, whenever you change the playback position, the player must recalculate where to begin streaming the video from the source file. This can (and does, more often than not) cause you to lose whatever buffer you had built up before.

**Comment by LevyWilson** [comment]
This has been an issue for me since the first day I downloaded YTC. Either it's something the devs can't fix, since it's been like this for so long, or perhaps something is broken?

**Comment by Yonezpt** [comment]
This is an issue with YouTube ever since they introduced DASH playback, it is not something YTC is causing nor can it change.

**Comment by ireun** [comment]
Than I will close this issue. ;)
