### ISSUE TITLE
Safari Dev Version Broken

### ISSUE THREAD

**Issue by Daniel0808** [YePpHa/YouTubeCenter#2000]
The Dev version of this extension failed to install on Safari on OS X Yosemite and it gives a error message saying:
<img width="420" alt="youtubecenterdev safarifail" src="https://cloud.githubusercontent.com/assets/13753041/9206048/831fa06a-405d-11e5-82a2-74011c80b406.png">

The old 2.17 version installs properly but is totally broken.

**Comment by martimarkov** [comment]
+1

**Comment by Yonezpt** [comment]
This has already been posted before: https://github.com/YePpHa/YouTubeCenter/issues/1948#issuecomment-122545175

For now use the userscript version with Tampermonkey.
