### ISSUE TITLE
Grid layout problem

### ISSUE THREAD

**Issue by jasonycw** [YePpHa/YouTubeCenter#2001]
Today, YouTube seems break the YTC grid layout again on Chrome 44.0.2403.130 m
![2015-08-12 23_03_39-subscriptions](https://cloud.githubusercontent.com/assets/4518597/9227699/779b849e-4147-11e5-9936-2ae288d01da2.png)

Also, on Windows 7 Firefox 40, grid layout is bugged
![2015-08-12 23_04_44-subscriptions](https://cloud.githubusercontent.com/assets/4518597/9227693/6fc0637a-4147-11e5-9d2b-33a81d86699b.png)
While this not happen on Windows 10 Firefox 40

**Comment by Yonezpt** [comment]
YouTube is currently testing a reversion to the previous Grid layout, you very likely received it. Delete the VISITOR_INFO_LIVE cookie so that it returns the default layout which does not conflict with the test.

**Comment by jasonycw** [comment]
I don't have VISITOR_INFO_LIVE but VISITOR_INFO1_LIVE 
Removing it doesn't help

**Comment by jasonycw** [comment]
Clicked the wrong button, not close yet, sorry

**Comment by Yonezpt** [comment]
Yes, I can see that it is not what I suspected, it is a recent CSS change YouTube shipped.

@YePpHa rule `#browse-items-primary .item-section > li > .yt-lockup-tile, #browse-items-primary .item-section > li > .multirow-shelf, .browse-list-item-container.feed-item-container.branded-page-box, .compact-shelf.branded-page-box, .c4-featured-content.branded-page-box` has `width: calc(100% - 36px)`, changing it to `initial` seems to work for me.

**Comment by Yonezpt** [comment]
@jasonycw Have youy checked for the cookie in Firefox as well? That screenshot shows a very different issue than the one in your first screenshot, which is very similar to the conflict with the new Grid layout YouTube is testing.

**Comment by jasonycw** [comment]
no VISITOR_INFO_LIVE but VISITOR_INFO1_LIVE in Firefox 40
Removing it makes grid work again, but same as Chrome, the margin between thumbnails all gone

**Comment by Yonezpt** [comment]
Yes, forgot the `1`. As for the margins, that is what needs to be fixed for now.

**Comment by gopego** [comment]
How to delete cookies??

**Comment by jasonycw** [comment]
http://lmgtfy.com/?q=Chrome+delete+cookie

**Comment by Brottweiler** [comment]
Looks similar to https://github.com/YePpHa/YouTubeCenter/issues/2064, but I think this is older and doesn't seem to be the bug that happens now.

**Comment by ErdeFB** [comment]
@Brottweiler This is not the same issue, but seems to be irrelevant issue report as of now nevertheless. The new problem is caused by YouTube implementing subscription grid layout themselves.
