### ISSUE TITLE
Is it time to drop YTC?

### ISSUE THREAD

**Issue by GrahamFinch** [YePpHa/YouTubeCenter#2002]
It seems like YTC is getting worse with each update. Every time a new version comes out, none of the bugs we ask to be repaired are fixed. Instead, they keep adding new pointless features and even MORE bugs become introduced.

https://github.com/YePpHa/YouTubeCenter/issues/1986
https://github.com/YePpHa/YouTubeCenter/issues/1902
https://github.com/YePpHa/YouTubeCenter/issues/1568

None of these issues have been fixed over the past 30+ updates over a period of five months.

I'm seriously considering dropping YTC if they're not going to start cleaning out persistent bugs.

**Comment by Pontiac76** [comment]
So do so?

**Comment by Trueffel** [comment]
Are you serious? Those are super small issues in a quite big script that does a shit tonne and works on 99% of teh features. How is "they", which afaik is one person, supposed to keep up with teh constant stupid changes YT does and where does this entitlement come from??

**Comment by ErdeFB** [comment]
Please keep criticism constructive and on-topic. This is a issue tracker and not a place to vent your frustration. I understand that development is currently slow and this can be frustrating, but there is only one person who mainly does the development and opening issues like this won't help bring any change to the problem. 

Thanks.
