### ISSUE TITLE
Flashplayer won't load in Opera <15 with DEV 532 

### ISSUE THREAD

**Issue by mikewinq** [YePpHa/YouTubeCenter#2006]
Flashplayer isn't working with Opera 12.17 (don't tell me to upgrade to Opera 15+)
HTML5 player works but will only play videos in 360p

Anyone know any fix for this? 

Thanks

**Comment by Zarggg** [comment]
Two important things to consider: Is DASH enabled and is it supported by Opera 12?

If the answer to either of these is "no," then there's nothing else we can tell you other than to use a browser that is actively supported/developed.
