### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by Imold** [YePpHa/YouTubeCenter#2014]
I up dated to the latest version and now I can't open the settings.

**Comment by Nuriell** [comment]
Work fine for me.

**Comment by dice1976** [comment]
does not work for me and I don't even have the icon for settings on youtube anymore

**Comment by MsC0mmun1cat10n** [comment]
I'm having the same issue - settings opens my YouTube home page, and it displays this in the address bar:
https://www.youtube.com/#ytcenter.settings.open
However there are no indications on the page that it is anything other than vanilla YouTube. No extra settings. I have the latest version and I run it on Mozilla Firefox 40.0.3. I have disabled other add-ons and this has had no effect on the problem.

**Comment by dice1976** [comment]
Try https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version dev

**Comment by Imold** [comment]
The problem is I'm all ready using that and I can't open the settings. Oh and I'm using Firefox I should have said so before.

**Comment by Imold** [comment]
never mind it was another add on causing the problem.

**Comment by g0ren** [comment]
Which addon was it exactly? I'm having the same problem with firefox 44, so I'd like to know how to fix this.

**Comment by Imold** [comment]
Sorry I forget.

**Comment by MsC0mmun1cat10n** [comment]
If it helps, I checked all of my addons and none of them were affecting the program. I uninstalled it ages ago, though, anyway.
