### ISSUE TITLE
Disabling DASH issues

### ISSUE THREAD

**Issue by YamiryuuZero** [YePpHa/YouTubeCenter#2015]
Disabling DASH playback will cause the videos to not be rendered past 720p and not run at 60fps (I believe videos get locked at 30fps). I know this happened due to a change on Youtube's side, but please, fix this issue, if possible.

**Comment by Zarggg** [comment]
Due to the nature of the nature of YouTube's implementation of DASH, it is not possible for a browser addon to load 1080p+ or 60fps videos without using DASH. The only formats available without using DASH are 240p, 360p, and 720p.

**Comment by Yonezpt** [comment]
This is by YouTube's design, there is nothing that can change this: 

>Please note that by disabling DASH Playback will result in 480p and 1080p not being available. This is because of a recent YouTube change.

https://github.com/YePpHa/YouTubeCenter/wiki/Features#DASH_Playback

It has been posted before many times, please use the search function in the future.

**Comment by YamiryuuZero** [comment]
"It has been posted before many times, please use the search function in the future."

I imagined that would have been the case, but I'm still getting used to this site, and I couldn't search properly.

I am aware that 480p and 1080p being locked are because of an issue caused on Youtube's end. What I didn't know is that there's no way around it.

Well, thanks for the answers, anyway.
