### ISSUE TITLE
Anyone else can't view this video when YTC is enabled?

### ISSUE THREAD

**Issue by mleyen** [YePpHa/YouTubeCenter#2020]
https://www.youtube.com/watch?v=kspUer5kTi4

YTC disabled, video loads fine.
YTC enabled, it switches to Flash Player, then Flash Player loads indefinitely.
When trying to download the video using YTC or Download Youube Videos as MP4, it says the video can't be read because of a network error. Complete YouTube Saver also fails.

If this can help, the download URL for 360p MP4 is:
`https://r2---sn-4g57knze.googlevideo.com/videoplayback?source=youtube&initcwndbps=765000&dur=242.439&nh=IgpwcjAxLmZyYTAzKgkxMjcuMC4wLjE&fexp=9406006%2C9406715%2C9408710%2C9408863%2C9409069%2C9409208%2C9414875%2C9415365%2C9415435%2C9415485%2C9416023%2C9416126%2C9416729%2C9417689%2C9417701%2C9417707%2C9418153%2C9418918%2C9418959%2C9419290%2C9419306%2C9419404%2C9419446&expire=1439944057&mm=31&itag=18&signature=48B0D772B12A391442B95F239F97A643E3C78C75.1FD66D0761392BDF661D9512C620B9C19B4BF5AE&requiressl=yes&ms=au&mt=1439922322&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&id=o-ADNNNbm1UOZ6cgOT4d4BY_UYMbPLTVSN1WNwy5-sNIyC&mime=video%2Fmp4&pl=17&sver=3&ip=92.148.66.195&key=yt5&mn=sn-4g57knze&ipbits=0&ratebypass=yes&lmt=1404580429524818&upn=kidZRt87ftQ&title=Speed%20Freaks%20-%20Track%206%20-%20City&cpn=DYfr5h90__I81H3d`

Edit: saveyoutube.com worked...

**Comment by Zerathos** [comment]
With YTC enabled it loads into the HTML5 player without issues for me. The new player, specifically. Downloading also works normally.

**Comment by vule76** [comment]
It works but I set my player to "default", no html5, no flash.

**Comment by vpontin** [comment]
Confimed this issue here too, but i can download the video (both webm and mp4)

**Comment by mleyen** [comment]
Follow-up: #2024
