### ISSUE TITLE
All comments country flags are  unknown

### ISSUE THREAD

**Issue by RoMoss** [YePpHa/YouTubeCenter#2031]
All comments country flags are unknown

![unknown](https://cloud.githubusercontent.com/assets/13918198/9424278/4cde2c84-48ef-11e5-9524-0dbcc64d1b62.jpg)

Maxthon 4.4.0.4000

Thanks

**Comment by Betsy25** [comment]
it is like that for about 4 months already, the google API no longer offers the ability to know the country of origin.

**Comment by ireun** [comment]
Yup, you can search for closed tickets about this..
