### ISSUE TITLE
Youtube Grid Subscription Grid Broken AGAIN.

### ISSUE THREAD

**Issue by RohithKumarSp** [YePpHa/YouTubeCenter#2038]
so the YouTube Grid subsription broken on Chrome on Version 45.0.2454.46 beta-m (64-bit)
will there be a fix ?
![dev](https://cloud.githubusercontent.com/assets/13819800/9470764/0b72e450-4b6b-11e5-9dc2-ac94223ae1a1.JPG)

https://gist.github.com/99e527399c087f75738e

**Comment by Zarggg** [comment]
It looks like you have a custom style installed. Can you verify that the issue still occurs with all custom styles disabled?

**Comment by RohithKumarSp** [comment]
custom stylish was not for youtube, it was some dark theme for some forum, btw, the problem seems to have fixed it self magically.

**Comment by RohithKumarSp** [comment]
actually no, the problems back again, as soon as you select grid view, that happens.

**Comment by RohithKumarSp** [comment]
youtube changed their my subscription to grid by default, so that seems to be the issue...

**Comment by RohithKumarSp** [comment]
ok even the animation is broke, it only shows 3 thumbnails now not showing the animation.  everythings broke as of today.

**Comment by RohithKumarSp** [comment]
ok found the bug, the things mess up if you load a previous setting and save it and reload.
