### ISSUE TITLE
[Feature Request] Auto Like

### ISSUE THREAD

**Issue by rwilkin** [YePpHa/YouTubeCenter#2039]
Is it possible to get an auto like feature for subscriptions?

**Comment by Eisys** [comment]
This has been requested before.
Meanwhile:
https://chrome.google.com/webstore/detail/auto-like-for-youtube/acbfffookooknjnhcmjpoahgpkegpcld

https://chrome.google.com/webstore/detail/auto-like-extension/hmpdnikomlpadcgfepeafhhdpfilbocb?hl=en

https://greasyfork.org/en/scripts/4948-youtube-auto-like-videos

**Comment by rwilkin** [comment]
Thank you for your reply. Sorry, I didn't find where it had been requested before. I was hoping to only have to have one extension/add-on that could do everything lol. In the mean time I will use one of the ones you have linked. Thank you again.
