### ISSUE TITLE
Userscript memory usage zero, FF addon memory 3 mb+

### ISSUE THREAD

**Issue by spacedingo** [YePpHa/YouTubeCenter#2056]
The Firefox xpi addon takes about 3.2 mb without visiting YouTube. The greasemonkey userscript takes no additional memory. Hooray for that.
![2015-09-08 10_32_38-onenote](https://cloud.githubusercontent.com/assets/471376/9728241/a68e1f70-5617-11e5-9269-aee047724b6c.jpg)
![2015-09-08 10_33_24-onenote](https://cloud.githubusercontent.com/assets/471376/9728240/a68b827e-5617-11e5-9186-e47d0290c82d.jpg)

**Comment by Eisys** [comment]
Why are you reporting this? 
It's kind of obvious the addon would use some memory. 
And you shouldn't use the addon anyway since it's so outdated. Use the dev version with Grease.

**Comment by spacedingo** [comment]
This isn't a request for a fix or that anything is broken; I'm happy to use the userscript.

[**@Eisys**](https://github.com/Eisys) commented on [Sep 8, 2015, 2:39 PM GMT+4](https://github.com/YePpHa/YouTubeCenter/issues/2056#issuecomment-138511071 "2015-09-08T10:39:46Z - Replied by Github Comment Enhancer"):
> Why are you reporting this?   
> 
> It's kind of obvious the addon would use some memory.   
> 
> And you shouldn't use the addon anyway since it's so outdated. Use the dev version with Grease.
No, it's not obvious that the addon would use that much memory, because I have 40+ addons and none does that. If the dev FF add-on is deprecated like the stuff on the main page, then it shouldn't be there, because I had to learn the hard way not to use it.

**Comment by spacedingo** [comment]
Just FYI for users

**Comment by Eisys** [comment]
I'm pretty sure the high memory usage has been reported times before.
And yes, it shouldn't be there but Yeppha doesn't update it much anymore, so it's kind of dying.
I recommend you check out [YT+](https://github.com/ParticleCore/Particle/). It has less features than YTC but works alot better and is actively worked on.
