### ISSUE TITLE
Flag comments don't work

### ISSUE THREAD

**Issue by gopego** [YePpHa/YouTubeCenter#2058]
It says Unknown country, it's been like this for like 4 months ago. I can live without it but I kinda miss it now. how to fix it??
http://prntscr.com/8ea0w1

P.S load by button doesn't work too and sorry bad English.

**Comment by Eisys** [comment]
It can't be fixed. Youtube changed some stuff and now getting the country info of people is not possible.

**Comment by vpontin** [comment]
dupe #1877

**Comment by Djfe** [comment]
the flag option should be removed for comments then ;)

**Comment by gopego** [comment]
agree with Djfe
