### ISSUE TITLE
subscription grid view is broken

### ISSUE THREAD

**Issue by lakitu13** [YePpHa/YouTubeCenter#2082]
I'm using the .xpi on FF Dev edition
![2015-10-11_22-13-37](https://cloud.githubusercontent.com/assets/5847007/10420264/5c3eb75a-7065-11e5-8819-1f43b2d53aa4.png)

**Comment by GrahamFinch** [comment]
I'm getting the same now.

**Comment by Brottweiler** [comment]
https://github.com/YePpHa/YouTubeCenter/issues/2064
