### ISSUE TITLE
Can't select higher quality than 720p on some videos

### ISSUE THREAD

**Issue by Artefact2** [YePpHa/YouTubeCenter#2088]
Example video that triggers the issue: https://www.youtube.com/watch?v=OXR6g0Qwkqc

With YouTube Center (DEV edition v533) enabled: 

![](https://i.imgur.com/2NdDEDd.png)

After disabling YouTube Center: 

![](https://i.imgur.com/sCysman.png)

**Comment by LazyBoot** [comment]
You probably have dash playback disabled.

**Comment by Artefact2** [comment]
No, I have it enabled. It works on other videos.

**Comment by Pontiac76** [comment]
Maybe the video was just encoded at 720?

**Comment by Artefact2** [comment]
Can you see the images in my original message? The video *has* 1080p60
available after disabling YTC. It may be DASH-related, but it's not because
I disabled it, it works fine on other videos.

**Comment by Primeey** [comment]
I reported this issue a while ago https://github.com/YePpHa/YouTubeCenter/issues/2079

**Comment by Artefact2** [comment]
Thanks, @Primeey. Closing issue as it is a duplicate of #2079.
