### ISSUE TITLE
Video window overlaps playlist column

### ISSUE THREAD

**Issue by p1nkyy** [YePpHa/YouTubeCenter#2097]
Hello, I noticed that my video windows overlaps the playlist column a bit. It's not too disturbing but I wonder if it can get fixed?
Here's a screenshot:

http://puu.sh/ldSQc/7afe640e4b.jpg

**Comment by trol4ever** [comment]
What I did to fix this is, under the comment:
```javascript
// Applying style data to #player-api
```
look for
```javascript
if (playerPlaylist) {
          playerPlaylist.style.marginTop = -playerHeight + "px";
}
```
Which should be the 2nd if, remove an extra 30 pixels from the playerHeight.

Like this: 
```javascript
playerPlaylist.style.marginTop = -(playerHeight - 30) + "px";
```
Don't exactly know what YouTube changed to mess up the way the playlist is positioned.

**Comment by p1nkyy** [comment]
Thanks! Works like a charm @trol4ever :)
