### ISSUE TITLE
Grid UI

### ISSUE THREAD

**Issue by aleung241** [YePpHa/YouTubeCenter#2100]
Did something change on YouTube's end and break the grid UI on the subscriptions page?
![ss 2015-11-19 at 09 01 31](https://cloud.githubusercontent.com/assets/6620772/11252652/2f89dd84-8e9c-11e5-8cde-365f536a8fd1.jpg)

**Comment by Aikoku** [comment]
Same problem.

**Comment by LazyBoot** [comment]
Looks like youtube has switched to it's own grid view (I assume) since turning grid mode in youtube center fix it.

**Comment by Aikoku** [comment]
Actualy Subscribe Grid feature was on, and now, when I make it off, my
subscribe grid looks well.


*Lugupidamisega,*
*Mark Nikolajev*

2015-11-18 22:12 GMT+02:00 LazyBoot <notifications@github.com>:

**Comment by patq911** [comment]
Looks like youtube made their own version! Just disable it in youtube center options.  General -> Layout -> Grid Subscriptions.

**Comment by Gormador** [comment]
Thanks for the fix @patq911 :-)

**Comment by killroy42** [comment]
I suppose this means no more hiding of watched videos?

**Comment by jackm** [comment]
Thanks @patq911 
Youtube actually implemented a good feature!

**Comment by lunghd** [comment]
Yikes - same issue here. Disabled as patq911 suggested & that will restore the grid... but hidden videos now have a big ol' blank space where the thumbnail was. YT's version doesn't reshuffle & delete those hidden vid thumbnails. Crap.

YTCenter's teeny little dots to hide videos now show up below the thumbnail area... which is actually an improvement. Now if there's a way to reshuffle video thumbnails after hiding one...

**Comment by Corruptinglyneedful** [comment]
@lunghd to be fair the hide watched videos doesn't work well to begin with.

**Comment by lunghd** [comment]
@corrptinglyneedful - I agree.... but it worked better than anything YouTube had going! My only complaint was that the mouseover 'dots' to bring up the 'hide watched video' function were so painfully tiny & washed out that I ended up opening videos I simply wanted to hide.

**Comment by marceloavf** [comment]
Thanks @patq911 
There is also some bugs with the resolution description in the upper left corner on hover, but it's acceptable.

**Comment by GrahamFinch** [comment]
OMG! Thank you, YouTube! You finally did something right!

**Comment by Teapsalm** [comment]
Really dislike how YouTube categorizes them by days when I'd rather just have it how it previously was. Hope this gets fixed.

**Comment by raywu2478** [comment]
Yes! I'd like it better if the whole thing was a giant grid instead of separated by days and weeks..

**Comment by ddulic** [comment]
Lets hope youtube will implement more of the features from this addon ^^

**Comment by ModerateWinGuy** [comment]
Have the same issue.
Wow, youtube actually did something right for a change with their UI.

**Comment by gopego** [comment]
so this means youtube inspired by youtube center?? :p

**Comment by Brottweiler** [comment]
https://github.com/YePpHa/YouTubeCenter/issues/2064
