### ISSUE TITLE
Weird stuff in subscription

### ISSUE THREAD

**Issue by PepinCZ** [YePpHa/YouTubeCenter#2105]
Wtf... I'm seeing thos when using YT Center:
![wtf](http://i.imgur.com/cV3X1DV.png)

**Comment by DeeboDK** [comment]
Youtube's changing stuff again.... The new subscription page layout is sorted by "Today", "Yesterday", "This Week", "This Month", etc. To make it show up properly go into the YT Center settings and under General->Layout untick the "Grid Subscriptions" box.

**Comment by PepinCZ** [comment]
@DeeboDK thank you, that works.

**Comment by khaivngo** [comment]
@DeeboDK worked like a charm, thank you.

**Comment by guiaurelio** [comment]
Yes !! It works for me too :) Thanks

**Comment by leonklingele** [comment]
In case you're still trying to hide watched videos:

```JS
exports.loadWatchedVideosFromYouTubePage = function() {
	var elems = document.querySelectorAll(".feed-item-container div.yt-lockup-thumbnail.watched");
	elems = Array.prototype.slice.call(elems, 0);
	elems.forEach(function(elem) {
		var parentElem = elem.parentNode.parentNode;
		parentElem.parentNode.remove(parentElem);
	});
};
```

**Comment by Brottweiler** [comment]
https://github.com/YePpHa/YouTubeCenter/issues/2064

**Comment by keanzu** [comment]
@DeeboDK Thanks, that worked for me.
