### ISSUE TITLE
Youtube Center Not Working

### ISSUE THREAD

**Issue by darney53** [YePpHa/YouTubeCenter#2106]
When I click on download, I get a .tx file. Is there an update or another script that I should use? Please direct me to the current workaround with instructions on how to add to extensions, Thanks

**Comment by Eisys** [comment]
YoutubeCenter hasn't been updated in a long time and many things don't work well anymore.

But if you really want it, the easiest option would be to get Greasemonkey if you're on Firefox, or Tampermonkey if on Chrome. And then get [Developer version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version) as a userscript.

**Comment by darney53** [comment]
Thank you for the reply. I have installed Tampermomkey from the chrome store. Installed your user script “Youtube Center”. Tampermomkey shows no script running. Since I am new to this and there are so many scripts. Can you suggest one that will allow me to download Youtube videos? And a brief on how to install it. Thank you much.

Darney53

**Comment by Eisys** [comment]
https://greasyfork.org/en/scripts/1317-download-youtube-videos-as-mp4

Just press 'Install this script'
Then Tampermonkey should open and in there, click 'Install'

**Comment by darney53** [comment]
Thank you, I see from the dashboard, that the script is installed. But inside Tampermonkey it show “No script running”. How do I get it to run within Tampermonkey?

**Comment by Eisys** [comment]
It should just work. Go to youtube and see if a download button appears under a video.
If it doesn't then you should contact the script's creator instead.

**Comment by darney53** [comment]
Thank you, yes it works. Can only download max resolution 360, but that ok. Mainly do it for friends that don’t have a computer or lack of access to workarounds that you guys have helped me access.

**Comment by BobbyWibowo** [comment]
> Can only download max resolution 360, but that ok.
That depends on the video. If the uploader didn't upload the video as 720p or better, of course you can't download 720p. But there's an issue where the download link for 420p version is never available. At least that's how it is on my side. If the video is 720p, I can download 720p and 320p, but there's no option to download 420p despite of the fact that I can play the video as 420p.

**Comment by darney53** [comment]
You are right, my observation was based on the first few videos downloaded. I have found since that comment that it depends on what resolution is available for a particular video. So I stand to be corrected.

**Comment by ErdeFB** [comment]
The reason you cannot download videos on certain resolution is due to Youtube splitting the video and audio tracks on those resolutions. YTC cannot help you with those.

**Comment by Eisys** [comment]
@darney53 It works fine for me. http://i.imgur.com/h9mH3jG.png

Perhaps try reinstalling Tampermonkey itself. Or something might be out of date like Tamper or Chrome or sth. Or maybe you have an older version of the script still running. Go into Tamper's dashboard and delete the scripts and reinstall it.
Also try clearing your browser's cache.

If none of that works, then try this script:
https://greasyfork.org/en/scripts/19592-youtube-best-video-downloader-2
or these: 
https://greasyfork.org/en/scripts/20823-video-download-button
https://greasyfork.org/en/scripts/16474-youtube-video-downloader
https://greasyfork.org/en/scripts/13851-youtube-downloader

Or search for one yourself here:
https://greasyfork.org/en/scripts/search?q=youtube+download

**Comment by darney53** [comment]
Thx, uninstalled & reinstalled Tampermonkey. Installed Grease Fork script. Downloading properly now.



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by darney53** [comment]
Hey for some reason Tapermonkey is not showing download button at Youtube.
Can you please send me a user script. And some kind of instructions. Cause
whenever it makes any changes I don't know what to do. I just use it.
I have made donations to show my appreciation. I need help?

**Comment by darney53** [comment]
Can anyone help me with finding and downloading a script to download youtube videos using Tapermonkey Please!

**Comment by darney53** [comment]
Or help me with this one
WARNING : Best Video Downloader 2 is not compatible with the experimental YouTube Material Layout
which is under BETA testing.

Click here for instructions on how to continue using the video downloading features.
This addon will get migrated to the new layout when Youtube makes the BETA design as default, make sure you are configured for auto-updates.
