### ISSUE TITLE
Subscription page view

### ISSUE THREAD

**Issue by lifeguardm** [YePpHa/YouTubeCenter#2112]
![youtube issue](https://cloud.githubusercontent.com/assets/8953555/11448075/f46f53a6-9516-11e5-9fb3-7c5931f007ea.PNG)

The subscription page is not stacking correctly, and seems to ad two videos to the right when load more is used.

**Comment by GrahamFinch** [comment]
Turn off subscription grid view on YTC. Google brought it back.

**Comment by lifeguardm** [comment]
Thanks, I wasn't aware that they conflicted.
