### ISSUE TITLE
[Fixed] Remove days, weeks, etc. from subscription view.

### ISSUE THREAD

**Issue by GrahamFinch** [YePpHa/YouTubeCenter#2113]
Since YouTube finally brought back grid view after two years (thank you!), it's kind of awkward to see the videos split up between time frames. Another issue with this new layout is that some very old videos from weeks and months ago WILL NOT GO AWAY, no matter how many times you remove it.

There needs to be a new feature in future versions of YTC to restore the old format of the grid view before YouTube botched it with this new version.

EDIT: How to I apply the Feature Request label to this post? I can't seem to do that...

**Comment by gwt32o32pr23r23pk** [comment]
I agree. The grid layout was much more useful when the videos flowed into each other with continuity.

**Comment by Yonezpt** [comment]
Try the following: With YTC grid layout enabled, open https://www.youtube.com/feed/subscriptions?flow=2

See if it works

**Comment by GrahamFinch** [comment]
It worked! Thanks, Yonezpt!

Old videos still won't go away, though.

**Comment by lunghd** [comment]
Changing the flow to "list" format just brought back more old videos & put away the grid view for me.
