### ISSUE TITLE
Flash Player plays only in 144p (solved)

### ISSUE THREAD

**Issue by alike03** [YePpHa/YouTubeCenter#2118]
Hi guys.
Since today I have this issue where I can't change the quality anymore.
Even if I select another quality it doesn't change.
The auto-start-quality doesn't work too which is normally at 1080p.

But when I change the Player type to HTML5 (Default) it works like it should without this problem.
So I'm assuming either is my browser is broke somehow or Youtube changed his source code.

**Comment by platekme** [comment]
I had the same problem, clearing cache/cookies and restarting the browser fixed it. Youtube must have changed something.

**Comment by flakzilla** [comment]
I saw this as well, clearing cache/cookies and restarting the browser fixed it. Youtube must have changed something.

**Comment by alike03** [comment]
Clearing the Cache fixed my problem. Thank you flakzilla
