### ISSUE TITLE
Resizing the player doesn't resize the video and controls.

### ISSUE THREAD

**Issue by eduardog3000** [YePpHa/YouTubeCenter#2120]
__Browser name__: Chrome
__Browser version__: 47.0.2526.80 m
__Browser engine__: Webkit
__YouTube Center version__: Developer Version - Build 533
__Addon type__: Userscript
__Issue description__:
This is what happens when I resize from `Fit to Content` to `Small`:
![](http://i.imgur.com/rKoWod9.jpg)

Toggling pause/play causes the video and controls to catch up with the player, but that isn't automatic.
Edit: It seems the `Show More`/`Show Less` button below the description also causes the size to adjust.

I'm guessing YouTube changed something again.

__How to reproduce the issue__: Resize any video.

**Comment by Greenphlem** [comment]
Can confirm, supposed to look like this: 
![fmlttin](https://cloud.githubusercontent.com/assets/3390436/11690248/97399498-9e4a-11e5-8c00-5850b8cafca9.jpg)

Looks like this
![sd8zgpn](https://cloud.githubusercontent.com/assets/3390436/11690270/b43e775c-9e4a-11e5-831c-50fdc859310d.png)

**Comment by iiiGerardoiii** [comment]
Pressing Ctrl+Shift+B twice adjusts the video as well, but yeah you gotta do that manually.

**Comment by Pazns** [comment]
Exactly same problem with Firefox on Fedora.

**Comment by Pazns** [comment]
Fixed for me with 2cc83e24eed608353f600be6c20c0f5819ae3e9b .

**Comment by Greenphlem** [comment]
Not fixed for me with the newest dev build 534

**Comment by iiiGerardoiii** [comment]
Works fine on Build #535

**Comment by Greenphlem** [comment]
Just tried that build, still getting it, see this gif. 

http://i.imgur.com/RfkDaYE.gifv

**Comment by Greenphlem** [comment]
Seems like it might have to do with the fullscreen top player

**Comment by iiiGerardoiii** [comment]
ooh you're right, problem still occurs on fullscreen top player.

**Comment by fireattack** [comment]
@YePpHa  Can you double check about this? I installed ver. 537 but still have this problem.
