### ISSUE TITLE
YouTubeCenter dosen't work after update Chromium on 47.0.2526.73

### ISSUE THREAD

**Issue by lexxus-lex** [YePpHa/YouTubeCenter#2121]
Today i have update Chromium, but now on youtube script don't work and missing settings button

**Comment by ErdeFB** [comment]
Try opening your browser menu and navigate to: More Tools -> Extensions -> navigate to YTC and click Options.

This should open a new browser tab and and the YTC settings. YTC should be usable on this tab.

**Comment by lexxus-lex** [comment]
no way. i Use java script.

**Comment by lexxus-lex** [comment]
Omg, i fixed this. 
I install tampermonkey and install jvscript again.
In violentmonkey script not work
