### ISSUE TITLE
Subscription Feed Box displaying incorrectly.

### ISSUE THREAD

**Issue by Kilva** [YePpHa/YouTubeCenter#2124]
It works when I disable the extension but it's a little annoying ;)
It's been a problem for a while I think since Google changed something, but I just want to make sure it's known about.

I'm using Maxthon v4.4.7.1000.

UPDATE: Well I just looked around and found a fix from 12 days ago. Adding ?flow=2 sets it to YouTube's typical listing, which YTC then seems to properly put into a grid.
I won't close it because, well... it is still an issue. Feel free to.

**Comment by Brottweiler** [comment]
https://github.com/YePpHa/YouTubeCenter/issues/2105#issuecomment-158065694
