### ISSUE TITLE
Choppy scrolling on youtube pages

### ISSUE THREAD

**Issue by 1112e** [YePpHa/YouTubeCenter#2125]
Firefox seems to be choppy overall, started when i updated to the newest ytc dev build

**Comment by LittleVulpix** [comment]
Yes, actually, the whole firefox becomes VERY slow after latest update - as soon as you open a video.

**Comment by CptWinters** [comment]
Same thing happening over here. Firefox 42.

**Comment by 1112e** [comment]
The newly added code messed it up, here's a build with that removed 
[YouTubeCenter.zip](https://github.com/YePpHa/YouTubeCenter/files/60195/YouTubeCenter.zip)

**Comment by Dabarti** [comment]
Exactly same thing is happening on Chrome 47.

**Comment by 1112e** [comment]
Or just do it yourself:
1. Open YouTubeCenter.xpi in 7zip or something
2: Open YouTubeCenter.js
3. Delete lines 1621-1637
4. Delete line 23230
5. Save and install

**Comment by Deviator13** [comment]
Everything bad on Maxthon 4, video stops every second and browser seems very slow.

**Comment by LittleVulpix** [comment]
Confirmed! thanks @YePpHa ! :D
