### ISSUE TITLE
Build #534 causes YouTube Videos to lag on Maxthon

### ISSUE THREAD

**Issue by peterpan11** [YePpHa/YouTubeCenter#2126]
Hello,

since I installed the new Build #534 a few minutes ago all the YouTube videos lag (not the sound, just the video). Before I installed the latest dev build everything worked fine.

A restart of Maxthon same as a restart of the PC didn't fix this problem.

Disabling the YouTubeCenter extension did solve the problem though.

Thanks in advance for looking into it! Keep up the great work!

PS: I am using the HTML5 player if that's relevant.

**Comment by YePpHa** [comment]
The only change made is that YouTube Center dispatches a custom event to the window that tells the page that the window has been resized. Look at https://github.com/YePpHa/YouTubeCenter/commit/2cc83e24eed608353f600be6c20c0f5819ae3e9b for the changes. I don't remember how many times the resize function is called, but it could either be that Maxthon has problems with custom events or something else is amiss.
