### ISSUE TITLE
Black borders on all videos

### ISSUE THREAD

**Issue by RaaFaaeL** [YePpHa/YouTubeCenter#2128]
All the videos that I watch are with these black borders. I have reseted the YouTube Center settings but still the same.

 
![youtube center bug](https://cloud.githubusercontent.com/assets/8131404/11763699/eb656eee-a0fb-11e5-9ffd-288aa3a2f9ac.png)

<b>Browser:</b> Chrome 47.0.2526.80 m (64-bit)
<b>YouTube Center version:</b> Developer Version (Build 535)  <b>(YouTubeCenter.crx)</b>
<b>Debug:</b> https://gist.github.com/0fcdbbe089931843008e

**Comment by Vankog** [comment]
+1

__Browser name__: Chrome 
__Browser version__: 47.0.2526.80 m (64-bit)
__Browser engine__: Blink, I think? ^^
__YouTube Center version__: Developer Version - Build #535
__Addon type__: Chrome extension
__Debug log__: https://gist.github.com/5c0a412967d02233890a
__Issue description__:
![blackborders](https://cloud.githubusercontent.com/assets/3804909/11764127/1de3a3ae-a124-11e5-988f-ed3db3c293a0.png)

__How to reproduce the issue__:
just import these settings:
https://gist.github.com/8721b9f20e05cfbbbf13

**Comment by YePpHa** [comment]
Go to Settings -> Player -> General and change `Auto-hide bar` to `Both progressbar & controlbar`.

**Comment by Vankog** [comment]
@YePpHa 
Thanks for the fix, it works now.
However, speaking of the auto-hide bar option. It seems to do nothing on the site. All options result in the same: Whole controls being hidden or visible based on mouse-over.
Not sure if I should really open a new issue for that, but worth a side note.

**Comment by RaaFaaeL** [comment]
<a href="https://github.com/YePpHa" class="user-mention">@YePpHa</a> Thank you :-)
