### ISSUE TITLE
Firefox removing YT Center

### ISSUE THREAD

**Issue by jake2wheels** [YePpHa/YouTubeCenter#2153]
Yesterday I opened up Firefox and received a notification saying YT Center was removed because it was unverified. Is there a way around this? I tried using the AMO add on but it never works for me. Any suggestions?

**Comment by Pontiac76** [comment]
Use the developer version and stay with FF43 or below.

**Comment by Yonezpt** [comment]
The alternatives have been shared here https://github.com/YePpHa/YouTubeCenter/issues/1992#issuecomment-164900008 and here https://github.com/YePpHa/YouTubeCenter/issues/2141#issuecomment-166273803

**Comment by Corruptinglyneedful** [comment]
xpinstall.signatures.required in about:config, set it to false.  This will only work for a small while, so make sure that you do not update further in the future.  It has been confirmed that Mozilla is removing the ability to do this from about config in the future, in addition to the deprecation of XUL addons systems.
