### ISSUE TITLE
Subscription tab broken

### ISSUE THREAD

**Issue by IonDrako** [YePpHa/YouTubeCenter#2158]
I've been running the most recent dev builds for a while and at one point the subscriptions tab from the homepage got super screwed up, I left it alone thinking as it seemed to be a big issue it'd get fixed but seeing as it hasn't I thought I might as well put it here, Image of the problem attached

![subtab](https://cloud.githubusercontent.com/assets/10403311/12075225/8b573094-b147-11e5-9999-11e8850bb258.png)

**Comment by Brottweiler** [comment]
Duplicate: https://github.com/YePpHa/YouTubeCenter/issues/2064

Workaround: https://github.com/YePpHa/YouTubeCenter/issues/2105#issuecomment-158065694

**Comment by IonDrako** [comment]
Thank you, didn't find the duplicate before posting, still weird nothing has been done to fix that or toggling the subscription grid thing off be default

**Comment by Brottweiler** [comment]
You can close this issue now. :stuck_out_tongue:
