### ISSUE TITLE
Addon broken on Firefox 44 and up

### ISSUE THREAD

**Issue by mzso** [YePpHa/YouTubeCenter#2162]
Hi!
It does not function at all. It's not the signature check, because I have that disabled, but some other change.

Maybe one of the changes mentioned in this topic was uplifted already? http://forums.mozillazine.org/viewtopic.php?f=23&t=2975063

**Comment by ButchDeLoria** [comment]
Video playback works if I force Flash with Settings > Player > Player Type: Aggressive Flash. It seems to be an HTML5 only problem.

**Comment by mzso** [comment]
It doesn't work at all. I don't even get the settings icon for youtube center. So I can't force anything. I don't get ratings preview or quality on icons. Nothing at all.
Are you sure you tried with FF44 or higher?

**Comment by Brugman** [comment]
Same thing as mzso for me. YouTube loads without a trace of YTC. Tried reinstalling the xpi but no difference. (xpinstall.signatures.required set to false a while ago)

I don't know if Firefox just updated in the background (that would help blame v44) but I am on 44.0.

**Comment by IMNdi** [comment]
@Brugman It is most definitely 44.0

I played a video on 43.0.3, pushed update, then no YTC. Same for clean install. Seems installed and enabled, but no icon nor trace of the thing exists (no scroll up to full screen, no resizing, nothing).

**Comment by PPNSteve** [comment]
It doesn't work at all. I don't even get the settings icon as well.. so something in ff44 borkd it

**Comment by amloessb** [comment]
Ditto here, the add-on just flat-out doesn't work in FF 44.  I have dev version 537 installed.

**Comment by ErdeFB** [comment]
This seems to be FF bug so I'll close this issue report unless it can be proven to be YTC issue.
It is also advisable to install the userscript version considering that @YePpHa releasing a signed add-on is rather unlikely at least at the time of writing.

**Comment by mzso** [comment]
That's silly. Not being a YTC bug doesn't fix the issue...
Also it's likely because one of those changes related to addons I linked to which isn't actually a firefox bug, but something that YTC wasn't updated for.

**Comment by Brugman** [comment]
The User Script version _does_ work so I'm happy with that. Thanks @ErdeF

**Comment by megaspel** [comment]
Userscript isn't an option, greasemonkey has massive memory leak bugs that have gone unaddressed for years and introduces a massive amount of lag when changing tabs.

**Comment by amloessb** [comment]
I installed Greasemonkey and have been using the userscript version of YTC for about a month now, and I haven't had any memory leakage or tab-lag.
