### ISSUE TITLE
YTC no longer working with Firefox update (44.0)

### ISSUE THREAD

**Issue by brickwall35** [YePpHa/YouTubeCenter#2171]
I was using YT fine with YTC, then I updated Firefox to the newest version, and it no longer works. I still have the extension, and it says it is running, but no options are showing up on YT. This could very well be an issue on my end, but I don't know what to do.

**Comment by brickwall35** [comment]
Managed to fix this via Greasemonkey, but before this version of Firefox, using a script wasn't necessary, so I guess it's still a bug.

**Comment by Zarggg** [comment]
The issue is that Firefox stopped supporting unsigned addons as of version 44 and YTC is not signed.

**Comment by Gotolei** [comment]
It's still possible to install unsigned extensions by going into about:config and changing *xpinstall.signatures.required* to false, and [will remain possible until fx46.](https://wiki.mozilla.org/Addons/Extension_Signing#Timeline)

That being said I've run into this as well. Userscript version works, though.

**Comment by Yaro96** [comment]
I wonder, why YePpHa doesn't update the "stable" (not working) version on its addons.mozilla.org page, so it can be signed and installed easily. The "developer" version seems pretty good to me.

**Comment by Prisoner416** [comment]
Still broken after setting xpinstall.signatures.

**Comment by PPNSteve** [comment]
same here, FF44 and its broken.. says it enabled and install unsigned extensions is allowed but nothing works.,

**Comment by Nicholas-Steel** [comment]
I can confirm that Youtube Center claims to be installed and active but it doesn't actually affect anything on Youtube anymore when using Firefox 44 under Windows 10 x64.

**Comment by Extraordinary37** [comment]
Same problem here, addon signing disabled in about:config, YTC addon says enabled, but is not working at all (Gave mozilla a load of grief thinking they had broken disabling signing, which they deserve anyway, it should be our choice forever, not just until FF46)

**Comment by Yonezpt** [comment]
@Yaro96 I've explained in detail the problems that are linked with something that appears to be a trivial task: https://github.com/YePpHa/YouTubeCenter/issues/2141#issuecomment-166273803

To all the others unable to run it after changing the signature enforcement, the userscript alternative appears to still be working. Until the add-on is updated I don't see a better fix other than using the userscript.

@YePpHa Can't tell for sure what, but I think one (or more) apis have been dropped in this version making the add-on version incompatible. Also signing the add-on as unlisted does not require any screening or review queues, so the new version can be updated and signed without issues as far as I could see avoiding the signature problems the new FF versions introduced.

**Comment by Nicholas-Steel** [comment]
Ah, I didn't realize the userscript was also on the main website. I'll install it now. Also thanks for that wordy post Yonezpt, nice and informative.

**Comment by banther7** [comment]
im running into this issue as well and i had to downgrade firefox to 43.0.3. does the userscript version keep your addons settings if you switch?

**Comment by Gotolei** [comment]
No, they don't seem to share them unfortunately :/

However it looks like you can at least export your settings in the addon version (button at the bottom of the General settings page) and then import them into the userscript version.

**Comment by Nicholas-Steel** [comment]
The userscript version doesn't work for me, I'm using a custom theme for Youtube via the Stylish mod which may be why.

**Comment by wrexwaz** [comment]
Same problem here. In Firefox 44 x64 options disappeared from YT.

**Comment by Cephsus** [comment]
Ugh! Nothing is working for me aswell.

xpinstall.signatures was already set to false, so no go there. And Greasemonkey userscript isnt working either. Crazy how different going on YT is now, like day and night. So many missing feats ;)

**Comment by Harmenius** [comment]
The devbuild userscript works for me as well but I accidentally installed the obsolete version from the wiki homepage first, so this is a heads-up for people making the same mistake.

**Comment by Extraordinary37** [comment]
I just rolled back to FF43.0.3 - nothing mega special about 44 to have to mess about like this, I`ll wait for a YTC addon update, and then upgrade back to 44

**Comment by Nicholas-Steel** [comment]
@Harmenius That was it! Thank you, it's working now :)

**Comment by Cephsus** [comment]
@Harmenius Thanks m8, the GM wiki version is the one i tried aswell, didnt realize there was a dev version. And it works again. Cheers.

**Comment by wrexwaz** [comment]
Give me a link to working version please.

**Comment by Cephsus** [comment]
@wrexwaz  https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

Install Greasemonkey, add the userscript (YouTubeCenter.user.js)

**Comment by max6166** [comment]
I have always been running the version at: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version 

No luck with FF44. No access to config settings, nothing works, video plays as narrow strip across top. 

Wonder why it is working for some and not others....?

**Comment by Nicholas-Steel** [comment]
If you actually read this topic you would know why it works for some and not others, and how to get it working for you too.

**Comment by max6166** [comment]
Ok, I'll take the bait. Why does the same GM dev script that some others are using not work for me? I don't see anything in this thread which explains that.

If there is something in this thread I missed, it wasn't for lack of reading it, which I did many times.

**Comment by PPNSteve** [comment]
went with greasemonkey and the userscript.js file.. is working again in Firefox 44+

**Comment by sagamusix** [comment]
Why did this get closed now? As far as I can see the original issue - the Firefox extension being broken - still exists and thus needs to be resolved, no matter if the UserScript versions works for some or not.

**Comment by Nicholas-Steel** [comment]
Max6166, you need to use the Userscript provided on the Developer Version website,.

**Comment by max6166** [comment]
@Nicholas-Steel As I initially said, I am running the dev version.

**Comment by ErdeFB** [comment]
The reason this got closed is because it is a Firefox issue and the developer needs to push a new stable version to Mozilla add-on page and this is very unlikely to happen as the author of YTC is no longer actively developing the add-on, only fixing issues that break the whole addon. You should use the developer version for now.

**Comment by Gotolei** [comment]
> You should use the developer version for now.
The developer version of the addon *is* the one with the problem.

Build 537, Firefox 44.0, Linux x64

**Comment by ErdeFB** [comment]
It works just fine when installed properly and with proper version (userscript). The original issue report was that the add-on version does not work with new versions of Firefox that disable unsigned add-ons.

**Comment by Gotolei** [comment]
Except the unsigned addon restriction can be disabled, at least for the time being. I have unsigned builds of two other addons that work just fine.

Admittedly, it looks like the addon version's good as dead already at this rate since that option's going to be taken out in a few months. Pity to see it go.
(Never heard of the userscript version being the "proper" one before, but whatever works I guess)

**Comment by ErdeFB** [comment]
I mentioned the userscript being the correct version due to the reason that it will be the only one to work for Firefox in near future so better to switch to it now. Also, it is smarter to recommend it to not so tech savvy users rather than instruct them to go messing with the browser configurations in about:config.

**Comment by yedey** [comment]
> Except the unsigned addon restriction can be disabled, at least for 
> the time being. I have unsigned builds of two other addons that work just fine.

Yep, same here. It's not a signature problem at all, as I can see YTC getting loaded in the browser console of Firefox and it throws a "loadScript is undefined" error.

**Comment by ErdeFB** [comment]
That would imply that it is a Firefox issue and not YTC issue considering the userscript works. If someone can prove it is YTC issue and not FF issue, I'll re-open this issue report.

**Comment by ErdeFB** [comment]
Actually, this is a duplicate of #2162 and it seems it might indeed be FF bug.
