### ISSUE TITLE
Fix subscription tab please

### ISSUE THREAD

**Issue by Zateks** [YePpHa/YouTubeCenter#2173]
Using TamperMonkey and userscript for Google Chrome.
The subscription tab does not load correctly and the thumbnails overlap.

<img width="1247" alt="screen shot 2016-01-27 at 11 21 18 pm" src="https://cloud.githubusercontent.com/assets/13065713/12635005/b95ece02-c54c-11e5-98de-b086c19e6938.png">

**Comment by ErdeFB** [comment]
Do you have grid subscriptions turned off in YTC settings?

**Comment by Zateks** [comment]
Yes, the feature was turned on. Turning it off fixed the problem, thank you!
