### ISSUE TITLE
The video thumbnail features

### ISSUE THREAD

**Issue by q1k** [YePpHa/YouTubeCenter#2176]
Is there a possibility someone to take a couple of the video thumbnail options and make them a seperate script?

What I would like is the Animation and Quality showing on hover.

So 
Enable animation - check
delay - 700
interval - 500
fallback - 2000

Enable quality - check
show fps - check
position - top left
visible - when mous is over thumbnail

Thank you to whoever helps

**Comment by q1k** [comment]
Anyone?

**Comment by ErdeFB** [comment]
I think silence for more than a week is answer enough for your question.
