### ISSUE TITLE
Developer version stopped working

### ISSUE THREAD

**Issue by marktedrow1** [YePpHa/YouTubeCenter#2178]
This is the best add on for YouTube I have found. It does everything for you, or at least it used to. All of the other YouTube add-ons do part of what this one does only.

Now the Firefox version is so outdated it won't work at all. I was using the Git Hub Developer Build version 537, but last night it stopped working also. I really want it back.

Also as Mozilla updated, they are removing add-ons that are not signed, and the Developer version is not signed. Maybe that is why the settings don't even show up when you click on "options". The "cog" wheel is missing completely.

**Comment by mpsdskd** [comment]
I'm also having this problem with this very useful add-on.

yt-center dev build 537
xpinstall.signatures.required=false
Firefox v44
Kubuntu linux

**Comment by blue-lightning** [comment]
Use the userscript version. The add-on's not working with Firefox 44

**Comment by marktedrow1** [comment]
I have seen the userscript version. How do I use it?

**Comment by Yonezpt** [comment]
@marktedrow1 Read https://github.com/YePpHa/YouTubeCenter/issues/2171#issuecomment-177489520

**Comment by marktedrow1** [comment]
Thank You! I did figure it out with Grease Monkey last night and it seems to have worked. At least for now. I did have to change the setting in "xpinstall.signatures.required" preference in FF 44 to false in the Firefox Configuration Editor to override the add on signing blockage, but I read that this cannot be overridden in FF 46, I'm assuming that means if the add on is not signed, you can't use it.

**Comment by lewisje** [comment]
By the time Firefox 46 comes out, unbranded builds, which will allow you to disable signing enforcement, will be available, and Firefox ESR also will not enforce signing (next one is ESR 45).

**Comment by marktedrow1** [comment]
Had a few questions, #1, what is an unbranded build, and #2, what is Firefox ESR?

**Comment by Yonezpt** [comment]
Please don't use the issue tracker for this kind of discussion, this is not a forum. If your issue has been solved then kindly close it

**Comment by lewisje** [comment]
Google is your friend, @marktedrow1: https://wiki.mozilla.org/Addons/Extension_Signing#FAQ

I did however forget that the ESRs *will* enforce signing by default and you'll need to set a preference to disable it, like the unbranded builds.

(Also there should be a "Close issue" button at the top of this issue, and at the bottom; I think only you or a YouTube Center collaborator can close the issue.)

**Comment by ErdeFB** [comment]
There is a close issue button for the person who opened it, but I'll handle it.

**Comment by marktedrow1** [comment]
Sorry, I have never used github.com before and was not trying to cause problems with forums or anything. You guys closed this issue after if was solved for me with the userscript, but only temporarily until FF 46. I was simply trying to gather more information on what to do then.
