### ISSUE TITLE
subscriptions displayed not correctly

### ISSUE THREAD

**Issue by ANALiTIK2550** [YePpHa/YouTubeCenter#2181]
http://take.ms/bfJU8
^this screen page https://www.youtube.com/feed/subscriptions
video superimposed and displayed not correctly
Brauser Maxthon 4.4.6.1000

В подписках уже кучу времени некорректно отображаются видео, накладываясь друг на друга.
ПС: это началось после очередного обновления ютуба(довольно давно). Это было то обновление после которого при обычной работе ютуба(без включенного разрешения) видео на каналах и в подписках, да и вообще почти везде, начали отображаться сеткой/плиткой, а не таким списком как и по сей день в https://www.youtube.com/feed/history

**Comment by ErdeFB** [comment]
Go to YouTube Center settings, General -> Layout -> and disable Grid subscriptions.

**Comment by ANALiTIK2550** [comment]
Thx you! =)
