### ISSUE TITLE
Videos and audio files won't download anymore

### ISSUE THREAD

**Issue by LaVey-Charkus-Veros** [YePpHa/YouTubeCenter#2182]
Hello.

Recently, I've noticed that videos won't download anymore, no matter if I press the main [Download] button or if I choose a resolution from the dropdown menu, the download simply won't start. If I use the "Save Link As..." option from the context menu, it now always downloads a 0 kb text file named "videoplayback.txt". I don't know if this is an issue only I have but a few months ago I could download any video or audio files without problem.

I've tried with HTML5 and Flash versions but the problem persists. I don't know if one of my browser's extensions is conflicting with YouTube Center, but if it's working for everyone, then that will hint me that it is a problem on my end and I'll be able to start looking for what's causing this.

By the way, I'm using an old version of Firefox (ver. 37.0.2) because all newer versions after that run with many bugs, scrolling through pages is choppy and the overall environment feels slower.

Thanks for reading and I hope someone can help me.

Regards.

**Comment by Yonezpt** [comment]
See https://github.com/YePpHa/YouTubeCenter/issues/2098#issuecomment-157497362
