### ISSUE TITLE
Has completely stopped working in firefox

### ISSUE THREAD

**Issue by Kitsuni** [YePpHa/YouTubeCenter#2184]
As of an hour or so ago it has stopped working in firefox, both stable and dev.  Doesn't even show the cog for options. Tried reinstalling with no luck.

Firefox version 44.0.1
YTC version 2.1.7 (dev)

**Comment by shadecrawler** [comment]
Yeah... I have the same problem. Since FF updated itself my favorite addon stopped working =/

**Comment by subliminal2** [comment]
Same here...

**Comment by sherehel** [comment]
Yep   😕

**Comment by Yonezpt** [comment]
See if the temporary fix in https://github.com/YePpHa/YouTubeCenter/issues/2171#issuecomment-175374141 still works. Remember to use the Dev version.

**Comment by shadecrawler** [comment]
Using the userscript version actually fixed it. Thanks!

**Comment by g0urra** [comment]
Do I need to remove the addon in order to make the userscript version work? Firefox 44.0.1.

**Comment by Yonezpt** [comment]
@g0urra You need to at least disable it to avoid conflict with the userscript.

**Comment by g0urra** [comment]
@Yonezpt I did that but it's still not working, even after restarting Firefox.

**Comment by Yonezpt** [comment]
Make sure you are using the developer version:

https://github.com/YePpHa/YouTubeCenter/raw/master/dist/YouTubeCenter.user.js

**Comment by submerged15** [comment]
@Yonezpt The grid doesn't work properly on the subscription page.

**Comment by Yonezpt** [comment]
@submerged15 see https://github.com/YePpHa/YouTubeCenter/issues/2114

In the future don't use unrelated issues for this, either search for an already existing one or post a new issue.

**Comment by submerged15** [comment]
@Yonezpt You're right. Should i create one now for that issue?

**Comment by Yonezpt** [comment]
No, I already linked to one providing a solution for your problem and there are already many opened. There's no reason to open one more duplicate.

**Comment by ways2web** [comment]
same here.. xpinstall.signatures.required is false

Firefox version 44.0.1
YTC version 2.1.7 (dev)

**Comment by Yonezpt** [comment]
2.1.7 is *NOT* the developer version, there isn't any 2.1.7 dev version.

v.537 is the developer version and it is located in the **Download** section only https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version#download

**Comment by ErdeFB** [comment]
Like stated, the only future-proof solution for FF users is to use the userscript developer version linked as the author is not actively developing this add-on anymore so getting a new stable version is rather unlikely (if one would be to materialize, it would most likely just be the current developer version anyways).

**Comment by ways2web** [comment]
how to use the userscript? its only a javascript file... sorry 4 the question.. beginner :)

**Comment by Yonezpt** [comment]
[How to install a userscript](http://lmgtfy.com/?q=how+to+install+a+userscript)
