### ISSUE TITLE
Add on not working at all after updating to firefox 44.02?

### ISSUE THREAD

**Issue by Badgerconda** [YePpHa/YouTubeCenter#2186]
Not sure if this is happening to anybody else, but after updating firefox today (to 44.02), the dev build addon doesn't work at all. I can't even access the options anymore. Tried disabling/reenabling and restarting, doesn't make a difference.

The user script version still works, but the addon just plain doesn't function.

**Comment by ErdeFB** [comment]
Please search old issue reports before creating new ones. You either need to switch to the userscript version or disable add-on signing which is only a temporary solution. Thanks.
