### ISSUE TITLE
Doesn't work with Firefox 44

### ISSUE THREAD

**Issue by seamoonz** [YePpHa/YouTubeCenter#2187]
Doesn't work with Firefox 44

**Comment by Yonezpt** [comment]
Please use the search field next time

https://github.com/YePpHa/YouTubeCenter/issues/2184

https://github.com/YePpHa/YouTubeCenter/issues/2171

https://github.com/YePpHa/YouTubeCenter/issues/2162

https://github.com/YePpHa/YouTubeCenter/issues/2186

**Comment by Fironet** [comment]
Oh, so these reports are due to the unsigned addon. Guess I missed all that since I'm using the developer version of Firefox with the setting disabled.
