### ISSUE TITLE
Subscriptions page completely broken

### ISSUE THREAD

**Issue by raku-cat** [YePpHa/YouTubeCenter#2196]
Running firefox 46.0a2 on linux mint 17.3 x64, using userscript dev build 537, the subscriptions page is mostly useless for me as shown here
![](http://puu.sh/nrkJs/5883d53f7f.png)
The list is squished and it shows videos from days and weeks ago, as opposed to how it displays normally with the script disabled 
![](http://puu.sh/nrlhO/6c03a3f74a.png)
This is actually partially fixable if you change the display with the script disabled from the tile mode to the list mode(upper right corner of second screenshot has the switcher in question) which cause it to display seminormally
![](http://puu.sh/nrlpq/7738d0b36d.png)

**Comment by ErdeFB** [comment]
Disable grid subscriptions from the settings.

**Comment by raku-cat** [comment]
Thanks that fixed it
