### ISSUE TITLE
Can't see quality/frame rate anymore.

### ISSUE THREAD

**Issue by GrahamFinch** [YePpHa/YouTubeCenter#2200]
When I would mouse over a YouTube video, I could usually see the video's quality and frame rate. Recently, however, it doesn't seem to work. Now it just says "Error!" for everything. This is unusual, because YTC works correctly on one computer, but not the other.

I'm using the latest Dev Build (537) and Pale Moon 26.1.1.

**Comment by ErdeFB** [comment]
Does the other computer also use the same browser version?
Try resetting the settings and see if that helps.

Working fine on Chrome tho.

**Comment by GrahamFinch** [comment]
Yes, they're the same version.

**Comment by ccrowles** [comment]
I have the same issue, today it just started saying "Error!" in every video thumbnail of my subscriptions instead of the quality.

**Comment by AndrewPlacid** [comment]
This issue manifests itself when I logged in.

**Comment by Cnuut** [comment]
yeah this happened to me right now also :'(

**Comment by GrahamFinch** [comment]
Now the issue is happening to **both** of my computers. Great...

**Comment by thinkpad4** [comment]
Getting the same issue

**Comment by Morten79** [comment]
Thank you very much for fixing this little bug.

**Comment by Nicholas-Steel** [comment]
Nice to see this project still getting developed.

**Comment by unn76** [comment]
I'm really sorry but I'm having this issue as well and I'm not sure if I downloaded the correct xpi from yeppha's links or if I even did it correctly, because my thumbnails still say Error and there's no thumbnail animations either. Can anyone walk me through this please?

**Comment by Nicholas-Steel** [comment]
You want the beta Userscript version.

**Comment by unn76** [comment]
Is there a way you can link me to it, I don't think I'm looking in the right place. Thanks a lot

**Comment by Replads** [comment]
Before update no **errors**, after...

![](https://i.imgur.com/xvG3TL1.png)

I'm on firefox & greasemonkey (latest)

**Comment by Fofer** [comment]
Same here.  Mine was working before.  Just updated to #538 and now get "Error" instead of quality, in the upper right hand corner, on mouseover.

**Comment by Nicholas-Steel** [comment]
When I said Beta i meant Developer. You want the Userscript developer version and the latest Greasemonkey

**Comment by AndrewPlacid** [comment]
I do not have this issue in PC (extension or js version via tamper monkey), but in OS X still have in different browsers.

**Comment by Fofer** [comment]
Interesting, yes, I am on OS X 10.11.4, running Safari 9.1, with the developer version of this script installed via Tampermonkey.  The "error" didn't appear in #537, but it did appear once I updated to #538.

**Comment by unn76** [comment]
The userscript version seems to still have this Error issue

**Comment by neozero** [comment]
I got this error on Firefox with Greasemonkey and on Chrome with Tampermonkey. After updating to #538, it was fixed on Firefox, but the error still persists on Chrome (both on Windows).

**Comment by unn76** [comment]
Version 538 on Firefox and I'm still getting this Error/No thumbnail animation issue

**Comment by Dratas** [comment]
Version 538 crx file google chrome same youtube error on any youtube.com video like @Replads writed,earlier versions worked fine,but with last update is messed up.Waiting for fix.Pc with linux mint.

**Comment by alice0775** [comment]
To prevent getting the "Error":
In Version 538, You should log-in Youtube.
In Version 537, You should not log-in Youtube.
