### ISSUE TITLE
Small issue. Like / dislike buttons.

### ISSUE THREAD

**Issue by Puk4400** [YePpHa/YouTubeCenter#2205]
I remember i was somehow able to modify the color of the liked button on the comments and i really liked it in blue. Now, i reinstalled chrome because i had some issues and i can't find the option for like / dislike buttons for comments, if there ever were any.

I also use the "dark skin for youtube" extension.

**Comment by fishbiscuit13** [comment]
It's under UI, in the Like/Dislike Button tab.
