### ISSUE TITLE
Quality label is only showing Error now

### ISSUE THREAD

**Issue by thinkpad4** [YePpHa/YouTubeCenter#2208]
On all videos, latest dev version

**Comment by MacgyverJohnson** [comment]
me too

**Comment by Leifman27** [comment]
yep same here

**Comment by GrahamFinch** [comment]
There's already an earlier thread for this issue: https://github.com/YePpHa/YouTubeCenter/issues/2200

**Comment by MTStrothers** [comment]
Having the same problem myself.  Only broke a day or two ago for me.
