### ISSUE TITLE
A userscript wants to access a cross-origin resource

### ISSUE THREAD

**Issue by bobobo122** [YePpHa/YouTubeCenter#2224]
Every time I open a video on youtube a tampermonkey tab appears saying "A userscript wants to access a cross-origin resource". See attatched.
![crop](https://cloud.githubusercontent.com/assets/18016414/14248572/29188378-fa6d-11e5-8580-ade34f2cb3ec.png)

**Comment by trinsic** [comment]
Latest version of Tampermonkey wants to know whether a userscript is allowed to access a certain URL. This is done with @connect which is missing.

You can click Always allow (domain).
You can disable @connect mode in TamperMonkey settings if you wish. This is not recommended by TM.

The request goes away if you add @connect youtube.com to the userscript.

**Comment by bobobo122** [comment]
Ok thank you!
