### ISSUE TITLE
60fps not working when Dash Playback is disabled

### ISSUE THREAD

**Issue by ccrowles** [YePpHa/YouTubeCenter#2226]
As said above, if the dash playback is disabled the video does not show the 60fps options. Not only that, but it only shows 720p and 360p as available format. This goes for both video in the youtube site and embed videos. The moment I enable dash playback, I get the full resolutions options. The moment I disable it, only 720p and 360p. I have firefox dev version with full html support (everything is enabled in the html5 page of youtube)

dash disabled:
![screenshot03006](https://cloud.githubusercontent.com/assets/12866474/14315511/19f75c10-fbfe-11e5-8dce-39740d361e91.jpg)

dash enabled:
![screenshot03007](https://cloud.githubusercontent.com/assets/12866474/14315512/19fb2f48-fbfe-11e5-810e-2c58c34f2250.jpg)

**Comment by ErdeFB** [comment]
This is not a YTC issue as the mentioned video options are not available in non-DASH format on YT's side.

**Comment by ccrowles** [comment]
Damn, I did not know. Sad, but thanks for informing me.
