### ISSUE TITLE
Player Resize (button on the UI below on the right) Broken?

### ISSUE THREAD

**Issue by Leifman27** [YePpHa/YouTubeCenter#2275]
I noticed that suddenly no matter if i click on it, it won't switch to the "second setting" it should be (so from "default player size" (which i have a custom setting for) to the "large player size" (same)
Basically all i see when i hover it is it saying "Default View" and no matter how many times i click it, it remains in the "Default player size" and doesn't switch to my "Large player size" i have in the settings or any other player size to begin with.
Is it something known? pretty sure it started just today (yesterday i am pretty sure i clicked the button a few times to change it during the day and worked fine)

**Comment by Leifman27** [comment]
can no one confirm this happens/happened to them?

**Comment by NearCry91** [comment]
I have the same issue.

**Comment by LunarGaze** [comment]
This is also broken for me--I had to disable the script because it would not resize the player.

**Comment by Leifman27** [comment]
i am sure that when YePpHa has some time off his full-time work he will try and fix it

**Comment by joshsleeper** [comment]
Same issue here @YePpHa 
Thanks for the hard work so far!
Windows 10, Chrome 52.0.2743.82 (Official Build) m (32-bit)

**Comment by Pazns** [comment]
I found out that if the small size setting is the original standard "Small", then it works again.

**Comment by Marucins** [comment]
The project is dead?

**Comment by Pazns** [comment]
The sole maintainer seems to be out.
Feel free to participate.

**Comment by bobo1724** [comment]
Adding to this from what I can tell, small resize seems to work, but if you do change to small size, there's no way to change back other than refreshing the page (which goes back to default). 

When hovering over the resize button, it shows "Default View" no matter how many times you click it.

I think I've been just been living with the bug for a year or so, but anyways using Win10, Chrome 56.0.2924.87 (64-bit). Script is Dev build #544 installed through Tampermonkey.

**Comment by YePpHa** [comment]
See https://github.com/YePpHa/YouTubeCenter/commit/b049c2f92be0c0d5464336e8c6a4c28b3ac03eb3
