### ISSUE TITLE
YouTube comments stopped working/showing

### ISSUE THREAD

**Issue by danilaml** [YePpHa/YouTubeCenter#2294]
On every video I open it says that the comments are disabled. In incognito mode they work fine.

**Comment by danilaml** [comment]
I fixed it by disabling "show country" and other options for comments in YTC settings.

**Comment by Yonezpt** [comment]
It was a YouTube problem, nothing related to YouTube Center: 

https://www.reddit.com/r/youtube/comments/51s71f/anyone_else_getting_comments_currently_unavailable/

https://www.reddit.com/r/youtube/comments/51s700/youtube_comments_down/

https://www.reddit.com/r/youtube/comments/51s6sg/comments/

https://www.reddit.com/r/youtube/comments/51s9n5/comments_are_currently_unavailable_for_all_users/

**Comment by danilaml** [comment]
Oh , thanks. Try to google it but couldn't find any recent posts at the time.
