### ISSUE TITLE
YTC Not Being Enable'able in Chrome

### ISSUE THREAD

**Issue by Nordby9** [YePpHa/YouTubeCenter#2296]
Hi

When i installed the dev build on chrome, it was disabled by chrome. and it can't be re-enabled because the extension isnt in the chrome store.

YTC Version: 538
Chrome Version: 53.0.2785.116 m

**Comment by CollinChaffin** [comment]
This has been like this for YEARS.  You need to unpack it locally and yes, acknowledge the annoying bubble at chrome dev build startup with it enabled.  Period.  No other way.  This is not an open issue.

**Comment by Nordby9** [comment]
aha. that's sad.
