### ISSUE TITLE
Sooo ... will someone finally please declare this project dead ...

### ISSUE THREAD

**Issue by BiZZKeryear** [YePpHa/YouTubeCenter#2301]
Wiki page about one year no update,
developer page even longer, (referring to even older info)
And also about one year no updates.

Three quarters of a year ago things started to break ... but in a way you still could live with it.
Now things start to break down totally. Videos are not playing when YTC is enabled, stopping without reason in middle, and other fuck ups because youtube changed a lot and is currently still changing more.

And still no new version in sight.

## **This project is dead even if you say otherwise**

Every project I predicted dead ... and actually denied it ... turned out to be truly dead later ... like (as only one example of many) the multi monitor software I bought at the end of XP / beginning of Win 7 ... and hadn't had an update for a year or so at that time ... "No, No! It isn't dead! A Win 7 update with cool new features will follow very soon." ... and that didn't happen till today. (and never will)

And lets face it ... YTC will spiral more and more out of date ... even if it gets an update or two (I mean literally literally two updates) And yet even one update would take me by surprise.

# **_Sooo ... will someone finally please declare this project dead ..._**

**Comment by mbStavola** [comment]
Uh, what good does that do? 

This is kinda of a dick tone to take for something that's available completely free and libre. Is it really that inconveniencing to you that the author hasn't officially declared it defunct?

**Comment by BiZZKeryear** [comment]
Maybe I can at least one more update squeeze out of Jeppes pride.
In best case I get him to get some coauthers in the boat and release updates more often. ... and that before the code is so outdated that it is a train wreck that only can be totally rewritten.

**Comment by Yonezpt** [comment]
This kind of topic is not helpful. It will be closed for the moment until the author chooses to re-open it again.
