### ISSUE TITLE
Flashplayer skips to beginning if I try to skip to middle of video.

### ISSUE THREAD

**Issue by Purfekt** [YePpHa/YouTubeCenter#2303]
Hey there.

I have been recently having a problem w/ flashplayer and youtube center.

When I'm trying to skip ahead in a video by clicking the video bar thing, it goes back to the very beginning.
Even when I load the video is fully buffered/download, it still skips to the beginning if I click ahead past the middle of the video.

It's only happening on youtube, so I updated flashplayer and it didn't work.
I disabled youtube center just to see if I was still getting the issue, and that fixed the issue.
So it's definitely youtube center that's doing something to cause the videos to skip to the beginning.

Doesn't do it in HTML5, but I don't really prefer HTML5.
Never had this issue until yesterday.

**Comment by digideth** [comment]
I just started having this problem today myself.... along with the the 360p download just opening the video into a new tab instead of trigger the download box.

**Comment by Purfekt** [comment]
I managed to fix it.

In youtube center options, go to "Player" (under "General" on the left hand column) and make sure "DASH Playback" is checked. This should fix it.

**Comment by Purfekt** [comment]
I don't seem to have a problem w/ downloading videos at the moment. I also have the flash video downloader addon, which can substitute downloading videos if it were to ever go bad (the youtube center downloading function).

**Comment by digideth** [comment]
I'll try the dash setting... I got the FVD script installed too and it does the same thing... oh well.

thanks.

**Comment by Purfekt** [comment]
You might get some errors w/ flash not functioning here and there, never ending buffer, crash prompts, and random ETC errors. At least that's what I've noticed in the last couple hours.

**Comment by ErdeFB** [comment]
@digideth Can you verify the posted fix worked for you? Also when testing it, disable all other addons/scripts that modify YouTube.

Thanks.

**Comment by digideth** [comment]
@ErdeFB So far enabling Dash is working... I will update if I see any bugs.
