### ISSUE TITLE
It does not show video on YouTube

### ISSUE THREAD

**Issue by Egor2142** [YePpHa/YouTubeCenter#2308]
I istall YouTube Center 2.1.1. Google Chrome 54.0.2840.71 m.
And Video on YouTube not working. 
Is there sound, аnnotations, subtitles, All is, but no **VIDEO**! I have **black screen**. What to do? Please help my)
<a href='http://hostingkartinok.com/show-image.php?id=4deacd591e99d297230d2f78678c88ec' title='бесплатный хостинг картинок'><img src='http://s8.hostingkartinok.com/uploads/thumbs/2016/11/4deacd591e99d297230d2f78678c88ec.png' /></a>

**Comment by ErdeFB** [comment]
Version 2.1.1 is an obsolete version and should not be used by anyone. 
Instead, use the developer version which you can get here:
https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

It is mostly functional, but active development for the addon has ceased.

**Comment by Egor2142** [comment]
Thenx. I have new Problem) Whot does it meen?
<a href='http://hostingkartinok.com/show-image.php?id=b6bc31d9b97d5d095befaa412978410c' title='фотосайт'><img src='http://s8.hostingkartinok.com/uploads/thumbs/2016/11/b6bc31d9b97d5d095befaa412978410c.png' /></a>
