### ISSUE TITLE
Disable Video progress bar

### ISSUE THREAD

**Issue by raywu2478** [YePpHa/YouTubeCenter#2314]
Youtube has added a video progress bar under the thumbnail that I find distracting as the red bar covers the video rating bar. Is there a way to disable this from youtube center or move the ratings bar under the video progress bar?

Youtube's description of the feature
https://support.google.com/youtube/answer/7174115?hl=en

Screenshot to show what I'm talking about
![capture](https://cloud.githubusercontent.com/assets/8943426/20733913/106c8668-b664-11e6-8e01-91384e34dab9.PNG)

**Comment by Pezor** [comment]
Yeah, if you have Stylish addon installed, then just create a new style and copy paste this code.

`@namespace url(http://www.w3.org/1999/xhtml);
@-moz-document domain("youtube.com") {
  
  /* remove red bar */
  .resume-playback-background, .resume-playback-progress-bar {
    display: none;
  }
}`

**Comment by Pezor** [comment]
Yeah, if you have Stylish addon installed, then just create a new style and copy paste this code.

```
@namespace url(http://www.w3.org/1999/xhtml);
@-moz-document domain("youtube.com") {
  
  /* remove red bar */
  .resume-playback-background, .resume-playback-progress-bar {
    display: none;
  }
}
```

**Comment by HowellBP** [comment]
@Pezor Doesn't seem to work. Is there anything else I need to do? I'm not very familiar with javascript so just poking around at the page layout in the console isn't helping me.

**Comment by Pezor** [comment]
@HowellBP Oh, it's not a javascript code, it's just a simple CSS style. Depending on your browser you will need to download a Stylish addon. Here's a little guide (I'm using the latest version of Firefox).
1. Download the addon for your browser from here ([Stylish for Firefox](https://addons.mozilla.org/en-US/firefox/addon/stylish/?src=external-userstyleshome), [Stylish for Chrome](https://chrome.google.com/webstore/detail/fjnbnpbmkenffdnngjfgmeleoegfcffe), [Stylish for Safari](http://sobolev.us/stylish/), or [Stylish for Opera](https://addons.opera.com/extensions/details/stylish/)).
2. Go to the Firefox's addons manager then choose User Styles. ([Image](http://i.imgur.com/cY6ZqJs.jpg))
3. Write new style and save ([Image](http://i.imgur.com/qKlEfuX.png))
4. Before/After for me ([Image](http://i.imgur.com/xAIU8qD.jpg))

Hope this helps!

**Comment by HowellBP** [comment]
@Pezor Oh I did all that but I still see the red progress bar. Do I need to clear my cache or cookies or something?

**Comment by Pezor** [comment]
@HowellBP Hmm, that's weird, you don't really need to clear your cache or cookies at all. Changes should be immediate. I have no idea why it's not working for you.

**Comment by HowellBP** [comment]
@Pezor Aha I figured it out. Since I'm using Chrome, I had to import the code you put here as "Mozilla Format" which converted it to the correct style for the Chrome version. Now it works, and yes, it was immediate. Thanks a lot.

**Comment by Pezor** [comment]
@HowellBP Glad it helped!

**Comment by YePpHa** [comment]
An option has been added to disable the resume playback bar (see https://github.com/YePpHa/YouTubeCenter/wiki/Features#Hide_Resume_Playback_Bar).
