### ISSUE TITLE
Only 2 resolution options with DASH Disabled - No 1080, 1440 or 4k options

### ISSUE THREAD

**Issue by The-Euphoria** [YePpHa/YouTubeCenter#2315]
Hello, I realise this has been mentioned already regarding there being no 1080p option with DASH disabled, but I also wanted to add that there is no 1440 or 4k options either.
Seamless 4k playback requires a pretty fast connection, above what any ADSL line can provide, so if YouTubeCenter could be updated and modernised to allow 1440 and 4k options with DASH disabled to allow users to pre-load (buffer) the entire video, that would be fantastically amazing.

Kudos to you for this add-on, good stuff 👍

**Comment by ErdeFB** [comment]
You cannot write the addon to support those video formats, because they do not exist on YouTube servers to begin with. Sorry.

**Comment by The-Euphoria** [comment]
Oh ok, sorry I wasn't aware of that. Thank you for the super fast reply.
