### ISSUE TITLE
Abandoned (contains an suggestion for alternative addon)

### ISSUE THREAD

**Issue by ddd111ddd** [YePpHa/YouTubeCenter#2324]
Since development halted, what's the future of this extension? Is there any popular fork or any other plans?

Unfortunately the new YouTube layout doesn't work with this extension.

I'm grateful that it worked so far, I've been using it for years!

**Comment by thinkpad4** [comment]
I would love to see this forked

**Comment by Fironet** [comment]
> Unfortunately the new YouTube layout doesn't work with this extension.

Been experiencing this off and on over the last couple months but today Youtube has finally rolled out the new design that completely breaks with YT Center active. Great shame.

**Comment by thinkpad4** [comment]
If someone would kindly fork this I would be very grateful

**Comment by ArJunaZ** [comment]
YePpha, Please resurrect this project to work with the current YouTube.  This has been such a valuable tool for my research and record keeping of the Satanic New World Order.

**Comment by Yonezpt** [comment]
Please read what the developer already explained: https://github.com/YePpHa/YouTubeCenter/wiki#status-of-youtube-center

> As of many of you know. I have not been actively developing on YouTube Center and there's a good reason for that. I have acquired a full time job, which leaves not much time for development. However, if a major bug occurs, because of some change in YouTube. I will try to fix it in a relatively small time frame.

> Moreover, I will will not stop developing on YouTube Center indefinitely and there might be some future surprises.

Moreover the license does allow others to fork if they wish to: https://github.com/YePpHa/YouTubeCenter#license

Begging will not make it happen, developers will fork a takeover if they are interested which I doubt it will without having to rebuild everything from scratch.

Any other kinds of questions requesting alternatives would be more appropriate in other places except in this issue tracker.

**Comment by Keith94** [comment]
>Is there any popular fork or any other plans?

Check out YouTube + (codename Particle): https://github.com/ParticleCore/Particle

The project was inspired by YouTube Center, and it's actively maintained. It's what I use currently.

**Comment by Maverynthia** [comment]
YT+ however doesn't work on older Firefox for those of us that don't want to deal with the whole signing thing.

**Comment by Keith94** [comment]
@Maverynthia You may be able to override that, see here: http://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/

**Comment by Maverynthia** [comment]
OK I tried particle and it seems to leave out the main reason I use YT center and that's resizing the video on the page. I see some float and pop-out, but that's not what I want to do. :c

**Comment by Yonezpt** [comment]
@Maverynthia let's keep this issue tracker for issues related to YTC, not for other projects. If you want help with that perhaps it would be best to either read its features list or post in their issue tracker instead.

**Comment by ireun** [comment]
And.. It's alive again. ;)
