### ISSUE TITLE
version 540 contains number 538 instead of 540

### ISSUE THREAD

**Issue by andrey-mikhaylov** [YePpHa/YouTubeCenter#2338]
vivaldi (chrome)

**Comment by andrey-mikhaylov** [comment]
update to version 540 message appears in every video
updating to 540 (load unpacked extension)
version is now... 538
update to version 540 message appears in every video
...

**Comment by viller239** [comment]
There is a chance that crx file was not rebuild for 540 (looking at https://github.com/YePpHa/YouTubeCenter/tree/master/dist last modification dates)

**Comment by nexces** [comment]
Commit message 7995bd539916af3550599ebdfc3751fbb00585cb clearly states that Chrome version was not compiled.

**Comment by H3llt3ch** [comment]
So can we fix that ourselves?

**Comment by Juliannico111** [comment]
Hey, 
just open YouTubeCenter.js with notepad++ etc. and search for "538"
You will find 3 results. 
Step to the second it schould be the line:

		fn += "(true, 1, true, 538)";

Change to 

		fn += "(true, 1, true, 540)";

Save
Delete extension in chrome and readd the modified

**Comment by levak69** [comment]
someone can fixed file .crx for Opera?

**Comment by Juliannico111** [comment]
Try this..
Remember, it's not the dev preview 540! 
Only 538 without the warning.

[YoutubeCenter.zip](https://github.com/YePpHa/YouTubeCenter/files/757997/YoutubeCenter.zip)

**Comment by Uthuriel** [comment]
Thank you but I can deactivate the update warning in the extension itself. I'd prefer the real v540.

**Comment by ColtaineCrows** [comment]
@Uthuriel You can disable the Update Checker in the YTCentre settings. Under the "Update" tab. At least that removed the yellow box for me.

**Comment by Uthuriel** [comment]
That's exactly what I did.

**Comment by levak69** [comment]
@Juliannico111  Ok, but then I know when a new version was released, if updates are disabled?

**Comment by YePpHa** [comment]
I found the certificates that I used to compile the crx file. So the latest crx file should be up-to date. See https://github.com/YePpHa/YouTubeCenter/commit/911c3a3391cbccef4b7161b16817c3f5352cf572
