### ISSUE TITLE
Where's the dev download? Update message links to v538.

### ISSUE THREAD

**Issue by Kilva** [YePpHa/YouTubeCenter#2340]
Currently at 542, I've been looking for the 540 and 541 downloads but they're not being updated I suppose.
Is this on purpose? The update message on every YouTube page is getting real annoying.

**Comment by YePpHa** [comment]
https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by Kilva** [comment]
Ah, you've updated the link now! Thank you.

**Comment by Kilva** [comment]
Ah, you've updated the link listed there now. Thank you!
