### ISSUE TITLE
video quality and fps shows [error!] in Edge

### ISSUE THREAD

**Issue by sdsucks** [YePpHa/YouTubeCenter#2342]
windows 10 x64 1607 RS1
video quality/fps doesn't show on thumbnail it shows error! instead

**Comment by NiGHTsC** [comment]
Are you log on your youtube account?

**Comment by sdsucks** [comment]
yes, I am most of the time. but does it matter?

**Comment by YePpHa** [comment]
It shouldn't matter. I would think the issue is that in Edge it can't connect to Google's API. I will need to investigate this however.

**Comment by MikeZeDev** [comment]
FYI i have the same problem on FF 51.0.1 emefree, x64, Windows.

And i am NEVER connected to my google account.

I will try messing with my extensions / Firefox profile to see if there is a conflict

**Comment by NiGHTsC** [comment]
no it shouldn't, but this only happent when I'm not log on.

**Comment by MikeZeDev** [comment]
So i tried on a fresh profile, with just GM and the dev build. Still having the problem.
Those are the console errors when i put my mouse hover a suggested video

> 17:40:45,981 Player configurations not found in spf. 1 YouTubeCenter.js
	
	con[key] YouTubeCenter.js

	loadVideoConfig/<.onload YouTubeCenter.js

	eventResponse YouTubeCenter.js


null

TypeError: cfg is null
loadVideoConfig/<.onload@YouTubeCenter.js:4805:17
eventResponse@YouTubeCenter.js:10514:11

[VideoThumbnail Quality] IO Error => Error!  YouTubeCenter.js
	con[key] YouTubeCenter.js
	loadVideoConfig/<.onload YouTubeCenter.js
	eventResponse

**Comment by YePpHa** [comment]
See https://github.com/YePpHa/YouTubeCenter/commit/3629a432450676aa7229657984a83032e2b80478
