### ISSUE TITLE
Red & gray line at the bottom of the thumbnail

### ISSUE THREAD

**Issue by p1nkyy** [YePpHa/YouTubeCenter#2343]
What is the red and/or gray line at the bottom of video thumbnail and how do I remove it?
I thought it has something to do with 'rating bar' but I have disabled it (for the video thumbnail) and it's still there.

http://puu.sh/tTeSg/cbfab40625.jpg

http://puu.sh/tTeRD/a19aad4314.jpg

**Comment by Yonezpt** [comment]
It's the new YouTube "WATCHED" layout. Instead of showing the overlay with the usual text, it now shows that red bar which also indicates how far you watched that video. Nothing to do with YTC.

**Comment by joridiculous** [comment]
Its a like/dislike bar.
`<div class="video-extras-sparkbars" style="height: 2px; position: absolute; bottom: 0px; left: 0px; width: 100%;"><div class="video-extras-sparkbar-likes" style="background: rgb(85, 153, 0); height: 2px; width: 100%;"></div><div class="video-extras-sparkbar-dislikes" style="height: 2px; background: rgb(255, 0, 0); width: 0%;"></div></div>`

You can remove it with stylish using: 
`.video-extras-sparkbars {
    display: none;
                    }
`

**Comment by Yonezpt** [comment]
@joridiculous It is not the like/dislike bar

https://www.reddit.com/r/youtube/comments/58q7qf/woke_up_to_this_red_line_underneath_videos/

https://www.reddit.com/r/youtube/comments/550xmf/does_anyone_know_what_these_red_lines_mean/

https://productforums.google.com/forum/#!topic/youtube/32Wspif5Ca8

**Comment by joridiculous** [comment]
I had one red / gray bar on my thumbs. The like/dislike bar Just as in OPs screenshots. Removed it with the paste up there. 
Snaps: 
Bar present: http://imgur.com/WaaBlJx
Bar gone:     http://imgur.com/SIjIOeC
The bar you are talking about is another one.

**Comment by p1nkyy** [comment]
OK, thank you for all the input & suggestion. Tried making a Stylish based on @joridiculous's suggestion and apparently it's gone!

**Comment by Yonezpt** [comment]
@joridiculous If you watch the actual ratingbar of the first videos in OP's screenshot you'd understand they are not the same, the sizes have nothing in common, thus confirming that those are watched time bars, not rating bars:

https://www.youtube.com/watch?v=BS7tz2rAOSA

The bars you show in your shots are red and green, they happen to have common elements, but they are not the same. If OP wants the watched mark he will no longer have it when using those hiding rules, unless that's not something important to him.

**Comment by p1nkyy** [comment]
I am a 'she' @Yonezpt and you are correct, the red bar re-appear again.

**Comment by Yonezpt** [comment]
Sorry for the gender mixup, but I usually make no distinction when referring to the original poster. You'll have to right-click that red bar and see the class names for those elements, those are the ones you'll have to use in Stylish instead of `video-extras-sparkbars`

**Comment by YePpHa** [comment]
I think it should be possible with CSS:
```CSS
.resume-playback-background,
.resume-playback-progress-bar {
  display: none;
}
```

I will probably add an option later today which applies this.

**Comment by joridiculous** [comment]
@p1nkyy Then you can put in this code to: 
`  .resume-playback-background, .resume-playback-progress-bar {
    display: none;
  }`
Keep both codes and both red-bars is gone. (This code alone will *not* remove the like bar!)
