### ISSUE TITLE
A new developer build is available.

### ISSUE THREAD

**Issue by tracker1** [YePpHa/YouTubeCenter#2344]
The link points to the version I'm using, and cannot find builds of the latest... the message is annoying, and haven't setup a build for this project to do it myself.

**Comment by YePpHa** [comment]
Look at https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version the links should be up-to date except for the Safari one.

**Comment by Marucins** [comment]
Yeeeee he is alive!
Thanks ;)

**Comment by q1k** [comment]
Is there any changelog for these past updates?

**Comment by YePpHa** [comment]
Look at https://github.com/YePpHa/YouTubeCenter/commits/master

**Comment by tracker1** [comment]
I updated to the version in question at that link, but I'm still seeing the notification message.

**Comment by YePpHa** [comment]
@tracker1 what link are you using?
