### ISSUE TITLE
View counter/rating bar and like/dislike buttons overlaping

### ISSUE THREAD

**Issue by kilara1988** [YePpHa/YouTubeCenter#2352]
I am using the **YTC Settings->UI->Placement->Move elements** option to move/disable some of YTC buttons.This exposes a placement bug where the view counter/rating bar and the like/dislike buttons are overlapping.

1. When YTC is disabled the rating bar(and view counter above it) are aligned with the line that separates the channel logo/subscriber counter and the default YouTube Share/Add to/More buttons. 
![ytc disabled](https://cloud.githubusercontent.com/assets/1025376/22753393/a0065aac-ee44-11e6-80b8-aca75209955c.png)

2. When YTC is enabled and you place the buttons so that you have 2 rows, the rating bar/view counter and like/dislike buttons are not overlapping.Note however that the rating bar/view counter is no longer aligned above the separating line and now is below the line, and the like dislike buttons are aligned with the bottom row.
![ytc enabled 2 rows](https://cloud.githubusercontent.com/assets/1025376/22753627/7844d27c-ee45-11e6-83a2-16857bc1ba80.png)

3. When YTC is enabled and you place the buttons so that you have only 1 row or you disabled all YTC buttons and leave only the YouTube default buttons,the rating bar/view counter and like/dislike buttons are now overlapping.
![ytc enabled 1 row](https://cloud.githubusercontent.com/assets/1025376/22753805/16868cbe-ee46-11e6-95be-8669deb9af8c.png)

It seems that the position of the rating bar/view counter is fixed directly below the separating line,but the like/dislike buttons are aligned with the rows and you can move them(you can't move the rating bar/view counter).So when you have only one row the like/dislike buttons are aligned with that row and they overlap the fixed position of the rating bar/view counter.

I am using FF 52 Beta 4 on Win 10 x64 with YTC #544 script.

**Comment by YePpHa** [comment]
See https://github.com/YePpHa/YouTubeCenter/commit/b39931b5a6391af6e4c9966aff8d1162cc910ae1

**Comment by kilara1988** [comment]
I just got the update to v545,but i didn't see the fix for this bug included in it and i still face this bug.

**Comment by YePpHa** [comment]
Weird, I tested it and it seemed to work.

**Comment by YePpHa** [comment]
Found the issue. I will send out a new update.
