### ISSUE TITLE
dosn't apper to work on palemoon

### ISSUE THREAD

**Issue by Doomdoging** [YePpHa/YouTubeCenter#2363]
this use to work till a few days ago on the palemoon browser a Firefox based browser

**Comment by YePpHa** [comment]
I assume you're using the extension version as Greasemonkey doesn't appear to be available on Pale Moon (at least the latest version of Greasemonkey).

**Comment by YePpHa** [comment]
Issue occurred because it didn't support something Firefox supported.

**Comment by Ghosthree3** [comment]
Working for me in Pale Moon using janekptacijarabaci's forked Greasemonkey 3.9 just fine. Was working with official GM 1.1.5 for a long time before that but it may be broken now.

**Comment by YePpHa** [comment]
@Ghosthree3 It probably worked with GM, but with the actual extension it didn't.
