### ISSUE TITLE
Playlist under Video

### ISSUE THREAD

**Issue by Audipower** [YePpHa/YouTubeCenter#2365]
Hello i use Firefox 51 and Version 548 and Video is over Playlist 

https://dl.dropboxusercontent.com/u/1390692/Bild.png

And some Sound Problems on Videos with Playlist sound is doubel wit 2 seconds delay

**Comment by NiGHTsC** [comment]
It's like only 3posts below.
https://github.com/YePpHa/YouTubeCenter/issues/2360
