### ISSUE TITLE
Stop updating the Developer Edition every single day

### ISSUE THREAD

**Issue by dfhg45645ag** [YePpHa/YouTubeCenter#2366]
It is incredibly annoying to see the pop-up of a 'new edition is available' every single time I open up the browser.

**Comment by NiGHTsC** [comment]
Disable auto-update?
Weirdest request i've ever seen.

**Comment by harveyadcock** [comment]
I'm just glad it's getting updated again! As NiGHTsC says, disable the update checked by disabling the checkbox located at settings->update->general->enable update checker

**Comment by Yonezpt** [comment]
You can disable the update checker if you wish to stop it: https://github.com/YePpHa/YouTubeCenter/wiki/Features#Enable_Update_Checker

You can also increase the update check interval if you want it less often: https://github.com/YePpHa/YouTubeCenter/wiki/Features#update-interval-1
