### ISSUE TITLE
Only 720p available

### ISSUE THREAD

**Issue by Symbai** [YePpHa/YouTubeCenter#2370]
I've set default resolution to 1440p which has worked few versions ago.
Now all YT videos have maximum 720p. When I try to select a higher solution manually it has a menu item "Are you looking for other quality settings?"

When I disable the YT Center script I have all resolutions available including 1440p. With enabled script only 720p.

**Comment by kilara1988** [comment]
Check to see if you have DASH enabled in YTC.When DASH is disabled you only get up to 720p.

**Comment by Symbai** [comment]
Thanks that did the trick. Annoying the Wiki doesn't tell anything about (at least not that 1440p is missing as well).

**Comment by YePpHa** [comment]
I'll update the wiki to include that part.
