### ISSUE TITLE
how to download old versions of developer versions

### ISSUE THREAD

**Issue by shaun90800** [YePpHa/YouTubeCenter#2383]
Hello there 
Could you please tell me how to download old versions of developer versions?

Thanks

**Comment by ireun** [comment]
Sure, You would need to go to the respective commit, (here for example: https://github.com/YePpHa/YouTubeCenter/commit/3629a432450676aa7229657984a83032e2b80478) look for a file that you're looking for (with extension that your browser uses) and download it..

Here is a video of that, If you would have some trouble..
https://s1.webmshare.com/vObRB.webm
