### ISSUE TITLE
Youtube center broke my subscription box

### ISSUE THREAD

**Issue by DimensioX1** [YePpHa/YouTubeCenter#2384]
After i installed youtube center my subscription box looks like this
http://oi63.tinypic.com/dobdqo.jpg
It doesn't happen when I look at other channels, playlist or in any other places, only in my subscription box.

**Comment by ireun** [comment]
Well.. I can't reproduce it, aren't you using some YouTube beta mode? Are You using newest DEV build?

![image](https://cloud.githubusercontent.com/assets/695818/23438554/a4bc2774-fe12-11e6-8029-eaeb7add8bf3.png)

**Comment by DimensioX1** [comment]
I am using the latest version, and i'm not using any youtube beta mode.
The only thing i am using is this stylish script to force youtube to go in full screen, but i tried turning it off and the problem is still there so i don't think it has anything to do with it, it's a problem caused by youtube center.
![cattura](https://cloud.githubusercontent.com/assets/17047474/23441063/59c89262-fe20-11e6-9032-71b2319997a7.PNG)

**Comment by Yonezpt** [comment]
I believe you have the grid layout enabled for the subscription pages (YTC option) which is having a conflict with YouTube's own grid layout. Solutions are to either turn off the grid layout in YTC or disable that option temporarily, switch your subscription layout inside YouTube to list (right top corner buttons) and then re-enable the grid layout in YTC.

Notice the 2 icons in the top right corner of @ireun subscription list? Those belong to YouTube and they allow you to switch layouts without the help of YTC, although their grid layout is still not that great, you can switch it to list and enable the grid in YTC if you want.

**Comment by DimensioX1** [comment]
Yes that was the problem, now i fixed it, thanks.
