### ISSUE TITLE
Please provide signed Firefox builds

### ISSUE THREAD

**Issue by Nicholas-Steel** [YePpHa/YouTubeCenter#2434]
Now that development has slowed significantly due to various reasons, would it be too much of a bother to have the current developer version verified/digitally signed/certified so it can be installed on new Firefox?

**Comment by Yonezpt** [comment]
As much as doing it yourself, which you actually can if you want to. Add-on sign-in on AMO is relatively simple and doesn't take more than 1 minute, as long as it is isn't for publishing on their store.

**Comment by Nicholas-Steel** [comment]
Could you explain how to do it, or link to a good source of information on the process?

**Comment by Yonezpt** [comment]
https://developer.mozilla.org/en-US/Add-ons/Distribution#Self-distributed_(unlisted)_versions

If you find any errors then you might understand why no one decided to "bother" signing an extension that can't be signed until all of those errors are fixed.

For more see here: https://github.com/YePpHa/YouTubeCenter/issues/2141#issuecomment-166273803

**Comment by Nicholas-Steel** [comment]
Thank you for the link.

**Comment by Nicholas-Steel** [comment]
For people wondering, here is how you can disable signature enforcement of Extensions (for now): https://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/
