### ISSUE TITLE
Can we donate money?

### ISSUE THREAD

**Issue by ackern** [YePpHa/YouTubeCenter#2442]
Is there a way to donate money? For years YouTubeCenter has been my #1 most important extension along with ad blockers and every day I am thankful it exists. Now the new Youtube design has finally motivated me to find out if we can donate. Just as a way to say thank you. I don't need any promise that it'll speed things up.

**Comment by raaomoka** [comment]
Yeah, simply open the settings and there's a donate tab to the left.

**Comment by YePpHa** [comment]
That's correct. I don't accept any donations because I'm not actively working on YouTube Center and I wouldn't feel right if I did. Anyways, if you want to donate you should donate to a charity instead as your money then will go to a good cause instead of into my pockets.
