### ISSUE TITLE
youtube won't approve me for monetization

### ISSUE THREAD

**Issue by stephilee** [YePpHa/YouTubeCenter#2477]
i'm not sure if this is the correct forum to be posting this in, but i went to the Youtube Space in LA today and they told me to come here. I've been trying to get my account approved for monetization for months. I've had almost 4 million views this month and i have over 60k subscribers. is there anything i can do to speed up this process?

**Comment by YePpHa** [comment]
This place is not the place to discuss this as this is no way related to Google or YouTube in any way. I would suggest you to take it to their [forums](https://productforums.google.com/forum/#!forum/youtube).
