### ISSUE TITLE
Video doesn't start.

### ISSUE THREAD

**Issue by MarlonAndradee** [YePpHa/YouTubeCenter#2481]
As you can see in the image, the video doesn't start, there's only a black window appearing where the video should be.

**I'm using:** Firefox Quantum 60.0b11 (64-bit) and Youtube Center Developer version with greasemonkey.

![screenshot-2018-4-11 speak english fluently pronunciation the word them pronunciation guide](https://user-images.githubusercontent.com/28205246/38648399-66ad2e88-3dc7-11e8-9907-393c499fbd15.png)

**Comment by pingufetch5** [comment]
Getting the same thing here. Windows 7 Firefox Userscript.

**Comment by Orbilo** [comment]
same problem here.

**Comment by Coffeeist** [comment]
Yep, same issue here, using Vivaldi (Chrome version of the addon)

**Comment by NiGHTsC** [comment]
This just happent on me as well, Win7 64bit+FF55.0.3+YTCenter v548

Seriously hoping this is Youtube itself's issue and will be fixed ASAP

**Comment by Fallen10111** [comment]
I had this. It worked an hour ago when I got in from work. Went to watch a video now, not working. I disabled Youtube Center, worked fine. I think it's an update they've done youtubes end maybe.

**Comment by flakzilla** [comment]
Same issue, FF56 on linux w/ greasemonkey. Everything works normally if I turn off greasemonkey so it's definitely a problem with YTC. Apparently youtube won't let you restore the old layout either... this might be the end, lads. Save us @YePpHa!

**Comment by 9aaron** [comment]
Same. Resetting YTC settings doesn't work either.

**Comment by LamerGamer** [comment]
Had the same issue. Didn't work when installed through Chrome, but Tampermonkey worked, strangely.

**Comment by GuyB01** [comment]
Same as @LamerGamer - The Chrome extension's stopped working but the Violentmonkey script works.

**Comment by valarnin** [comment]
Quick fix is to change the way window.matchMedia is getting overridden.
I'm running one of the dev builds for Chrome, here's what I did:
There are two spots in YouTubeCenter.js where window.matchMedia gets set to null. This needs to be changed to instead set to a function that returns false.
For me, I changed line 11061 from:
```javascript
          window.matchMedia = null;
```
to:
```javascript
          window.matchMedia = function(){return false;};
```
And line 26853 from:
```javascript
	  injectScript(function(){ window.matchMedia = null; }, "matchMediaOverride.js");
```
to:
```javascript
	  injectScript(function(){ window.matchMedia = function(){return false;}; }, "matchMediaOverride.js");
```

**Comment by texaskelly** [comment]
Can confirm that valarnin's edit works.

Hopefully we get an official update to the script real soon, although given that there's seemingly been no development for months on this, I'm guessing we shouldn't hold our breaths.

**Comment by NiGHTsC** [comment]
@valarnin: Thank you Thank you!

YeP is working on new YT script, gonna take a while but he's on the new project.

**Comment by valarnin** [comment]
If I wasn't extremely sick and had the energy to do more than just watch YT, I'd format a proper PR or upload fixed builds or something. But I'll leave that to someone that's not currently hacking up their lungs.
For those who can manage to apply the fix themselves, enjoy.

**Comment by bhrgunatha** [comment]
@valarin Get well soon and a big thanl you - youtube is so unpleasant without YTC!

**Comment by MarlonAndradee** [comment]
Thank you so much, it worked!

**Comment by dertrance** [comment]
@valarnin Thank you so much for the edit, it worked flawlessly!

**Comment by ccrowles** [comment]
The edit works on firefox too! Thank you so much!

**Comment by adnieman** [comment]
I run FF59 with ViolentMonkey and I made the edits, but it doesn't work... Thanks for trying, though.

**Comment by adnieman** [comment]
Can confirm valarnin's fix works in FF59 with ViolentMonkey.

**Comment by Hampster82** [comment]
Thanks for the fix from here as well.

**Comment by YePpHa** [comment]
@ericboehs the reason for this is because I was stupid and didn't add the `dist` folder to the `.gitignore` file.
