### ISSUE TITLE
Black window where player should be

### ISSUE THREAD

**Issue by Vadigor** [YePpHa/YouTubeCenter#2483]
Sometime in the past 24 hours a presumed YouTube update broke YouTubeCenter completely. Instead of rendering the player, it just draws a black screen. Type of player selected or other options don't seem to matter.

Console shows:

```
TypeError: window.matchMedia is not a function[Learn More]  base.js:7279:111
	<anonymous> https://www.youtube.com/yts/jsbin/player-vflRhCLRy/en_GB/base.js:7279:111
	<anonymous> https://www.youtube.com/yts/jsbin/player-vflRhCLRy/en_GB/base.js:1:20
TypeError: content is null[Learn More]  watch:23059:11
	resize YouTubeCenter.js:23059:11
	ytcenter.player._resize YouTubeCenter.js:23280:16
	ytcenter.player._updateResize YouTubeCenter.js:22918:9
	mutationCallback YouTubeCenter.js:2485:11
TypeError: window.matchMedia is not a function[Learn More]  base.js:7279:111
	<anonymous> https://www.youtube.com/yts/jsbin/player-vflRhCLRy/en_GB/base.js:7279:111
	<anonymous> https://www.youtube.com/yts/jsbin/player-vflRhCLRy/en_GB/base.js:1:20
TypeError: uw.yt.player is undefined[Learn More]  watch:10870:11
	load YouTubeCenter.js:10870:11
	onload
```

I realise that maintenance on this was stopped so I don't expect we'll get an official fix for this, but perhaps a workaround can be found.

**Comment by YePpHa** [comment]
Someone made a [PR](https://github.com/YePpHa/YouTubeCenter/pull/2482) which is now compiled. Go to https://github.com/YePpHa/YouTubeCenter/tree/master/dist and install the new version.

**Comment by ShamblerDK** [comment]
The one for Chrome is version 548 still :-)

**Comment by YePpHa** [comment]
@ShamblerDK I seem to have forgotten to use the certificate.

**Comment by Vadigor** [comment]
Ah, didn't realise the Issue page filtered out closed ones. This is a duplicate of [2481 ](https://github.com/YePpHa/YouTubeCenter/issues/2481) which is now fixed in build 549.

**Comment by Vadigor** [comment]
Duplicate of #2481

**Comment by ThoBekMic** [comment]
@YePpHa Tak :-)

**Comment by Green45** [comment]
The Maxthon version appears to be build 548, too.

**Comment by YePpHa** [comment]
@Green45 as far as I can see https://github.com/YePpHa/YouTubeCenter/raw/master/dist/YouTubeCenter.mxaddon is build 549.

**Comment by Green45** [comment]
Claims to be Build 548 when I check the "about" info on YouTube. Additionally, it still has the "black screen only"-bug, which I assume was meant to be fixed in 549 for all browsers?

**Comment by YePpHa** [comment]
@Green45 perhaps there's a caching issue in Maxthon. Have you tried to uninstall the extension. Close the browser. Open the browser and install the new version?

**Comment by Green45** [comment]
Turn it off and turn it back on again, in other words.

And you know what? It worked. It ALWAYS works.

**Comment by YePpHa** [comment]
@Green45 glad to be of some help :)
