### ISSUE TITLE
YC deletes quality options

### ISSUE THREAD

**Issue by VasVadum** [YePpHa/YouTubeCenter#315]
youtube center removes half the resolution options for playing video.  Here is a screenshot of one of my videos on youtube both without and with Youtube Center.

![youtubecenterbroken](https://f.cloud.github.com/assets/1490797/2177472/cc14844e-961c-11e3-9702-b99653abf9ef.png)

As you can see, it removes 1080p, 480p, and 144p.  Though, no one cares about 144p, the other 2 are quite standard and great things to have.  It's almost enough that I don't want to use youtube center anymore because of the removal of 1080p.  I have no clue what causes this either.
You can also sort of see another bug in the image, but it's not all that important.  YC has a 1 second difference in the video max time.  :P  But meh.  I just want my 1080p and 480p options back.

If you need some info like my settings or browser plugins and such, just ask.

**Comment by Maxxee** [comment]
All claims that this is default behavior are lies.
YouTubeCenter definitely *DOES BREAK* many available resolutions, like 1080p.
This is a fact which nobody can deny.

**Comment by ErdeFB** [comment]
@Maxxee This is not a conspiracy forum. Please do not necro old and closed issues without a reason.

**Comment by Maxxee** [comment]
Yes, and this was very true for former versions of YTC, so now what wannabe-smartie?

**Comment by Zarggg** [comment]
ErdeFB has no issues with tone or language in his reply. A "fact nobody can deny" is that YouTube requires [DASH playback](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) for certain stream qualities. YTC is only "breaking" functionality in the sense that it operates as if one were using a browser that does not support DASH in the first place. The option to disable the fature was added when DASH was still experimental and prone to issues. Furthermore, it would serve no purpose if YouTube decides to remove non-DASH streams at some point in the future.

As of last April, [five major browsers support the format](http://stackoverflow.com/questions/22292224/which-web-browsers-support-the-mpeg-dash-streaming-protocol/22787831#22787831) and YouTube has developed their implementation to the point where it is now YouTube's default functionality. There's no reason to continue beating this dead horse.
