### ISSUE TITLE
Progress bar displays incorrectly

### ISSUE THREAD

**Issue by smasher816** [YePpHa/YouTubeCenter#349]
Recently when watching videos the progress bar will fill-in ahead of the current position.

Edit: Confirmed to happen on both chromium and firefox using the HTML 5 player on Linux.

![image](https://f.cloud.github.com/assets/904012/2305540/b9479590-a25b-11e3-9dc5-4251de6f5b10.png)

**Comment by DaAwesomeP** [comment]
I am seeing this problem in FF36. YouTube now enables HTML5 by default, so this should be fixed.

Pressing the large/small button seems to put it into "Theater mode" where the progress bar and annotations are too wide (hidden as they are too big for the container).

I originally thought that this was a problem with Youtube: [HTML5 Player Issue: Progress bar does not scale with player](https://productforums.google.com/forum/?hl=en#!category-topic/youtube/playing-and-watching-videos/report-a-technical-issue/firefox/nRsbb11Cank)

**Comment by YePpHa** [comment]
@DaAwesomeP What version of YouTube Center are you using? If you're not using the [developer version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version), it might be the issue you're having. Also, I will close this issue as this is an older discussion.

**Comment by DaAwesomeP** [comment]
I updated to the dev version and that fixes it. This is a very significant bug though, so it should be pushed to a release version.
