### ISSUE TITLE
Maxthon & Firefox

### ISSUE THREAD

**Issue by v8commodore** [YePpHa/YouTubeCenter#373]
If I open a youtube video in maxthon and the video setting is default, it loads the html version by default, and if i set to flash default it won't play.
But if i open the same video in firefox and the video setting is default it plays the flash player version. 
example link- https://www.youtube.com/watch?v=X9vZLYMoTCQ&list=PLcAFCEDZU39xYLamb1NBGW_14DrieamN2

**Comment by ireun** [comment]
If you still got this issue please open a new one.. ;)

*Closing..*
