### ISSUE TITLE
[Issue] No quality options on YC Flash player.

### ISSUE THREAD

**Issue by aznskillz336** [YePpHa/YouTubeCenter#378]
![screenshot](https://cloud.githubusercontent.com/assets/7110146/2562748/084a7fb4-b85e-11e3-9bde-dcc667896cb4.png)

Is there a way to either get around or fix this?

**Comment by ireun** [comment]
If this issue still exist please download DEV version of this script (Look at the wiki). And if it would still occur, please create a new issue. :)

*Closing..*
