### ISSUE TITLE
Safari v.2.1.0 black error screen

### ISSUE THREAD

**Issue by bbrasfie** [YePpHa/YouTubeCenter#390]
When opening a video there is a black fuzzy screen with an error message. Chrome version plays fine on the same OS.

**Comment by LexCovent** [comment]
I'm using OS X Yosemite and I've installed the YouTube Center Safari extension and I got a problem. Every time I play a video, the video doesn't resize to the player window. Theres a black empty space on the player window.
Can anybody help me out?
Thanks
