### ISSUE TITLE
Google Chrome deactivated my extension and won't allow me to activate it again

### ISSUE THREAD

**Issue by CapBlackShot** [YePpHa/YouTubeCenter#524]
![image](https://cloud.githubusercontent.com/assets/7877725/3267160/b04d2940-f2c5-11e3-9b63-2097330bc735.png)

Guys, what happened? I can not activate it again. Chrome says it may be unsafe and deactivated it automatically.

**Comment by razeenmk** [comment]
@ChromeCanary  thanks. enabling extension api worked for me.

**Comment by Noah670** [comment]
Terrible
