### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by mikhaelkh** [YePpHa/YouTubeCenter#599]
When I try to download any file from https://www.youtube.com/watch?v=7-7knsP2n5w I get videoplayback.txt file with comment "Error: server problem" on Chromium, can't download on Firefox either. YTC Dev build 330, default extension settings.

**Comment by chrcoluk** [comment]
Sadly this isnt fixed, I get it on the link he posted also on videos posted by a independent music artist, I am guessing youtube has some kind of anti download feature for musical type content.

Using build 533 on chrome.
