### ISSUE TITLE
Seems like I might increase YouTube Center's file size by 26 MB

### ISSUE THREAD

**Issue by YePpHa** [YePpHa/YouTubeCenter#716]
I just found out by a friend of mine that some guys have converted ffmpeg into JavaScript using Emscripten (Mozilla you're awesome) and the file size of that said file is at about 26 MB.

ffmpeg is a commandline tool used to convert media files into other media files. You could merge two files into one where one of the files contains a video source and the other file an audio source. This I will use to make it possible to download 4k videos (or lower) again by downloading both the video source and the audio source and merging them together into a single file that will be playable in your media player.

I will soon release a developer version with a beta version of this where I plan to make it possible to select the quality of the video, the quality of the audio and the output file's format (mp4, webm, avi, mkv, mp3, m4a and etc).

Link to ffmpeg: https://www.ffmpeg.org/.
Link to the JavaScript version of ffmpeg: https://github.com/bgrins/videoconverter.js/.

**Comment by cattleyavns** [comment]
Hi YePpHa, any news about this feature or you dropped it already ?
To be honest it is really interesting, just make a sister version with @resource and everything will be okay :)
