### ISSUE TITLE
Country flags on comments not working again

### ISSUE THREAD

**Issue by Mike-Correa** [YePpHa/YouTubeCenter#735]
They work fine and load very fast on the latest developer version but nothing happens on YePpHa Center v2.1.2 from webstore.

Other issues on both versions:
* ~~Subscriptions page takes like half a second before resizing. The default size by YT will load first.~~
* Video plays for almost 1 second before auto pausing on HTML5 players. Old problem.
* Sometimes the HTML5 player appears before flash for a short time (maybe the same time it takes for HTML to auto-pause) even with agressive flash enabled.

**Comment by ireun** [comment]
Migrating all issues about country flags not working to one issue, check out issue numer "1877"
