### ISSUE TITLE
New "channel playlist link" feature non-functional

### ISSUE THREAD

**Issue by DeeboDK** [YePpHa/YouTubeCenter#784]
The newly added feature to remove playlist video links in channels appears to be non-functional. I've tried it with the option unchecked (which should remove the "&list=yaddayadda" from the url) and with the option checked. There is no change. I've also tried the current developer version (build 369) and the feature is broken in it as well.

I'm using Firefox 31 and the YouTubeCenter 2.1.5 userscript with Greasemonkey

**Comment by C0NPAQ** [comment]
Unfortunately it is broken again.

Thank you so much for your efforts YePpHa. I have written scripts myself to make Youtube usable and I know that it is constant hard work. I already have donated money to you and advertize Youtube Center to everyone. Each time vital features like this break, I feel more in dept to you.

**Comment by C0NPAQ** [comment]
I found this, and it works: 

http://www.reddit.com/r/LifeProTips/comments/247c2u/lpt_youtube_how_to_play_all_videos_from_a_channel/

Add &feature=mfu_in_order&list=UL to the end of the URL.

**Comment by C0NPAQ** [comment]
Wrote Greasemonkey script that does the job: https://openuserjs.org/scripts/C0NPAQ/Youtube_Channel_Playlist
