### ISSUE TITLE
Ability to disable header when viewing videos!

### ISSUE THREAD

**Issue by Eisys** [YePpHa/YouTubeCenter#786]
I'd like to be able disable the header when viewing videos, so the header would be there when on the main page and when on someone's channel but not when viewing a video! The 'Static header' feature sort of works for that and the 'Scroll to player' makes it even better but when I scroll down during a video to check comments or something and then scroll back up, it goes to the very top again and scrolling down a bit again is just too big of a hassle for me( I'm lazy :D ). I like to make my Youtube player as big as possible so the header just gets in the way for me. So I would love to see a way to disable the header or a way to auto-scroll to the player every time I scroll back up

There is an addon called ImprovedTube (http://bit.ly/WMVDeK) that already does this(only disables header when viewing a video and moves the player to the very top) but it has some problems and it makes a video start twice so the viewing experience isn't smooth!

http://imgur.com/IlVTwyZ <-- How it is right now!
http://imgur.com/mFXlcKp <-- How I wish it was like(player is at the very top)!

EDIT! That addon seems to have now fixed the problems but it doesnt work well with YoutubeCenter and when I disable the header, with YTCenter enabled, it leaves an empty space at the top.

**Comment by Yonezpt** [comment]
Here it is, it should work for Firefox and Chrome. Only downside is the google notifications little window won't be visible in order for the smooth animation to work, otherwise you can trade that transition by following the suggestion at the end of this reply, after the userscript link.

https://gist.github.com/Yonezpt/c007c82d9299cfa32f01

Clicking on the `raw` button in the link above should show your greasemonkey/tampermonkey pop-up window.

If you want to trade the transition for the google notifications' window simply change the 14th line to this:

````javascript
        '#masthead-positioner{height:50px}\n' +
````

The behavior is set to only show when you either pause the video or when it is cued. The header will always hide whenever you are playing, buffering or loading a video on the main video pages.

Let me know if it works for you.

**Comment by Eisys** [comment]
Oo thank you so much!
But it does not seem to work alongside YTC for me! It does work without YTC and works really well.
But when YTC is enabled, the header does not go away and if I click on the google notification, the box doesn't appear! Also if I change the bit of code, then the header doesn't go away, but the video is under the header, like this: http://prntscr.com/5ue133 (without YTC ) (With YTC, changing the code makes the google notif. appear but still doesnt hide header)
Here are my YTC settings if needed: http://pastebin.com/hTpQrtmu
I tried changing the static header settings but that didn't work! I even tried resetting to default YTC settings, no change!
Also, the animation of it going away and coming back could be just a tiny bit faster but that's nothing important!

I'm on Chrome Version 40.0.2214.85 beta-m (64-bit) and using latest dev build 462(yay for updated finally!)

Again, thanks so much for doing this, it's using up your own free time and I really appreciate it!

**Comment by Yonezpt** [comment]
Sorry for my mistake, while testing I forgot to test it alongside YTC. I have updated the code, it should work correctly now, you can download it from the same place I instructed before.

If you want to change the transition time to a shorter one all you have to do is change the time to one of your choice, which can be done in line 14. Where it reads `transition:height 1s` change the `1s` to the number you prefer, if you want it to be faster then simply change it to a smaller number, like `0.5s`

To disable the transition and have the notification box appear again you will have to replace the following lines:

````javascript
    var sheet =
        '#masthead-positioner,#masthead-positioner-height-offset{height:50px;transition:height 1s;overflow:hidden}\n' +
        '#body #body-container .hide{height:0 !important;}'
````
with this single line:

````javascript
    var sheet = '#body #body-container .hide{display:none !important;}',
````

**Comment by Eisys** [comment]
Ok, now it works, kind of!

So, now, without YTC, it works fine when going to a video from youtube.com, and works right away but when I refresh the video, then the header doesn't go away until I pause and unpause the video! And also, if I click the YT logo, it will take me to youtube.com and the header will be gone on that page too.

With YTC, it doesn't work right away in any case, I have to pause and unpause the video, then it will go away, it's like the script doesn't get activated right away!

Ok, I did some testing and it seems that SPF being disabled is at fault! I can't use SPF since the auto-resolution doesn't work most of the time with it enabled. So if I enable SPF, your script works perfectly but with SPF disabled, I have to pause and then unpause a video to get the header to go away! 
But even with SPF enabled, if I refresh the video, then the header doesn't go away until a pause and unpause!

**Comment by Yonezpt** [comment]
Try it now and let me know if it works correctly.

**Comment by Yonezpt** [comment]
Woo! YePpHa implemented your request, test it whenever you have the time and let us know how it plays out, @Eisys.

**Comment by KDsMax** [comment]
How about container also, I mean that lower part of the YouTube page: youtube.com###footer-container

**Comment by Yonezpt** [comment]
@KDsMax It is better if you open a dedicated thread request for that.
