### ISSUE TITLE
Option to hide "Recommended for you" videos on watch pages

### ISSUE THREAD

**Issue by xdpirate** [YePpHa/YouTubeCenter#9]
The "Recommended for you" video suggestions on the right hand side on view pages annoy the everliving crap out of me, due to it showing me videos I have absolutely no interest in watching, based on videos I watched a year ago or that my friends have watched or shown me whilst logged into my account. Any option to hide these would be great.

Something like:

``` JavaScript
var matches = document.querySelectorAll("span");
for(i = 0; i < matches.length; i++) {
	if(matches[i].innerHTML == "Recommended for you") {
		matches[i].parentNode.parentNode.removeChild(matches[i].parentNode);
	}
}
```

...I'd make a pull request but I can't make sense of what you got going on here.

**Comment by mrjpaxton** [comment]
Looks like problem is fixed: https://github.com/YePpHa/YouTubeCenter/wiki/Features#Hide_Recommended_Channels

**Comment by ireun** [comment]
Thank you @mrjpaxton! Closing..
