### ISSUE TITLE
Embedded videos not working

### ISSUE THREAD

**Issue by Diftraku** [YePpHa/YouTubeCenter#94]
While having Youtube Center enabled, embedded videos will not load and produce a SecurityError in the console. This happens only when the embed is inside an iframe, breaking the embed out of the iframe and loading it directly allows playing the video.

Chrome 30.0.1599.69 m
YoutubeCenter v2.0.1

```
[URL] https://www.youtube.com/embed/Z4qHbd-mT0M?fs=true&version=3&rel=0&autoplay=1&showsearch=0&showinfo=0&modestbranding=1&wmode=opaque YouTubeCenter.js:1738
In Scope YouTubeCenter.js:1738
Initializing Functions YouTubeCenter.js:1738
Initializing icons YouTubeCenter.js:1738
Uncaught SecurityError: An attempt was made to break through the security policy of the user agent. YouTubeCenter.js:7803
  (anonymous function) YouTubeCenter.js:7803
  (anonymous function) YouTubeCenter.js:8159
  (anonymous function) YouTubeCenter.js:17560
  inject YouTubeCenter.js:48
  (anonymous function) YouTubeCenter.js:17705
  (anonymous function) YouTubeCenter.js:17731
[writeEmbed] Externally Called (most likely by YouTube) YouTubeCenter.js:1738
```

**Comment by megaspel** [comment]
I'm getting a similar problem suddenly. While the firefox YouTube Center 2.1.7 extension is enabled, all embedded youtube videos remain entirely black with this in the console:

> This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] UJjLpPikLKE
> "Domain registered www.youtube.com."

**Comment by cedrik17** [comment]
I have same problem like @megaspel and i dont completely understand this certicate thing. Im using firefox and Windows 7 64 bit.

**Comment by cedrik17** [comment]
anyone?

**Comment by erolcanulutas** [comment]
Same here. Help please.

**Comment by YePpHa** [comment]
Please open a new issue with a reference to this issue instead of continuing this _old_ issue. Anyway, I will recommend you to try the [developer version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version).

**Comment by erolcanulutas** [comment]
Developer version solved the problem. Thanks.
