### ISSUE TITLE
Country flags are not shown

### ISSUE THREAD

**Issue by abstain** [YePpHa/YouTubeCenter#978]
When expand comments country flags are not shown
Opera 12
YTC 2.1.1 as extension
or YTC 2.1.5 via Violent monkey 1.6.3
![Image](https://dl.dropboxusercontent.com/u/83035777/%D0%9A%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%BE%D0%BF%D0%BE%D0%BC%D0%BE%D0%B9%D0%BA%D0%B0/flag.png)

**Comment by ireun** [comment]
Migrating all issues about country flags not working to one issue, check out issue number "1877",
